### DISCUSSION TITLE
How to run ing requests for controlling z/OS system automation

### DISCUSSION THREAD

**Discussion by wmike** [ansible-collections/ibm_zos_core#1500] [Q&A]
I need to restart started tasks controlled by z/OS system automation (netview ?).

Therefore I converted a working jcl to an ansible task:
```
    - name: SAO Call MVS Raw
      ibm.ibm_zos_core.zos_mvs_raw:
        program_name: IKJEFT01
        auth: true
        verbose: true
        dds:
          - dd_output:
              dd_name: SYSTSPRT
              return_content:
                type: text
          - dd_input:
              dd_name: SYSTIN
              content: "EX 'SYS1.ING.SINGTREX(AOFRYCMD)' SERVER=* HIGHRC=00 MAXRC=00"
          - dd_dummy:
              dd_name: SYSIN
```

I just skipped the ingrequest in SYSIN for a minimal example.
Execution of this tasks fails with:
```
fatal: [lpar1]: FAILED! => {
    "backups": [],
    "changed": false,
    "dd_names": [],
    "ret_code": {
        "code": 8
    }
}

MSG:

ZOSRawError('An error occurred during execution of z/OS program IKJEFT01.  BGYSC0307I Program: <IKJEFT01> Arguments: <>\nBGYSC0308I DDNames:\nBGYSC0311I   SYSIN=DUMMY\nBGYSC0312I   SYSTIN=USERID.P3951854.T0847984.C0000000\nBGYSC0312I   SYSTSPRT=USERID.P3952484.T0801916.C0000000\nBGYSC0306I DUMMY Dynalloc succeeded for SYSIN=DUMMY\nBGYSC0303I Dataset allocation succeeded for SYSTIN=USERID.P3951854.T0847984.C0000000\nBGYSC0303I Dataset allocation succeeded for SYSTSPRT=USERID.P3952484.T0801916.C0000000\nBGYSC0328I OS Load program IKJEFT01\nBGYSC0319I Program is APF authorized\nBGYSC0320I Addressing mode: AMODE31\nBGYSC0341I signal 9 issued for child process IKJEFT01\nBGYSC0232E Child process did not complete correctly for IKJEFT01.\nBGYSC0354I Dummy free succeeded for SYSIN\nBGYSC0338I Dataset free succeeded for SYSTIN=USERID.P3951854.T0847984.C0000000\nBGYSC0338I Dataset free succeeded for SYSTSPRT=USERID.P3952484.T0801916.C0000000\n'
``` 

Since I _only_ run a script I tried to use zos_tso_command as well:
```
    - name: SAO Call TSO Command
      ibm.ibm_zos_core.zos_tso_command:
        commands:
          - EX 'SYS1.ING.SINGTREX(AOFRYCMD)' 'SERVER=* HIGHRC=00 MAXRC=00'
        max_rc: 0
```
This module can execute the batch interface program and tries to read data from SYSIN:
```
changed: [lpar] => {
    "changed": true,
    "max_rc": 0,
    "output": [
        {
            "command": "EX 'SYS1.ING.SINGTREX(AOFRYCMD)' 'SERVER=* HIGHRC=00 MAXRC=00'",
            "content": [
                "EVJ040I Processing Commands:",
                "IRX0555E The input or output file SYSIN is not allocated. It cannot be opened for I/O.  ",
                "IRX0670E EXECIO error while trying to GET or PUT a record.   ",
                ""
            ],
            "failed": false,
            "lines": 4,
            "rc": 0,
            "stderr": ""
        }
    ]
}
```
I did not find any way in the documentation to allocate additonal dd statements for zos_tso_commands.

I need help to run batch interface for system automation successfull as an ansible task without submitting a job.
