### DISCUSSION TITLE
ibm_zos_core - 1.8.0 - Copy fails if destination library is migrated to tape

### DISCUSSION THREAD

**Discussion by rohan-zos-ansible** [ansible-collections/ibm_zos_core#1571] [General]
Usually, I see copy members function from zos_core - copy is failing when destination library is migrated. I need to physically recall it first and then run this copy function.

Error snap:
```

    "msg": "Failure during execution of mvscmd; Return code: 4; stdout: 1IDCAMS  SYSTEM SERVICES                                           TIME: 10:03:54        07/04/24     PAGE      1\n0        \n  LISTCAT ENT('DBU.QA.TXO4.DBDLIB') DATA ALL\n0IDC1565I DBU.QA.TXO4.DBDLIB NOT A REQUESTED TYPE\n1IDCAMS  SYSTEM SERVICES                                           TIME: 10:03:54        07/04/24     PAGE      2\n0         THE NUMBER OF ENTRIES PROCESSED WAS:\n0                   AIX -------------------0\n                    ALIAS -----------------0\n                    CLUSTER ---------------0\n                    DATA ------------------0\n                    GDG -------------------0\n                    INDEX -----------------0\n                    NONVSAM ---------------0\n                    PAGESPACE -------------0\n                    PATH ------------------0\n                    SPACE -----------------0\n                    USERCATALOG -----------0\n                    TAPELIBRARY -----------0\n                    TAPEVOLUME ------------0\n                    TOTAL -----------------0\n0         THE NUMBER OF PROTECTED ENTRIES SUPPRESSED WAS 0\n0IDC0001I FUNCTION COMPLETED, HIGHEST CONDITION CODE WAS 4\n0        \n0IDC0002I IDCAMS PROCESSING COMPLETE. MAXIMUM CONDITION CODE WAS 4\n; stderr: ",
    "rc": null,
    "stderr": null,
    "stderr_lines": null,
    "stdout": null,
    "stdout_lines": null

``` 
Source Code -
```
  tasks: 
    - name: Copy Pre-compiled IMS Catalog DBDs from Latest IMS Release - 15
      ibm.ibm_zos_core.zos_copy:
        src: "IMSVS.R15M.SDFSRESL({{ item }})"
        dest: "{{ DFS_IMS_HLQGROUP2 }}.DBDLIB({{ item }})" 
        remote_src: yes
        volume: "{{ DFS_DS_VOLUME1 }}"
        force: true 
      loop: [DFSCD000,DFSCX000]    

    - name: Copy Pre-compiled IMS Catalog PSBs from Latest IMS Release - 15
      ibm.ibm_zos_core.zos_copy:
        src: "IMSVS.R15M.SDFSRESL({{ item }})"
        dest: "{{ DFS_IMS_HLQGROUP2 }}.PSBLIB({{ item }})"
        remote_src: yes
        volume: "{{ DFS_DS_VOLUME1 }}"
        force: true
      loop: [DFSCPL00,DFSCP000,DFSCP001,DFSCP002,DFSCP003]
```
