### DISCUSSION TITLE
Want to remove a block from PDS member

### DISCUSSION THREAD

**Discussion by rohan-zos-ansible** [ansible-collections/ibm_zos_core#1667] [Q&A]
I want to remove a block between # BEGIN and # END from a PDS member with the help of blockinfile module.
```
SCRIPT +                                              
# BEGIN ANSIBLE MANAGED BLOCK                         
       UTIDSN(ZZZDBU.V51QA.SMPE.DBUSCRL +             
       ZZZBRI.QAV51.BRISCRL  +                        
       ZZZCDBU.V51QA.SMPE.DBUSCRS  +                   
       ZZZCBRI.QAV51.BRISCRS) +                        
       SYSOUT(*) TRACE(Y) TRACEOUT(*)                 
# END ANSIBLE MANAGED BLOCK            
```   

Code:
```
        - name: Remove some libraries from Scripts in INI file
          ibm.ibm_zos_core.zos_blockinfile:
            src: "PDS.ANSIBLE.WORK.CNTL(TRZSINI)"
            marker_begin: "# BEGIN ANSIBLE MANAGED BLOCK                                           "
            marker_end: "# END ANSIBLE MANAGED BLOCK                                             "
            state: absent 
```

 Not sure what mistake i am doing. If anyone has any knowledge on this, please let me know.

Thank you,
Rohan
