### DISCUSSION TITLE
Question: zos_submit It is possible submit more than 1 element?

### DISCUSSION THREAD

**Discussion by JCzOS** [ansible-collections/ibm_zos_core#1680] [General]
Hi all, 

I am creating some JCLs using a loop, this JCL is located on USS and I submit them using:

```
    - name: Submit de JCLS
      ibm.ibm_zos_core.zos_job_submit:
        src: "/u/ibmuser/jcls/{{ item }}"
        wait_time_s: 86400
        location: USS  
        max_rc: 8
      loop: "{{ file_list.stdout_lines }}" 
``` 
      

I dont know (and didnt found doc.)  about if it is possible to submit all Jcls in paralell.

At this time, jcls are submitted approximately 10 minutes apart from one to the next. And Any job is around 2 minutes.

 I am also not able to use wait_time_s in rigth way, I am always facing this issue:
 
 failed: [lrdtts02] (item=bindpla1.jcl) => {"ansible_loop_var": "item", "changed": false, "duration": 46, "item": "bindpla1.jcl", "job_id": null, "msg": "The job /u/ibmuser/jcls/bindpla1.jcl has been submitted and no job id was returned within the allocated time of 86400 seconds. Without the job id, the error can not be determined, consider using module `zos_job_query` to poll for the job by name or review the system log for purged jobs resulting from an abend."}

failed: [lrdtts02] (item=bindpla2.jcl) => {"ansible_loop_var": "item", "changed": false, "duration": 56, "item": "bindpla2.jcl", "job_id": null, "msg": "The job /u/ibmuser/jcls/bindpla2.jcl has been submitted and no job id was returned within the allocated time of 86400 seconds. Without the job id, the error can not be determined, consider using module `zos_job_query` to poll for the job by name or review the system log for purged jobs resulting from an abend."}

Thanks in advance.
