### DISCUSSION TITLE
z/OS core - Job submit failed

### DISCUSSION THREAD

**Discussion by ghost** [ansible-collections/ibm_zos_core#716] [Q&A]
I'm using z/OS core 1.4.0 to submit jobs and encountering the following situation:

  - When the sysout is small or the job abends with return-code 12, the automation ends correctly and I manage to handle the sysout.

  - When the sysout is large, the automation return fails with the error in the image below, but in the mainframe it runs normally.
  
![image](https://user-images.githubusercontent.com/105386204/228886847-3db7ed25-3e66-4886-82f4-e3c2a7584859.png)

  
Obs.:I already tried with return output false and true
Obs.: I already increased the size of the user's TSO session on the mainframe, the user's /home on the control node but I can't identify exactly what the problem is.

**Comment by ddimatos** [comment]
Hello @fabiobncbb 
I'll look closer at this shortly, I have a suspicion this is related to an issue a user raised in an email to me that I was not able to reproduce and later when I engaged them they were not able to allocate time to further this along which left the analysis incomplete.
 
I would be happy to help and it just happens we might still have a customized build you could try that would answer if this issue is yours as well , [here](https://github.com/ansible/ansible/issues/80379). If I recall you might have challenges installing updates, I'll  review on Monday and reach out you.

**Comment by ddimatos** [comment]
@fabiobncbb by any chance did you noticed any system log entries that look like:
```
INSUFFICIENT STORAGE
NOT ENOUGH STORAGE FOR BUFFER
```

**Reply by ghost** [reply]
Unfortunately no, in the z/OS log messages this message does not appear.

Today, scanning the log messages of both executions (successfully and unsuccessfully), I identified a SEC6 abend in the execution where I cannot capture the sysout, but I could not advance in this analysis. 

![image](https://user-images.githubusercontent.com/105386204/229930645-0be3584d-852d-4085-b3be-515675eb410b.png)


Esta é a única diferença que encontrei entre as duas execuções até o momento.

**Comment by ddimatos** [comment]
So I did trace it down to the [code](https://github.com/ansible/ansible/blob/322366620f9422fe2c813fc6f9a1308790ae6161/lib/ansible/module_utils/basic.py#L2054) which threw the [exception](https://github.com/ansible/ansible/blob/322366620f9422fe2c813fc6f9a1308790ae6161/lib/ansible/module_utils/basic.py#L2087)  which then was propagated by our code instead of capturing it which would not change anything. 

From what I can see without a recreate is that after our REXX code ran which collected the job log, the Ansible engine code started reading stdout and and appending it to a variable which for some reason appears to run out of storage/heap. The issue I noted in the post #[80379](https://github.com/ansible/ansible/issues/80379) is not the same issue, although its in the same ansible api. 

I have one idea, this would not work for issue #[80379](https://github.com/ansible/ansible/issues/80379) but might work for this, and that is to force the stdout and stderr streams to be unbuffered by using environment variable [PYTHONUNBUFFERED](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUNBUFFERED).

You should be able to do this by passing it to your environment vars like so `PYTHONUNBUFFERED: 1`.
```
environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  JAVA_HOME: "{{ JAVA }}"
  PYTHONPATH: "{{ ZOAU }}/lib"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin:{{ JAVA }}/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
  PYTHONUNBUFFERED: 1
```

Try this and see if it helps, if you have any stats/info on the joblog size in terms of kb or lines we might be able to reproduce it.
