### ISSUE TITLE
[Bug] [zos_copy] Investigate if an alias of a LOADLIB can be a 'src'

### ISSUE THREAD

**Issue by ketankelkar** [ansible-collections/ibm_zos_core#1013]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.4

### IBM Enterprise Python

v3.9.x

### IBM z/OS Ansible core Version

v1.8.0-beta.1

### ansible-version

latest

### z/OS version

v2.5

### Ansible module

zos_copy

### Bug description

See internal slack thread - CSLEJ8VGV/p1696613056253019 - from the ansible z collections guild channel.

The user is trying to copy a PDS `IMSBLD.I15STSMM.SDFSRESL` to a PDS. The user reported it did not make a different whether or not the destination data set existed prior.

The src appears to be an alias:
![image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/68c38f09-6fd1-42c6-9804-84eb689ce8fe)

`dls` seems to be unable to find that particular data set name. 

```bash
bash-4.3# dls IMSBLD.I15STSMM.SDFSRESL
bash-4.3# dls -a IMSBLD.I15STSMM.SDFSRES
BGYSC1103E No datasets match pattern: IMSBLD.I15STSMM.SDFSRES.
```

However, `dcp` with an existing target at least begins copying over members. I terminated the copy when it looked like it had hung because it was taking a long time. Aliases seem to be preserved in the destination loadlib.
```bash
bash-4.3# dtouch -tpdse -rU -l0 user.test.loadlib
bash-4.3# dcp -IX IMSBLD.I15STSMM.SDFSRESL user.test.loadlib
bash-4.3#
bash-4.3# mls user.test.loadlib
BPEAQHT0
BPEAWCR0
BPEAWI00
...
DBFDAX10
DBFDBAC0 ALIAS(DBFDBAC1 DBFDBAC2 DBFDBAC3 DBFDBAC4)
DBFDBAC5
...
```

**Comment by richp405** [comment]
Jira id 9996 with Joel

**Comment by richp405** [comment]
Tick #10141 merged into 1.3 pre build

**Comment by ketankelkar** [comment]
The internal jira ticket `#9996` mentioned above is not related to this git issue. 
`#9996` has to do with the call to `dls -al` producing incorrect output. That is not a concern here.

`#10141` has been re-opened. The fix that was delivered seemed not to address the use case where the `src` data set itself is an alias. Details on recreating a data set library that is an alias can be found in the jira. 

Below is a playbook with ZOAU 1.3.x to recreate this issue. Note, it it's current state, it MUST be run on the ECs (z/VMs) because the relevant data set (`IMSBLD.I15STSMM.SDFSRESL`)is only present there.

```yml
  tasks:

  - name: set facts
    ansible.builtin.set_fact:

      DEFAULT_DATA_SET_NAME: "KETAN.ANSIBLE.TESTDS"

  - name: do some stuff
    block:
    - name: copy lib to lib
      zos_copy:
        src: "IMSBLD.I15STSMM.SDFSRESL"
        dest: "{{ DEFAULT_DATA_SET_NAME }}"
        aliases: yes
        remote_src: yes
```
