### ISSUE TITLE
[Documentation] [zos_tso_command] Add module examples on how to execute REXX scripts

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1021]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Documentation issue description

This issue is so that examples of running REXX scripts contained in data sets are demonstrated. This would allow for users to know how to execute a REXX exec, more on this topic in this git issue #427.

### IBM z/OS Ansible core Version

None

### Ansible module

zos_tso_command

**Comment by rexemin** [comment]
Taken from the sample playbook showcasing how to run REXX with a TSO command:

```yaml
- name: Copy file to a new data set.
  ibm.ibm_zos_core.zos_copy:
    src: ./files/DSINFO
    dest: "{{ script_data_set }}"
    remote_src: false

- name: Run REXX script from MVS.
  ibm.ibm_zos_core.zos_tso_command:
    commands:
      - EXEC '{{ script_data_set }}' '{{ rexx_args }}' exec
```

Since TSO allows executing implicitly or explicitly, the above example runs a REXX script or CLIST explicitly, hence the use of `EXEC` and `exec` in the same command. Data set names have to contain a HLQ.
