### ISSUE TITLE
[Bug] [zos_copy] MVS to non-existent MVS copy - verify destination atttrs match up 

### ISSUE THREAD

**Issue by ketankelkar** [ansible-collections/ibm_zos_core#1022]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.4

### IBM Enterprise Python

v3.12.x

### IBM z/OS Ansible core Version

v1.7.0

### ansible-version

latest

### z/OS version

v2.5

### Ansible module

zos_copy

### Bug description

Copying a load object from a src loadlib to a non-existent loadlib via zos_copy yielded a destination library with attributes slightly larger than the src according to `dls -s`. ISPF shows 2 extra tracks allocated in the destination. 

The point to investigate is whether allocated data sets are created with ever-increasing sizes or if there's only some rounding error or something else. The concern is if data set allocations keep growing between back and forth copies. 

```bash
>dls -s KETAN.ZCPY.DESTLIB.DISPSHR
KETAN.ZCPY.DESTLIB.DISPSHR                   PO  U        0 X9TSO8           ??      4929768
>dls -s KETAN.ZCPY.srclib         
KETAN.ZCPY.SRCLIB                            PO  U        0 X9TSO4           ??      4816440
```
![image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/d4c535a0-cdaf-4b78-957a-1da3eb8c23b7)

![image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/1b275166-3afd-4669-adcd-bcd665c54c3e)

### Playbook verbosity output.

actual playbook:
```yaml
---
- name: Demo zos_copy - aliases w force_lock option.
  hosts: np8
  collections:
    - "ibm.ibm_zos_core"
  gather_facts: no

  vars:
    hlq: "{{ ansible_user | upper }}"

    mem1: "MEM1"
    mem2: "MEM2"
    alias1: "MEM1A"

    pgms:
      - "{{ mem1 }}"
      - "{{ alias1 }}"
      - "{{ mem2 }}"

    src_pds_name: "{{ hlq }}.ZCPY.SRCPDS"
    src_lib_name: "{{ hlq }}.ZCPY.SRCLIB"

    mvscmdstr: "mvscmd --steplib='%s' --pgm='%s' --sysout='*'"

    # dest PDSs
    dest_lib_from_srclib: "{{ hlq }}.ZCPY.DESTLIB.NOALIAS"
    dest_lib_from_srclib_w_aliases: "{{ hlq }}.ZCPY.DESTLIB.ALIASES"
    dest_lib_disp_shr: "{{ hlq }}.ZCPY.DESTLIB.DISPSHR"

    # dest uss dir
    # uss_base_dir: "{{ '/home/ketan/aliases' if ansible_user == 'ketan' else '/u/oeusr01/'}}"
    # uss_demo_dir: "{{ uss_base_dir }}/demo"
    # uss_dest_dir: "{{ uss_demo_dir }}/aliases"

    COBOL_HLQ: ADCOB370

  environment: "{{ environment_vars }}"


  tasks:

################################################################################
# Show off SRC loadlib
################################################################################

  - name: "mls {{ src_lib_name }}."
    shell: mls '{{ src_lib_name }}'
    register: mls_src_lib_output
  
  - name: "Exec pgms in {{ src_lib_name }}"
    shell: "{{ mvscmdstr | format(src_lib_name, item) }}"
    loop: "{{ pgms }}"
    register: exec_src_lib_output

  - name: Print mls and pgm exec results.
    debug:
      msg:
      - "{{ mls_src_lib_output.stdout }}"
      - ""
      - "mem1  {{ exec_src_lib_output.results[0].stdout | trim }}"
      - "mem1a {{ exec_src_lib_output.results[1].stdout | trim }}"
      - "mem2  {{ exec_src_lib_output.results[2].stdout | trim }}"

################################################################################
# leverage force_lock to copy load object into loadlib.
################################################################################

  - name: Ensure destination loadlib is not present.
    zos_data_set:
      name: "{{ item }}"
      state: absent
    loop:
      - "{{ dest_lib_disp_shr }}"

  - name: "Copy load object into non-existent lib - {{ dest_lib_disp_shr }}"
    zos_copy:
      src: "{{ src_lib_name }}({{ mem2 }})"
      dest: "{{ dest_lib_disp_shr }}({{ mem2 }})"
      remote_src: yes
      executable: yes

  - name: "mls {{ dest_lib_disp_shr }}."
    shell: mls '{{ dest_lib_disp_shr }}'
    register: mls_dest_lib_disp_shr_output

  - name: "Exec pgms in {{ dest_lib_disp_shr }}"
    shell: "{{ mvscmdstr | format(dest_lib_disp_shr, item) }}"
    loop: 
      - "{{ mem2 }}"
    register: exec_dest_lib_disp_shr_output

  - name: "print output for copy to {{ dest_lib_disp_shr }}"
    debug:
      msg:
      - "{{ mls_dest_lib_disp_shr_output.stdout | trim }}"
      - ""
      - "mem2  {{ exec_dest_lib_disp_shr_output.results[0].stdout | trim }}"

  - name: "Pause to acquire lock via ISPF on {{ dest_lib_disp_shr }}."
    pause:
      prompt:
        - "Press Enter after verifying lock by running: opercmd 'd grs,res=(*,{{ dest_lib_disp_shr }})'."

  #----------------------------------------------------------------------------#
  # zos_copy - attempt w/o any special options (ie -- no force, no force_lock) #
  #----------------------------------------------------------------------------#
  - name: "copy mem1 and its alias to a locked loadlib {{ dest_lib_disp_shr }}"
    zos_copy:
      src: "{{ src_lib_name }}({{ mem1 }})"
      dest: "{{ dest_lib_disp_shr }}"
      remote_src: yes
      executable: yes
      aliases: yes
    ignore_errors: yes

  #----------------------------------------------------------------------------#
  # zos_copy - attempt w force=True, no force_lock -- ie "as-is" for 1.7.0     #
  #----------------------------------------------------------------------------#
  - name: "copy mem1 and its alias to a locked loadlib {{ dest_lib_disp_shr }} w force"
    zos_copy:
      src: "{{ src_lib_name }}({{ mem1 }})"
      dest: "{{ dest_lib_disp_shr }}"
      remote_src: yes
      executable: yes
      aliases: yes
      force: yes
    ignore_errors: yes

  #----------------------------------------------------------------------------#
  # zos_copy - showcases feature - `force_lock` option                         #
  #----------------------------------------------------------------------------#
  - name: "copy mem1 and its alias to a locked loadlib {{ dest_lib_disp_shr }} w force_lock"
    zos_copy:
      src: "{{ src_lib_name }}({{ mem1 }})"
      dest: "{{ dest_lib_disp_shr }}"
      remote_src: yes
      executable: yes
      aliases: yes
      force_lock: yes
    ignore_errors: yes

  - name: "mls {{ dest_lib_disp_shr }}."
    shell: mls '{{ dest_lib_disp_shr }}'
    register: mls_dest_lib_disp_shr_2_output

  - name: "Exec pgms in {{ dest_lib_disp_shr }}"
    shell: "{{ mvscmdstr | format(dest_lib_disp_shr, item) }}"
    loop: "{{ pgms }}"
    register: exec_dest_lib_disp_shr_output

  - name: "print output for copy to {{ dest_lib_from_srclib }}"
    debug:
      msg:
      - "{{ mls_dest_lib_disp_shr_2_output.stdout | trim }}"
      - ""
      - "mem1  {{ exec_dest_lib_disp_shr_output.results[0].stdout | trim }}"
      - "mem1a {{ exec_dest_lib_disp_shr_output.results[1].stdout | trim }}"
      - "mem2  {{ exec_dest_lib_disp_shr_output.results[2].stdout | trim }}"

```
