### ISSUE TITLE
[Bug] Error in zos_find.py

### ISSUE THREAD

**Issue by guikarai** [ansible-collections/ibm_zos_core#1062]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.5

### IBM Enterprise Python

v3.12.x

### IBM z/OS Ansible core Version

v1.7.0

### ansible-version

latest

### z/OS version

v2.5

### Ansible module

zos_find

### Bug description

Hello,

There is an error find in zos_find.py in line 482.
The split on item 5 must be on item 6.

This generate an error when we try to use the followig task as exemple.

- name: Find all data sets greater than 2MB and allocated in one of the specified volumes
      zos_find:
        patterns: 'BENCHRES.XXXXXXXX.*'
        size: 2m

Once fixed on client side, it works as expected.

### Playbook verbosity output.

The full traceback is:
Traceback (most recent call last):
  File "/u/hoareau/.ansible/tmp/ansible-tmp-1700059475.89395-98730-121024297223368/AnsiballZ_zos_find.py", line 107, in <module>
    _ansiballz_main()
  File "/u/hoareau/.ansible/tmp/ansible-tmp-1700059475.89395-98730-121024297223368/AnsiballZ_zos_find.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/u/hoareau/.ansible/tmp/ansible-tmp-1700059475.89395-98730-121024297223368/AnsiballZ_zos_find.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.ibm.ibm_zos_core.plugins.modules.zos_find', init_globals=dict(_module_fqn='ansible_collections.ibm.ibm_zos_core.plugins.modules.zos_find', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_zos_find_payload_9fk41uqz/ansible_zos_find_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_find.py", line 895, in <module>
  File "/tmp/ansible_zos_find_payload_9fk41uqz/ansible_zos_find_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_find.py", line 891, in main
  File "/tmp/ansible_zos_find_payload_9fk41uqz/ansible_zos_find_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_find.py", line 784, in run_module
  File "/tmp/ansible_zos_find_payload_9fk41uqz/ansible_zos_find_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_find.py", line 482, in data_set_attribute_filter
ValueError: invalid literal for int() with base 10: '??'

### Ansible configuration.

```YAML
,
```

### Contents of the inventory

```YAML
source_system:
  hosts:
    TCL1:
      ansible_host: 9.212.129.18
      ansible_user: hoareau
      ansible_python_interpreter : /usr/lpp/IBM/cyp/v3r11.p/pyz/bin/python3
    TCL2:
      ansible_host: 9.212.129.118
      ansible_user: hoareau
      ansible_python_interpreter : /usr/lpp/IBM/cyp/v3r11.p/pyz/bin/python3
```

### Contents of `group_vars` or `host_vars`

```YAML
environment_vars:
_BPXK_AUTOCVT: ON
ZOAU_ROOT: '/usr/lpp/IBM/zoautil/v1r2m5.p'
PYTHONPATH: '/usr/lpp/IBM/zoautil/v1r2m5.p/lib'
LIBPATH: '/usr/lpp/IBM/zoautil/v1r2m5.p/lib/:V2R5/usr/lpp/IBM/cyp/v3r11.p/pyz/lib:/usr/lib:/lib:.'
PATH: '/usr/lpp/IBM/zoautil/v1r2m5.p/bin;V2R5/usr/lpp/IBM/cyp/v3r11.p/pyz/bin'
```
