### ISSUE TITLE
[Enabler] [Dev] [zos_operator] Migrate module, module utilities and test cases to ZOAU 1.3

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1112]
## Ansible module
`zos_operator`

### See Epic
[[Enabler] [Epic] Adopt new ZOAU 1.3 Python changes](https://github.com/ansible-collections/ibm_zos_core/issues/931)

### Enabler description

With the adoption of ZOAU 1.3, modules, module utilities and test cases may need to be updated according to the [migration guide](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier). 

APIs changes affecting module:
- Impacted by ZOAU Dataset API: No
- Impacted by ZOAU jobs API: No
- Impacted by the rename of types.py to ztypes.py: No
- Impacted by the contents of module volumes.py having been moved to datasets.py: No
- Impacted by opercmd timeout to milli sec: Yes
- Impacted by JSON schema change: No
- Impacted by Exceptions schema: No

Review the [zoautil_py datasets module migration doc](https://www.ibm.com/docs/en/zoau/1.3.x?topic=planning-migrating-zoau-v13-from-v12x-earlier#changes-to-the-datasets-module).

Upon review, this module is affected by:
- the opercmd utility argument timeout returns time in hundredths of a second (0.01 sec) rather than seconds
   - see: `def execute_command(operator_cmd, timeout=1, *args, **kwargs):`
   - see: `response = opercmd.execute(operator_cmd, timeout, *args, **kwargs)`
   - see: `rc, stdout, stderr, elapsed = execute_command(cmdtxt, timeout=wait_s, *args, **kwargs)`
   - NOTE: We will need to decide if we will leave the module timeout as seconds and perform conversions in the code or we should update the module interface to milliseconds but that might be to small an increment to make sense for a module that performs poorly over a newtwork. 

This issue depends on shared import identified by git issues:
- [module_utils/better_arg_parser.py](https://github.com/ansible-collections/ibm_zos_core/issues/1116)

**Comment by ketankelkar** [comment]
Best I can tell, there is no content that is returned from ZOAU opercmd that contains the timeout value in seconds or centiseconds. Therefore, there were no changes made to the zos_operator code as part of the migration which address changing the timeout value "back" to seconds. The "elapsed" field is part of the zos_operator module return structure, however, it is calculated on the Ansible side and therefore has no bearing on the unit of measurement of 'timeout' from ZOAU opercmd.

The only reference to centiseconds I found was when the `opercmd` utility is run in shell.
```
bash-4.3# opercmd -J 'd u,all'
{
	"data": {
		"output": "IEE457I 12.04.27 UNIT STATUS 436\nUNIT TYPE STATUS        VOLSER     VOLSTATE      SS\n0000 3390 F-NRD                        /RSDNT     0\n0001 3211 OFFLINE                                 0\n0002 3211 OFFLINE                                 0\n0003 3211 OFFLINE                                 0\n0004 3211 OFFLINE                                 0\n0005 3211 OFFLINE                                 0\n0006 3211 OFFLINE                                 0\n0007 3211 OFFLINE                                 0\n0008 3211 OFFLINE                                 0\n0009 3277 OFFLINE                                 0\n000C 2540 A                                       0\n000D 2540 A                                       0\n000E 1403 A                                       0\n000F 1403 A                                       0\n0010 3211 A                                       0\n0011 3211 A                                       0\n"
	},
	"timestamp": "2024023  12:04:27.00",
	"timeout": 100,
	"command": "D U,ALL",
	"program": "opercmd",
	"options": "-J ",
	"rc": "0"
}

```
However, the python interface, which is what's leveraged in the module, does not currently seem to return the timeout value
```python
>>> a=opercmd.execute('d u,all', 1)
>>>
>>> pprint(a.to_dict())
{'command': 'opercmd -T 1 -- "d u,all "',
 'rc': 0,
 'response_format': 'UTF-8',
 'stderr_response': '',
 'stdout_response': 'EC01148A   2024023  12:10:28.00             ISF031I '
                    'CONSOLE OMVS0000 ACTIVATED\n'
                    'EC01148A   2024023  12:10:28.00            -D U,ALL \n'
                    'EC01148A   2024023  12:10:28.00             IEE457I '
                    '12.10.28 UNIT STATUS 444\n'
                    '                                           UNIT TYPE '
                    'STATUS        VOLSER     VOLSTATE      SS\n'
                    '                                           0000 3390 '
                    'F-NRD                        /RSDNT     0\n'
                    '                                           0001 3211 '
                    'OFFLINE                                 0\n'
                    '                                           0002 3211 '
                    'OFFLINE                                 0\n'
                    '                                           0003 3211 '
                    'OFFLINE                                 0\n'
                    '                                           0004 3211 '
                    'OFFLINE                                 0\n'
                    '                                           0005 3211 '
                    'OFFLINE                                 0\n'
                    '                                           0006 3211 '
                    'OFFLINE                                 0\n'
                    '                                           0007 3211 '
                    'OFFLINE                                 0\n'
                    '                                           0008 3211 '
                    'OFFLINE                                 0\n'
                    '                                           0009 3277 '
                    'OFFLINE                                 0\n'
                    '                                           000C 2540 '
                    'A                                       0\n'
                    '                                           000D 2540 '
                    'A                                       0\n'
                    '                                           000E 1403 '
                    'A                                       0\n'
                    '                                           000F 1403 '
                    'A                                       0\n'
                    '                                           0010 3211 '
                    'A                                       0\n'
                    '                                           0011 3211 '
                    'A                                       0\n'}
>>> 


```

**Comment by ketankelkar** [comment]
When the verbose option is turned on, there is a reference to `centiseconds` in the output. However, the output does mention the unit o f measurement as centiseconds and therefore I do not think intercepting and converting the output is warranted:
```yml
  - name: test_zos_operator_positive_path_verbose
    ibm.ibm_zos_core.zos_operator:
      cmd: "d u,all"
      verbose: True
    register: result
  - name: print result
    debug:
      var: result
```

```yml
TASK [print result] ******************************************************************************************************************************************************************************************************************
task path: <.. omitted ..>
Tuesday 23 January 2024  15:08:45 -0800 (0:00:22.375)       0:01:23.949 ******* 
ok: [zvm] => {
    "result": {
        "changed": true,
        "cmd": "d u,all",
        "content": [
            "<omitted>   2024023  15:08:43.00             ISF031I CONSOLE OMVS0000 ACTIVATED",
            "<omitted>   2024023  15:08:43.00            -D U,ALL ",
            "<omitted>   2024023  15:08:43.00             IEE457I 15.08.41 UNIT STATUS 768",
            "                                           UNIT TYPE STATUS        VOLSER     VOLSTATE      SS",
            "                                           0000 3390 F-NRD                        /RSDNT     0",
            "                                           0001 3211 OFFLINE                                 0",
            "                                           0002 3211 OFFLINE                                 0",
            "                                           0003 3211 OFFLINE                                 0",
            "                                           0004 3211 OFFLINE                                 0",
            "                                           0005 3211 OFFLINE                                 0",
            "                                           0006 3211 OFFLINE                                 0",
            "                                           0007 3211 OFFLINE                                 0",
            "                                           0008 3211 OFFLINE                                 0",
            "                                           0009 3277 OFFLINE                                 0",
            "                                           000C 2540 A                                       0",
            "                                           000D 2540 A                                       0",
            "                                           000E 1403 A                                       0",
            "                                           000F 1403 A                                       0",
            "                                           0010 3211 A                                       0",
            "                                           0011 3211 A                                       0",
            "BGYSC0804I Using timeout of 100 centiseconds.",
            "BGYSC0801I CONSBUFPGNUM=128 - Console command output buffer memory size to be allocated: 131072 bytes.",
            "BGYSC0806I Using console name of OMVS0000.",
            "BGYSC0805I Using CART of ZOAU1208.",
            "BGYSC0802I Console command returned output string size of 917 bytes."
        ],
        "elapsed": 18.15,
        "failed": false,
        "rc": 0,
        "wait_time_s": 1
    }
}
```

**Comment by ketankelkar** [comment]
The following playbook recreates the zos_operator functional tests as of today. Running this playbook in verbose mode (`-vvv`) very effectively illustrates all the output this module creates. Overall, I did not notice any anomalies/irregularities beyond the transition of the timeout value from seconds to centiseconds.

```yaml

  tasks:

  - name: test_zos_operator_various_command
    ibm.ibm_zos_core.zos_operator:
      cmd: "{{ item }}"
    register: result
    loop:
      - "d a"
      - "k s"
      - "d r,l"
      - "d parmlib"
      - "SEND 'list ready',NOW"
  - name: print result
    debug:
      var: result

  - name: test_zos_operator_invalid_command
    ibm.ibm_zos_core.zos_operator:
      cmd: "invalid command"
    register: result
  - name: print result
    debug:
      var: result

  - name: test_zos_operator_invalid_command_to_ensure_transparency
    ibm.ibm_zos_core.zos_operator:
      cmd: "DUMP COMM=('ERROR DUMP')"
    register: result
  - name: print result
    debug:
      var: result

  - name: test_zos_operator_positive_path
    ibm.ibm_zos_core.zos_operator:
      cmd: "d u,all"
    register: result
  - name: print result
    debug:
      var: result

  - name: test_zos_operator_positive_path_verbose
    ibm.ibm_zos_core.zos_operator:
      cmd: "d u,all"
      verbose: True
    register: result
  - name: print result
    debug:
      var: result

  - name: test_zos_operator_positive_verbose_with_full_delay
    ibm.ibm_zos_core.zos_operator:
      cmd: "RO *ALL,LOG 'dummy syslog message'"
      wait_time_s: 10
      verbose: True
    register: result
  - name: print result
    debug:
      var: result

  - name: test_zos_operator_positive_verbose_with_quick_delay
    ibm.ibm_zos_core.zos_operator:
      cmd: "d u,all"
      verbose: True
      wait_time_s: 10
    register: result
  - name: print result
    debug:
      var: result

  - name: test_zos_operator_positive_verbose_blocking
    ibm.ibm_zos_core.zos_operator:
      cmd: "d u,all"
      verbose: True
      wait_time_s: 5
    register: result
  - name: print result
    debug:
      var: result

  - name: test_response_come_back_complete
    ibm.ibm_zos_core.zos_operator:
      cmd: "\\$dspl"
    register: result
  - name: print result
    debug:
      var: result


```
