### ISSUE TITLE
[Bug] <zos_job_submit module - unexcepted failure when location is missing> 

### ISSUE THREAD

**Issue by vcorfmatibm** [ansible-collections/ibm_zos_core#1199]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.4

### IBM Enterprise Python

v3.10.x

### IBM z/OS Ansible core Version

v1.8.0-beta.1

### ansible-version

v2.15.x

### z/OS version

v2.4

### Ansible module

zos_job_submit

### Bug description

**First, I was unable to choose version v1.8.0 from the list of versions offered (the latest is v1.8.0-beta1 ...)**

When I execute zos_job_submit with PDS in src parameter and not location parameter, the module fails but it should not because normally, the default value for location parameter is "DATA_SET"

If I add location parameter valorised to "DATA_SET" it's ok

Example ko :  
```
- name: "[{{current_step_name}}]"
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"
  block:

    - name: "Job_submit"
      zos_job_submit:
        src: 'NAZARE.WDEPLOY.ANSIBLE.JCL(HELLO1)'
```

Example ok :
```
- name: "[{{current_step_name}}]"
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"
  block:

    - name: "Job_submit"
      zos_job_submit:
        src: 'NAZARE.WDEPLOY.ANSIBLE.JCL(HELLO1)'
        location: "DATA_SET"
```

### Playbook verbosity output.

```
The full traceback is:
Traceback (most recent call last):
  File "/home/vcorfmat/.local/lib/python3.10/site-packages/ansible/executor/task_executor.py", line 165, in run
    res = self._execute()
  File "/home/vcorfmat/.local/lib/python3.10/site-packages/ansible/executor/task_executor.py", line 660, in _execute
    result = self._handler.run(task_vars=vars_copy)
  File "/home/vcorfmat/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/action/zos_job_submit.py", line 55, in run
    if module_args["location"] == "LOCAL":
KeyError: 'location'
fatal: [zos_host_01]: FAILED! => {
    "msg": "Unexpected failure during module execution: 'location'",
    "stdout": ""
}
```

### Ansible configuration.

```YAML
#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2023. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
[defaults]
forks = 25
host_key_checking = False
#callbacks_enabled = ibm.ibm_zos_wazi_deploy.cb_aggregate_evidences
stdout_callback = ibm.ibm_zos_wazi_deploy.cb_evidences

[ssh_connection]
pipelining = True
#ssh_args = -o ControlMaster=auto -o ControlPersist=3600s -o PreferredAuthentications=publickey
```

### Contents of the inventory

```YAML
all:
  hosts:
    zos_host_01:
      ansible_host: x.x.x.x
      ansible_user: MYUSER
      ansible_ssh_port: 222
```

### Contents of `group_vars` or `host_vars`

```YAML
environment_vars: &environment_vars_defaults
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  #PYTHONPATH: "{{ ZOAU }}/lib"
  PYTHONSTDINENCODING: "cp1047" 
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:/lib"
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
```
