### ISSUE TITLE
[Enabler] [zos_job_submit] Remove `wait` from doc and deprecation notices

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1214]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_job_submit

### Enabler description

Module zos_job_submit has a deprecation that is approaching a year old, its time we remove it. 
```
 wait=dict(type="bool", required=False, default=False,
                  removed_at_date='2022-11-30',
                  removed_from_collection='ibm.ibm_zos_core')
```
and clean up the doc:
```
  wait:
    required: false
    default: false
    type: bool
    description:
      - Setting this option will yield no change, it is deprecated. There is no
        no need to set I(wait); setting I(wait_times_s) is the correct way to
        configure the amount of tme to wait for a job to execute.
      - Configuring wait used by the L(zos_job_submit,./zos_job_submit.html) module has been
        deprecated and will be removed in ibm.ibm_zos_core collection.
      - See option I(wait_time_s).
```
