### ISSUE TITLE
[Bug] [zos_lineinfile] When using digits shorthand `\d` the JSON response is not escaped and errors

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1234]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.5

### IBM Enterprise Python

v3.10.x

### IBM z/OS Ansible core Version

v1.8.0-beta.1

### ansible-version

latest

### z/OS version

v2.5

### Ansible module

zos_lineinfile

### Bug description

When using something like this regex (which is currently not working for other reasons than the escape) it will error. 
```
    - name: Remove all comments in the USS file
      zos_lineinfile:
        src: ANSIBLE.TEST.PDS(MEMBER2)
        state: absent
        regexp: '^(.*)Xms(\d+)m(.*)$'
        insertafter: '^#JAVA_OPTS'
        line: JAVA_OPTS="-Xms128m -Xmx1G -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true"
      register: result
      tags: task_6
```
or
```
    - name: Add a line to a member PDS is in use
      zos_lineinfile:
        src: ANSIBLE.TEST.PDS(MEMBER1)
        insertafter: EOF
        line: 'Forcing an update on a data set that is locked'
        force: True
      register: result
      tags: task_7
```
Fails with:
```
fatal: [zvm]: FAILED! => {"changed": false, "msg": "dsed return content is NOT in json format", "rc": 1, "stderr": "", "stderr_lines": [], "stdout": "{\"cmd\": \"dsedhelper -d -c IBM-1047 /^(.*)Xms(\\d+)m(.*)$/d ANSIBLE.TEST.PDS(MEMBER2) \", \"found\": 0, \"changed\": 0}", "stdout_lines": ["{\"cmd\": \"dsedhelper -d -c IBM-1047 /^(.*)Xms(\\d+)m(.*)$/d ANSIBLE.TEST.PDS(MEMBER2) \", \"found\": 0, \"changed\": 0}"]}
```

Looking closer it appears this can be addressed in ZOAU or in Ansible, for now the easy solution is to correct the escape in ansible by adding a line like this to this block:
```
 try:
        # change the return string to be loadable by json.loads()
        stdout = stdout.replace('/c\\', '/c\\\\')
        stdout = stdout.replace('/a\\', '/a\\\\')
        stdout = stdout.replace('/i\\', '/i\\\\')
        stdout = stdout.replace('$ a\\', '$ a\\\\')
        stdout = stdout.replace('1 i\\', '1 i\\\\')
        stdout = stdout.replace('/d', '\\\\d')
        if line:
            stdout = stdout.replace(line, quotedString(line))
```
While I don't know if the above is the best option, I am able to recreate this using the dependency which depicts the issue more clearly.

For this command:
```
dsed -d -f -c IBM-1047 '/^(.*)Xms(\d+)m(.*)$/d' "ANSIBLE.TEST.PDS(MEMBER2)"
```
I get:
```
{"cmd": "dsedhelper -d -f -c IBM-1047 /^(.*)Xms(\d+)m(.*)$/d ANSIBLE.TEST.PDS(MEMBER2) ", "found": 0, "changed": 0}
```
Passing the result above into `json.loads(...)` results in an error:
```
>>> import json
>>> json.loads(r'{"cmd": "dsedhelper -d -f -c IBM-1047 /^(.*)Xms(\d+)m(.*)$/d ANSIBLE.TEST.PDS(MEMBER2) ", "found": 0, "changed": 0}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 1 column 49 (char 48)
```

But if I escape `\d` with `\\d` in the response and put it back into json.loads(...), it succeeds:
```
>>> json.loads(r'{"cmd": "dsedhelper -d -f -c IBM-1047 /^(.*)Xms(\\d+)m(.*)$/d ANSIBLE.TEST.PDS(MEMBER2) ", "found": 0, "changed": 0}')
{'cmd': 'dsedhelper -d -f -c IBM-1047 /^(.*)Xms(\\d+)m(.*)$/d ANSIBLE.TEST.PDS(MEMBER2) ', 'found': 0, 'changed': 0}
```

Then looking closer at the [EMCA](https://ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf) spec, it appears maybe the optimal way to RECEIVE the JSON is with the added escape `\\d`:

![image](https://github.com/ansible-collections/ibm_zos_core/assets/25803172/77433783-1da3-42ed-9cfc-62630ff226c2)
