### ISSUE TITLE
[Bug] zos_copy truncating file during transfer

### ISSUE THREAD

**Issue by prevoyant1** [ansible-collections/ibm_zos_core#1259]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Description
While working with the `zos_copy` module when trying to submit a compilation JCL using a Jinja2 template to insert the PL/1 code instream, I noticed that the destination file is truncated. The file cuts off abruptly in the middle of the template where the variable is inserted. This results to a non functionnal JCL. 

I tried not using the template and the JCL worked perfectly. I also tried filling the template and saving it locally before sending and it was complete also. This just happens with the zos_copy.

Sorry if this is a dumb question, I am an intern who just learned about Ansible and z/OS about 2 weeks ago and I appreciate any help if the issue is on my end.

### Steps to Reproduce
1. Run the playbook
2. Wait for the zos_copy to happen
3. Check the dataset's content

### Expected Outcome
The destination file should contain the full template with the variables inserted in them.

### Actual Outcome
The destination file is truncated in the middle.

### Additional Information
IBM Z Open Automation Utilities
v1.2.5 (default)

IBM Enterprise Python
v3.11.x (default)

ansible-version
v2.14.x

### Jinja Template
```//{{ job_name | upper }} JOB (200,2088),MSGLEVEL=(1,1),NOTIFY=&SYSUID,CLASS=S,REGION=0M
//* ---------------------------------------------------------*//
//*  Exemple de compilation d'un programme PL/I - Version 1  *//
//* ---------------------------------------------------------*//
//*
//* Creation du PDSE
//PDSE      EXEC PGM=IEFBR14
//SYSPRINT  DD SYSOUT=*
//SYSIN     DD DSN=&&PDSELOAD,
//          DISP=(NEW,PASS),
//          DSNTYPE=LIBRARY,
//          SPACE=(TRK,(100,10,10),RLSE),
//          DCB=(RECFM=U,LRECL=0,BLKSIZE=19069)
//*
//* Compilation du programme
//COMPIL    EXEC PGM=IBMZPLI,PARM='@DD:OPTIONS'
//STEPLIB   DD DISP=SHR,DSN=EXO0.IBMPLIR.V61R1.SIBMZCMP
//SYSUEXIT  DD DUMMY
//OPTIONS   DD *
    OPTIMIZE(0)
/*
//SYSDEFSD  DD SYSOUT=*
//SYSPRINT  DD SYSOUT=*
//SYSUT1    DD SYSOUT=*
//SYSUT2    DD SYSOUT=*
//SYSUT3    DD SYSOUT=*
//SYSLIB    DD DUMMY
//SYSIN     DD *
{{ file_content | safe }}
/*
//SYSLIN    DD DSN=&&MOD,
//          DISP=(NEW,PASS),
//          SPACE=(TRK,(100,10),RLSE),
//          DCB=(RECFM=FB,LRECL=80,BLKSIZE=0)
//*
//* Linkedit
//LKED      EXEC PGM=IEWBLINK,
//          PARM='FETCHOPT=(PACK,PRIME),NORENT,REUS,STORENX=NEVER'
//SYSOUT    DD SYSOUT=*
//SYSPRINT  DD SYSOUT=*
//SYSTERM   DD SYSOUT=*
//SYSDEFSD  DD SYSOUT=*
//SYSUT1    DD SPACE=(CYL,(2,1)),UNIT=SYSDA
//SYSLIB    DD DISP=SHR,DSN=CEE.SCEELKED
//          DD DISP=SHR,DSN=ISP.SISPLOAD
//SYSLIN    DD DISP=(OLD,PASS),DSN=&&MOD
//SYSLMOD   DD DISP=SHR,DSN=&&PDSELOAD(HELLO)
//*
//* Execution du programme
//RUN       EXEC PGM=HELLO
//STEPLIB   DD DISP=SHR,DSN=&&PDSELOAD
//SYSPRINT  DD SYSOUT=*
```

### file_content variable
```
DCL NBI FIXED BIN(31) INIT(100);

PUT SKIP EDIT('bonjour ', NBI, ' FOIS BOUCLE EN FIXED BIN(31)')(A);
DO I = 1 TO NBI;
T = T + 1;
END;
PUT SKIP EDIT('RESULTAT:', T)(A);
END ZPE000;
```

### zos_copy task
```
- name: Copy the JCL to the USS directory
  zos_copy:
    src: "{{ role_path }}/templates/COMPILE.j2"
    dest: "{{ tgt_tmp_dir }}/ansible/jcl/{{ job_name }}"
    use_template: True
    force: True
  vars: 
    file_content: "{{ file_content }}"
  register: jcl_copy_result
```

### Output
```
//HELLO JOB (200,2088),MSGLEVEL=(1,1),NOTIFY=&SYSUID,CLASS=S,REGION=0M
//* ---------------------------------------------------------*//
//*  Exemple de compilation d'un programme PL/I - Version 1  *//
//* ---------------------------------------------------------*//
//*
//* Creation du PDSE
//PDSE      EXEC PGM=IEFBR14
//SYSPRINT  DD SYSOUT=*
//SYSIN     DD DSN=&&PDSELOAD,
//          DISP=(NEW,PASS),
//          DSNTYPE=LIBRARY,
//          SPACE=(TRK,(100,10,10),RLSE),
//          DCB=(RECFM=U,LRECL=0,BLKSIZE=19069)
//*
//* Compilation du programme
//COMPIL    EXEC PGM=IBMZPLI,PARM='@DD:OPTIONS'
//STEPLIB   DD DISP=SHR,DSN=EXO0.IBMPLIR.V61R1.SIBMZCMP
//SYSUEXIT  DD DUMMY
//OPTIONS   DD *
    OPTIMIZE(0)
/*
//SYSDEFSD  DD SYSOUT=*
//SYSPRINT  DD SYSOUT=*
//SYSUT1    DD SYSOUT=*
//SYSUT2    DD SYSOUT=*
//SYSUT3    DD SYSOUT=*
//SYSLIB    DD DUMMY
//SYSIN     DD *
ZPE000: PROC OPTIONS(MAIN);
DCL T FIXED BIN(31) INIT(0);
DCL I FIXED BIN(31) INIT(0);
DCL NBI FIXED BIN(31) INIT(100);

PUT SKIP EDIT('bonjour '

```

This is also my first Github issue so forgive me if I missed some information. Let me know if you need more.

### IBM z/OS Ansible core Version

v1.9.0-beta.1

### IBM Z Open Automation Utilities

v1.2.5 (default)

### IBM Enterprise Python

v3.11.x (default)

### ansible-version

v2.14.x

### z/OS version

v2.5 (default)

### Ansible module

zos_copy

**Comment by fernandofloresg** [comment]
Hey @prevoyant1 , I tried recreating the issue with the information you provided and was not reproducible.

Did your task failed or completed successfully? Could you also share your playbook output ? Should look something like this : 
```
PLAY [zvm] *********************************************************************

TASK [Copy the JCL to the USS directory] ***************************************
ok: [zvm]

PLAY RECAP *********************************************************************
zvm                        : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
If you add the following task we can get more detailed info : 

```
- name: print result
      debug:
        msg: "{{ jcl_copy_result }}"
```

And that output should look like this:
```
TASK [print result] ************************************************************
ok: [zvm] => {
    "msg": {
        "changed": false,
        "dest": "/tmp/ansible/jcl/test.jcl",
        "failed": false,
        "gid": 1,
        "group": "OMVSGRP",
        "is_binary": false,
        "mode": "0644",
        "owner": "BPXROOT",
        "size": 1671,
        "src": "./templates/COMPILE.j2",
        "state": "file",
        "uid": 0
    }
}

```

Even better, If you add `-vvv` option to the `ansible-playbook` command we can get more details on task execution, If it does not contain any confidential info please share that too.

In my execution resulting file is 1671 bytes, see how large is your resulting file either using ls or something else. Make sure you have enough space for a bigger file.

Also, could you share how the file_content variable content is assigned? 

PS. Welcome to the z/OS world and congrats on opening your first GH issue, you did great.

**Comment by prevoyant1** [comment]
Yes of course, sorry I don't know why I didn't include that in the first place.

## Execution result 
It looks like the size is pretty similar. Also, when I put the content of file_content directly in the template (without using the template so), the file is copied correctly. So I feel like the problem is caused by the templating itself.
```
changed: [giwd] => changed=true
  dest: /tmp/ansible/jcl/HELLO
  gid: 0
  group: ROOTGRP
  invocation:
    module_args:
      dest: /tmp/ansible/jcl/HELLO
      force: true
      src: /home/lsyloi/ansible-nrb/roles/jcl_setup/templates/COMPILE.j2
      use_template: true
  is_binary: false
  mode: '0644'
  owner: XXX
  size: 1839
  src: /home/lsyloi/ansible-nrb/roles/jcl_setup/templates/COMPILE.j2
  state: file
  uid: 64583
```

## How the file_content variable content is assigned
I personnly don't think this is the problem because when I debug the variable it prints the correct output.
```
- name: Read the content from the file
  set_fact: 
    file_content: "{{ lookup('file', file_path) }}"
```

**Comment by prevoyant1** [comment]
After some more troubleshooting, I found out that the problem doesn't come from the transfer from the Ansible controller machine to the z/OS nor from the templating. I used the zos_fetch module to retrieve the JCL copied to the USS and the content is correct. 
The problem comes from the copy from USS to the PDS member. 

## Task
```
- name: Populate the PDS member with the JCL from USS
  zos_copy:
    src: "{{ tgt_tmp_dir }}/ansible/jcl/{{ job_name }}"
    dest: "{{ data_set_name }}({{ pds_member_name }})"
    force: True
    remote_src: True
  register: pds_member_population_result
```

## Output 
```
TASK [jcl_setup : Populate the PDS member with the JCL from USS] *******************************************************
changed: [giwd]

TASK [jcl_setup : Display the result of populating PDS member with the JCL] ********************************************
ok: [giwd] =>
  msg: |-
    PDS member population result:
    changed: true
    dest: XXX(MEM1)
    dest_created: true
    destination_attributes:
        block_size: 32760
        record_format: FB
        record_length: 1028
        space_primary: 3
        space_secondary: 1
        space_type: K
        type: PO
    failed: false
    is_binary: false
    src: path/to/HELLO
```
