### ISSUE TITLE
[Bug][zos_data_set] Attempt to create a data set of the same name on a different volume does not work nor does it report a failure

### ISSUE THREAD

**Issue by ketankelkar** [ansible-collections/ibm_zos_core#1269]
### Is there an existing issue for this?

- [x] There are no existing issues.

### Bug description

There _may_ be a use case for creating data sets of the same name on multiple volumes. The playbook tasks for that may look something like:
```yaml
- name: create data set on some volume
    ibm.ibm_zos_core.zos_data_set:
        name: "{{ DEFAULT_DATA_SET_NAME }}"
        state: present
        volume: "00000"

- name: create data set on a different volume
    ibm.ibm_zos_core.zos_data_set:
        name: "{{ DEFAULT_DATA_SET_NAME }}"
        state: present
        volume: "222222"
```

Currently, the result of the above is:
```bash
TASK [create data set on some volume] ******************************************
Thursday 29 February 2024  16:22:35 -0800 (0:00:00.007)       0:00:00.007 ***** 
changed: [zvm]

TASK [create data set on different volume] ********************************
Thursday 29 February 2024  16:23:15 -0800 (0:00:39.561)       0:00:39.569 ***** 
ok: [zvm]

PLAY RECAP *******************************
zvm                        : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
Where the playbook was reported to have "succeeded" BUT the data set on the `different` volume `222222` is NOT created. To me, the end-state of the system does not match with the state described in the 2nd task, which to me is "ensure a data set by some specified name is present on the specified volume".

I would expect one of two things:
1. module failure on the second task with some message about how the data set was found in catalog on a different volume than specified in the task and perhaps the user would attempt to un-catalog the data set first.
2. module success with `changed=True` where under the covers, the first data set was uncataloged, the new data set was created on the specified other volume. From here I see two options:
   1.  leave the latest data set in catalog
   2. un-catalog the latest data set and re-catalog the initial -- this would leave the system in the same state it started in.

### IBM z/OS Ansible core Version

v1.10.0-beta.1

### IBM Z Open Automation Utilities

v1.2.5 (default)

### IBM Enterprise Python

v3.11.x (default)

### ansible-version

v2.15.x

### z/OS version

v2.5 (default)

### Ansible module

zos_data_set

### Playbook verbosity output.

```
TASK [create data set on some volume] ************************************************************************************************************************************************************************************************
task path: /Users/ketan/dev/playbooks/130poo.yml:37
Thursday 29 February 2024  16:30:30 -0800 (0:00:00.008)       0:00:00.008 ***** 
Using module file /Users/ketan/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_data_set.py
Pipelining is enabled.
<ec01148a.vmec.svl.ibm.com> ESTABLISH SSH CONNECTION FOR USER: omvsadm
<ec01148a.vmec.svl.ibm.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="omvsadm"' -o ConnectTimeout=10 -o 'ControlPath="/Users/ketan/.ansible/cp/956b2fabb5"' ec01148a.vmec.svl.ibm.com '/bin/sh -c '"'"'_BPXK_AUTOCVT=ON _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' _TAG_REDIR_ERR=txt _TAG_REDIR_IN=txt _TAG_REDIR_OUT=txt LANG=C ZOAU_HOME=/zoau/v1.3.0 ZOAU=/zoau/v1.3.0/bin ZOAU_ROOT=/zoau/v1.3.0 LIBPATH=/zoau/v1.3.0/lib/:/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz/lib:/lib:/usr/lib:. ZOAUTIL_DIR=/zoau/v1.3.0 PYTHONPATH=/zoau/v1.3.0/lib/3.10/ PYTHON_HOME=/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz PYTHON=/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz/bin PATH=/zoau/v1.3.0/bin:/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz/bin:/bin:/usr/sbin:/var/bin:/usr/lpp/java/java180/J8.0_64/bin PYTHONSTDINENCODING=cp1047 /allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz/bin/python3 && sleep 0'"'"''
<ec01148a.vmec.svl.ibm.com> (0, b'\n{"changed": false, "message": "", "names": ["KETAN.PRIVATE.TESTDS"], "invocation": {"module_args": {"name": "KETAN.PRIVATE.TESTDS", "state": "present", "volume": "000000", "volumes": "000000", "type": "PDS", "space_type": "M", "space_primary": 5, "space_secondary": 3, "record_format": "FB", "replace": false, "force": false, "batch": null, "sms_management_class": null, "sms_storage_class": null, "sms_data_class": null, "block_size": null, "directory_blocks": null, "record_length": null, "key_offset": null, "key_length": null, "tmp_hlq": null}}}\n', b'')
ok: [zvm] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "batch": null,
            "block_size": null,
            "directory_blocks": null,
            "force": false,
            "key_length": null,
            "key_offset": null,
            "name": "KETAN.PRIVATE.TESTDS",
            "record_format": "FB",
            "record_length": null,
            "replace": false,
            "sms_data_class": null,
            "sms_management_class": null,
            "sms_storage_class": null,
            "space_primary": 5,
            "space_secondary": 3,
            "space_type": "M",
            "state": "present",
            "tmp_hlq": null,
            "type": "PDS",
            "volume": "000000",
            "volumes": "000000"
        }
    },
    "message": "",
    "names": [
        "KETAN.PRIVATE.TESTDS"
    ]
}

TASK [create data set on different volume] *******************************************************************************************************************************************************************************************
task path: /Users/ketan/dev/playbooks/130poo.yml:43
Thursday 29 February 2024  16:30:39 -0800 (0:00:09.658)       0:00:09.666 ***** 
Using module file /Users/ketan/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_data_set.py
Pipelining is enabled.
<ec01148a.vmec.svl.ibm.com> ESTABLISH SSH CONNECTION FOR USER: omvsadm
<ec01148a.vmec.svl.ibm.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="omvsadm"' -o ConnectTimeout=10 -o 'ControlPath="/Users/ketan/.ansible/cp/956b2fabb5"' ec01148a.vmec.svl.ibm.com '/bin/sh -c '"'"'_BPXK_AUTOCVT=ON _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' _TAG_REDIR_ERR=txt _TAG_REDIR_IN=txt _TAG_REDIR_OUT=txt LANG=C ZOAU_HOME=/zoau/v1.3.0 ZOAU=/zoau/v1.3.0/bin ZOAU_ROOT=/zoau/v1.3.0 LIBPATH=/zoau/v1.3.0/lib/:/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz/lib:/lib:/usr/lib:. ZOAUTIL_DIR=/zoau/v1.3.0 PYTHONPATH=/zoau/v1.3.0/lib/3.10/ PYTHON_HOME=/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz PYTHON=/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz/bin PATH=/zoau/v1.3.0/bin:/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz/bin:/bin:/usr/sbin:/var/bin:/usr/lpp/java/java180/J8.0_64/bin PYTHONSTDINENCODING=cp1047 /allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz/bin/python3 && sleep 0'"'"''
<ec01148a.vmec.svl.ibm.com> (0, b'\n{"changed": false, "message": "", "names": ["KETAN.PRIVATE.TESTDS"], "invocation": {"module_args": {"name": "KETAN.PRIVATE.TESTDS", "state": "present", "volume": "222222", "volumes": "222222", "type": "PDS", "space_type": "M", "space_primary": 5, "space_secondary": 3, "record_format": "FB", "replace": false, "force": false, "batch": null, "sms_management_class": null, "sms_storage_class": null, "sms_data_class": null, "block_size": null, "directory_blocks": null, "record_length": null, "key_offset": null, "key_length": null, "tmp_hlq": null}}}\n', b'')
ok: [zvm] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "batch": null,
            "block_size": null,
            "directory_blocks": null,
            "force": false,
            "key_length": null,
            "key_offset": null,
            "name": "KETAN.PRIVATE.TESTDS",
            "record_format": "FB",
            "record_length": null,
            "replace": false,
            "sms_data_class": null,
            "sms_management_class": null,
            "sms_storage_class": null,
            "space_primary": 5,
            "space_secondary": 3,
            "space_type": "M",
            "state": "present",
            "tmp_hlq": null,
            "type": "PDS",
            "volume": "222222",
            "volumes": "222222"
        }
    },
    "message": "",
    "names": [
        "KETAN.PRIVATE.TESTDS"
    ]
}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************
zvm                        : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

Thursday 29 February 2024  16:30:42 -0800 (0:00:02.299)       0:00:11.966 ***** 
```

### Ansible configuration.

```YAML
(ansible-2.15)% ansible-config view
[defaults]
forks = 25
callbacks_enabled = profile_tasks

# remote_tmp = /u/ansible/tmp
# remote_port = 22
# debug = True
# verbosity = 1

[ssh_connection]
pipelining = True
```
```


### Contents of the inventory

_No response_

### Contents of `group_vars` or `host_vars`

```YAML
environment:
    _BPXK_AUTOCVT: "ON"
    _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
    _TAG_REDIR_ERR: "txt"
    _TAG_REDIR_IN: "txt"
    _TAG_REDIR_OUT: "txt"
    LANG: "C"
    ZOAU_HOME: "/zoau/v1.3.0"
    ZOAU: "/zoau/v1.3.0/bin"
    ZOAU_ROOT: "/zoau/v1.3.0"
    LIBPATH: "/zoau/v1.3.0/lib/:/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz/lib:/lib:/usr/lib:."
    ZOAUTIL_DIR: "/zoau/v1.3.0"
    PYTHONPATH: "/zoau/v1.3.0/lib/3.10/"
    PYTHON_HOME: "/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz"
    PYTHON: "/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz/bin"
    PATH: "/zoau/v1.3.0/bin:/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz/bin:/bin:/usr/sbin:/var/bin:/usr/lpp/java/java180/J8.0_64/bin"
    PYTHONSTDINENCODING: "cp1047"
```
