### ISSUE TITLE
[Bug] When executing the zos_tso_command module, I am getting some giberish back and the play fails

### ISSUE THREAD

**Issue by ehrocha** [ansible-collections/ibm_zos_core#1291]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Bug description

When executing the following play, I am getting odd errors:
```
---
- name: Issue TSO Command
  hosts: zdtZos
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  tasks:
    - name: Get list of allocated datasets
      environment: "{{ environment_vars }}"
      zos_tso_command:
        commands: lista
      register: vlista
```
This is the error, please see the giberish returned in content.
```
fatal: [s0w1_demo-zdt01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": "lista",
            "max_rc": 0
        }
    },
    "max_rc": 0,
    "msg": "Some (True) command(s) failed:\nCommand \"lista\" executionfailed.  RC was 16.",
    "output": [
        {
            "command": "lista",
            "content": [
                "?@ŧ?@?@?\u0015"
            ],
            "failed": true,
            "lines": 1,
            "rc": 16,
            "stderr": ""
        }
    ]
}
```

### IBM z/OS Ansible core Version

v1.8.0 (default)

### IBM Z Open Automation Utilities

v1.2.4

### IBM Enterprise Python

v3.11.x (default)

### ansible-version

v2.16.x (default)

### z/OS version

v2.5 (default)

### Ansible module

zos_tso_command

### Playbook verbosity output.

1163289 1710015769.95467: getting the next task for host s0w1_demo-zdt01
1163289 1710015769.95471: host s0w1_demo-zdt01 is done iterating, returning
fatal: [s0w1_demo-zdt01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": "lista",
            "max_rc": 0
        }
    },
    "max_rc": 0,
    "msg": "Some (True) command(s) failed:\nCommand \"lista\" executionfailed.  RC was 16.",
    "output": [
        {
            "command": "lista",
            "content": [
                "?@ŧ?@?@?\u0015"
            ],
            "failed": true,
            "lines": 1,
            "rc": 16,
            "stderr": ""
        }
    ]
}

### Ansible configuration.

```YAML
[defaults]
inventory = ./inventory
log_path = ./logs/ansible.log
interpreter_python = auto
host_key_checking = False
forks=25
[ssh_connection]
pipelining = True
ssh_args = -C -o ControlMaster=no -o ControlPersist=60s -o ConnectTimeout=10 -o StrictHostKeyChecking=no
transfer_method = scp
scp_extra_args="-O"
```

### Contents of `group_vars` or `host_vars`

```YAML
environment_vars:
 _BPXK_AUTOCVT: ON
 _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
 _TAG_REDIR_ERR: "txt"
 _TAG_REDIR_IN: "txt"
 _TAG_REDIR_OUT: "txt"
 ZOAU_HOME: '/usr/lpp/IBM/zoautil'
 PYTHONPATH: '/usr/lpp/IBM/zoautil/lib'
 PYTHONSTDINENCODING: "cp1047"
 LIBPATH: '/usr/lpp/IBM/zoautil/lib:/usr/lpp/IBM/cyp/pyz/lib:/usr/lib:/lib:.'
 PATH: '/bin:/usr/bin:/usr/sbin:/usr/lpp/IBM/zoautil/bin:/usr/lpp/IBM/cyp/pyz/bin/python3'
 LANG: "C"
```
