### ISSUE TITLE
[Bug] [1.10.0] [zos_blockinfile] Work-Around to fix false negative when 'block' parameter contains a double quote (")

### ISSUE THREAD

**Issue by ketankelkar** [ansible-collections/ibm_zos_core#1301]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Bug description

Reminder to review/revise the doc changes made in #1284 so they are up to date with whatever changes this bugfix implements. 

Related issues:
- #1258 

The above is a tracker for the fix going into ZOAU. This will be the issue that provides the work-around until the dependency in the above issue is completed.

This behavior is a known issue stemming from ZOAU v1.3.0 `dmod`/`dsed`, specifically the JSON parser. 
This is worth changing because currently, the module *changes* the `src` and then reports a `failed` module. 
This is an issue of data integrity. 

Futhermore, we do not know if only the double quote (") character is affected or there are others too. It could potentially be all the characters which are treated as special in the JSON RFC.

playbook task:
```yml
- name: blockinfile
  ibm.ibm_zos_core.zos_blockinfile:
    src: "some.data.set"
    block: JK"L
    insertafter: EOF 
```

result(s):

The playbook task is reported as `failed=True` and `changed=False`.
```sh
TASK [blockinfile] *****************************************************************************************************************************************************************************************************************************************************************
fatal: [zvm]: FAILED! => {"changed": false, "msg": "ZOAU dmod return content is NOT in json format", "rc": 8, "stderr": "BGYSC5309E Failed to insert new entry.\nBGYSC5306E Failed to parse JSON text into array.\nBGYSC4820E Failed to process JSON output.\n", "stderr_lines": ["BGYSC5309E Failed to insert new entry.", "BGYSC5306E Failed to parse JSON text into array.", "BGYSC4820E Failed to process JSON output."], "stdout": "", "stdout_lines": []}
```
But, ssh-ing in and dumping the data set shows the changes were made.
before:
```sh
bash-4.3$ dcat 'some.data.set'
"ABC"
"DEF"
"GHI"
```
after:
```sh
bash-4.3$ dcat 'some.data.set'
"ABC"                                                                           
"DEF"                                                                           
"GHI"                                                                           
# BEGIN ANSIBLE MANAGED BLOCK                                                   
JK"L                                                                            
# END ANSIBLE MANAGED BLOCK 
```
I see several options worth exploring as a temporary work-around until the underlying issue is fixed.

The preferred:
Disable the JSON flag during the call to the ZOAU functionalities (`datasets.blockinfile`)and then capture/parse the stdout/stderr. This should be possible via the ZOAU python interfaces and is preferable, but if not, `run_command` command can be used to call `dmod`/`dsed` directly. 

Since we do not know which characters work and which don't, it may be advisable to revert to the non-JSON for all calls to `blockinfile` rather than limiting the work-around code to only those where the `block` param contains double quotes.

Less preferable:
Detect the presence of double quote (and potentially other 'forbidden' chars) and fail the module with an informative message. 
This option limits usability and is therefore less preferable. Further, we do not know which characters work and which ones do not.

Least preferable:
Capture the exception, inspect the file to verify the changes ...
This would be a ton of work, expensive both for development as well as per task. 

### IBM z/OS Ansible core Version

v1.10.0-beta.1

### IBM Z Open Automation Utilities

v1.3.0

### IBM Enterprise Python

v3.11.x (default)

### ansible-version

v2.16.x (default)

### z/OS version

v2.5 (default)

### Ansible module

zos_blockinfile

### Playbook:
```yml
    - name: create data set
      ibm.ibm_zos_core.zos_data_set:
        name: "some.data.set"
        type: SEQ
        space_primary: 10
        space_type: M
        replace: yes

    - name: write to some data set
      ibm.ibm_zos_core.zos_copy:
        content: |
          ABC
          DEF
          GHI
        dest: "some.data.set"
        force: yes

    - name: add string with double quote to end of file
      ibm.ibm_zos_core.zos_blockinfile:
        src: "some.data.set"
        block: 'JK"L'
        insertafter: EOF

```
