### ISSUE TITLE
[Enabler] [zos_data_set] Batch mode allows certain non-nested parameters as valid syntax.

### ISSUE THREAD

**Issue by ketankelkar** [ansible-collections/ibm_zos_core#1302]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

When the module is called with the `batch` parameter, there are a number of parameters which are allowed as per the Ansible parser rules and therefore "valid syntax" BUT wind up being ignored by the code logic which handles the batch-ed tasks. 

See [this comment](https://github.com/ansible-collections/ibm_zos_core/pull/1285#discussion_r1523672009) for my initial findings.

For example, the following playbook task is valid syntax:
```yml
- name: create data set
  ibm.ibm_zos_core.zos_data_set:
    record_format: FBA
    batch:
      - name: "some.data.set.one"
        type: SEQ
        state: present
        record_format: VB
      - name: "some.data.set.two"
        type: SEQ
        state: present
        record_format: VB
```
Where the initial `record_format: FBA` is ignored by module logic. I think this creates an ambiguity where a user may attempt to define the parameter at the top (outside of `batch`) and assume that the option would apply to the nested items -- which it will NOT.

For the task below, a user could potentially be surprised to see that their data sets were defined in `record_format: FB` rather than `FBA` as they "specified" because the option was not specified within the batch task. The default value was used and the resulting data set was created with record format `FB`. 
```yml
- name: create data set
  ibm.ibm_zos_core.zos_data_set:
    record_format: FBA
    batch:
      - name: "some.data.set.one"
        type: SEQ
        state: present
      - name: "some.data.set.two"
        type: SEQ
        state: present
```

The following parameters also behave in a similar manner.
- state
- space_type
- space_primary
- space_secondary
- record_format
- replace
- force

See list of mutually exclusive parameters as defined in the src [here.](https://github.com/ansible-collections/ibm_zos_core/blob/ce2551abd7724701e557be0af583f2de92ff5047/plugins/modules/zos_data_set.py#L1179)

My understanding is that this behavior stems from using "choices", which are used to restrict which values can be specified in the parameters. 

It would be preferable to keep the current behavior rather than removing the use of choices. 
The ideal would be to find a way to keep the choices intact and have the `batch` parameter be mutually exclusive with the rest of the module options. 

More extensive playbook task:
```yml
- name: create data set
  ibm.ibm_zos_core.zos_data_set:
    state: absent
    space_type: TRK
    space_primary: 100
    space_secondary: 100
    record_format: FBA
    replace: no
    force: no
    batch:
      - name: "some.data.set.one"
        type: SEQ
        state: present
        space_type: TRK
        space_primary: 50
        space_secondary: 50
        record_format: VBA
        replace: yes
      - name: "some.data.set.two"
        type: SEQ
        state: present
        space_type: TRK
        space_primary: 50
        space_secondary: 50
        record_format: VB
        replace: yes
```
![image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/809aca9d-402b-42b4-8338-0be950957649)
![image](https://github.com/ansible-collections/ibm_zos_core/assets/10567394/39c03f3a-99f3-4746-b8ba-af2b8d772e62)

### Ansible module

zos_data_set
