### ISSUE TITLE
[Documentation] Address zos_ping.rst:56: WARNING: undefined label: ansible.builtin.ssh_module

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1330]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Documentation issue description

In the latest ping module where ssh is mentioned because of the use of scp with openSsh 9 or later, this error was shown:
````
/Users/ddimatos/git/gh/ibm_zos_core/docs/source/modules/zos_ping.rst:56: WARNING: undefined label: ansible.builtin.ssh_module (if the link has no caption the label must precede a section header) solved when the doc tooling is updated
```
While this does not prevent doc from generating , the module will not be able to link outside its current collection (ibm_zos_core). 

There are alternatives to link to modules outisde of the collection but not available today because of doc gen currently uses a frozen version of ansible and some dependencies because of a bug reported some time back that has recently been resolved. 

The issue is in place to address this error once the doc dependencies are updated. This happens in the `seealso` section but if you look at the latest version there are other options now beyond module(...) that we can use to solve this. 

```
seealso:

# Reference by module name
- module: cisco.aci.aci_tenant

# Reference by module name, including description
- module: cisco.aci.aci_tenant
  description: ACI module to create tenants on a Cisco ACI fabric.

# Reference by plugin name
- plugin: ansible.builtin.file
  plugin_type: lookup

# Reference by plugin name, including description
- plugin: ansible.builtin.file
  plugin_type: lookup
  description: You can use the ansible.builtin.file lookup to read files on the control node.

# Reference by rST documentation anchor
- ref: aci_guide
  description: Detailed information on how to manage your ACI infrastructure using Ansible.

# Reference by rST documentation anchor (with custom title)
- ref: The official Ansible ACI guide <aci_guide>
  description: Detailed information on how to manage your ACI infrastructure using Ansible.

# Reference by Internet resource
- name: APIC Management Information Model reference
  description: Complete reference of the APIC object model.
  link: https://developer.cisco.com/docs/apic-mim-ref/
```

See documentation link: https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html

### IBM z/OS Ansible core Version

v1.9.0

### Ansible module

_No response_
