### ISSUE TITLE
[Enabler] [zos_encode] GDG/GDS and special character support

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1372]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

New MVSDataset class
-----------------------

There is a new MVSDataset class introduced in #1386 that represents a data set, when used, as part of initialization it escapes and resolves the gds relative name if any.

This is a sample on how to initialize the new class, many of these params can just be None.

```python
MVSDataSet(
            name = params.get("name"),
            record_format = params.get("record_format", None),
            volumes = params.get("volumes", None),
            data_set_type = params.get("type", None),
            block_size = params.get("block_size", None),
            record_length = params.get("record_length", None),
            space_primary = params.get("space_primary", None),
            space_secondary = params.get("space_secondary", None),
            space_type = params.get("space_type", None),
            directory_blocks = params.get("directory_blocks", None),
            key_length = params.get("key_length", None),
            key_offset = params.get("key_offset", None),
            sms_storage_class = params.get("sms_storage_class", None),
            sms_data_class = params.get("sms_data_class", None),
            sms_management_class = params.get("sms_management_class", None),
        )
```

GDG/GDS Support
-------------------

Option `src`, `dest` and `backup_name` accept a data set name or path, enabler is to support GDS relative names.

```yaml
- name: Convert file encoding from a sequential data set to another
    sequential data set
  zos_encode:
    src: ZOAUSER.GDG(0)
    dest: USER.TEST1.PS
    encoding:
      from: IBM-1047
      to: ISO8859-1

- name: Convert file encoding from a sequential data set to another
    sequential data set
  zos_encode:
    src: USER.TEST1.PS
    dest: ZOAUSER.GDG(0)
    encoding:
      from: IBM-1047
      to: ISO8859-1

- name: Convert file encoding from a sequential data set to another
    sequential data set
  zos_encode:
    src: USER.TEST1.PS
    dest: USER.TEST2.PS
    encoding:
      from: IBM-1047
      to: ISO8859-1
    backup: True
    backup_name: BACKUP.GDG(+1)
```

Using a new generation of the GDG as a dest or backup will create that new version and copy into that data set, since each GDS can be sequential or PDS/E new generation will depend on the source type.

Internally, in the case of a data set name being a GDS relative name we should resolve those names into absolute GDS names when the generation number is 0 or negative.

Following functions will be implemented in #1386 
```python
# Sample of soon to be implemented gdg function
if DataSet.is_gds_relative_name(name):
    src = DataSet.resolve_gds_absolute_name(src)
```

Symbols support
-----------------
 
Changes done to the BetterArgParser should be adopted in the module to not break and use the correct escaped name in case of the data set name having a symbol in it.

data set name with symbol

`ZOAUSER.TE$T`

That way, the modules will have to retrieve the new escaped named and the original user provided name inside the dictionary like:

```python
name = DataSet.escape_data_set_name(name)
```
Escaping special characters could be done via a new function inside the BetterArgParser.
These are some of the special characters:
- \#
- @
- $
- \-

For this task completion we need:
- [x] Do the development work
- [x] Update the docs to talk about GDG and GDS handling in the module.
- [x] Update the docs with at least 1 example on how to use with GDSs.
- [x] Create a new test case for GDSs.
- [x] Create a new test case for symbols.

### Ansible module

zos_encode
