### ISSUE TITLE
[Enabler] [zos_unarchive] Special character support

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1381]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description
Symbols support
-----------------

Data set names in `src` option can contain different permitted symbols, goal is to add support into the module.

Changes done to the BetterArgParser should be adopted in the module to not break and use the correct escaped name in case of the data set name having a symbol in it.

```
- name: Unarchive a terse data set and excluding data sets from unpacking.
  zos_unarchive:
    src: ZOAUSER.TE$T
    format:
      name: terse
```

For this task completion we need:
- [ ] Do the development work
- [ ] Create a new test case for symbols.

That way, the modules will have to retrieve the new escaped named and the original user provided name inside the dictionary like:

```python
name = DataSet.escape_data_set_name(name)
```

### Ansible module

zos_unarchive
