### ISSUE TITLE
[Bug] {zos_job_submit] TypeError: submit() takes from 1 to 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by gngrossi** [ansible-collections/ibm_zos_core#1465]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Bug description

Trying to use Python 3.12.1 on z/OS 2.5.  Python 3.11.5 works.

### IBM z/OS Ansible core Version

v1.9.0

### IBM Z Open Automation Utilities

v1.2.5 (default)

### IBM Enterprise Python

v3.12.x

### ansible-version

v2.16.x (default)

### z/OS version

v2.5 (default)

### Ansible module

zos_job_submit

### Playbook verbosity output.

bash-4.4$ ansible-playbook submit.yml

PLAY [MA1] *************************************************************************************************************************

TASK [Submit a job] ****************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: submit() takes from 1 to 2 positional arguments but 3 were given
fatal: [mvs-sysd]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 107, in <module>\n  File \"<stdin>\", line 99, in _ansiballz_main\n  File \"<stdin>\", line 47, in invoke_module\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_ibm.ibm_zos_core.zos_job_submit_payload_781lrow0/ansible_ibm.ibm_zos_core.zos_job_submit_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_submit.py\", line 1108, in <module>\n  File \"/tmp/ansible_ibm.ibm_zos_core.zos_job_submit_payload_781lrow0/ansible_ibm.ibm_zos_core.zos_job_submit_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_submit.py\", line 1104, in main\n  File \"/tmp/ansible_ibm.ibm_zos_core.zos_job_submit_payload_781lrow0/ansible_ibm.ibm_zos_core.zos_job_submit_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_submit.py\", line 921, in run_module\n  File \"/tmp/ansible_ibm.ibm_zos_core.zos_job_submit_payload_781lrow0/ansible_ibm.ibm_zos_core.zos_job_submit_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_job_submit.py\", line 707, in submit_src_jcl\nTypeError: submit() takes from 1 to 2 positional arguments but 3 were given\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *************************************************************************************************************************
mvs-sysd        : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

### Ansible configuration.

```YAML
bash-4.4$ ansible-config view
[defaults]
forks = 25
inventory = ~/playbooks/inventory.yml
host_key_checking = false
remote_port = 2222
timeout = 15
#deprecation_warnings=false

[ssh_connection]
pipelining = true
```

### Contents of the inventory

```YAML
#
# Hosts
#
MA1:
  hosts:
    mvs-sysd:
  vars:
    ansible_user: "@02858"
#
```

### Contents of `group_vars` or `host_vars`

```YAML
#
ZOAU_HOME:        /hewitt/zopentools/zoau1258
#ZOAU_HOME:        /hewitt/zopentools/zoau1310
#PYZ_HOME:         /hewitt/zopentools/python311/usr/lpp/IBM/cyp/v3r11/pyz
PYZ_HOME:         /hewitt/zopentools/python312/usr/lpp/IBM/cyp/v3r12/pyz

ansible_python_interpreter: "{{PYZ_HOME}}/bin/python3"

environment_vars:
  LIBPATH:        "{{ZOAU_HOME}}/lib:{{PYZ_HOME}}/lib:/lib:/usr/lib:."
  PATH:           "{{ZOAU_HOME}}/bin:{{PYZ_HOME}}/bin:/bin:/usr/sbin:."

  PYTHONSTDINENCODING: cp1047

# not compatible with pip installing the zoau package
# PYTHONPATH:     "{{ZOAU_HOME}}/lib"

# works without it
# LANG: C

  _BPXK_AUTOCVT:  ON
  _CEE_RUNOPTS:   "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_IN:  txt
  _TAG_REDIR_OUT: txt
  _TAG_REDIR_ERR: txt
#
```
