### ISSUE TITLE
[Documentation] [zos_operator] Include instructions to the user to escape # and $ characters for JES2 commands.

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1471]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Documentation issue description

Related to issue #1444 

Currently users that need to execute a JES2 command using `zos_operator` have to escape the `$` symbol, we do provide an example in the docs but need to be more specific by instructing users when to escape those symbols.

Documentation in the short term, where the docs might instruct users to escape command prefixes, eg $, # and the doc include some updated samples. One might be to show and example of how to figure out the command prefix the system is using and possibly mention this in documentation as well.
For example, this command D OPDATA,PREFIX (short version I believe is D O) yields:

Current example in the docs is :

```yaml
- name: Execute an operator command to purge all job logs (requires escaping)
  zos_operator:
    cmd: "\\$PJ(*)"

```

### IBM z/OS Ansible core Version

v1.9.0

### Ansible module

zos_operator
