### ISSUE TITLE
[Bug] [zos_job_submit] Incompatibility with ZOAU V1.2.2 and Below

### ISSUE THREAD

**Issue by connor-sunlife** [ansible-collections/ibm_zos_core#1522]
### Is there an existing issue for this?

- [x] There are no existing issues.

### Bug description

When running zos_job_submit from ibm_zos_core v1.9 while ZOAU v1.2.2 is installed on the Mainframe the following error is given:
The JCL submitted with job id JOB26449 but there was an error, please review the error for further details: 'Job' object has no attribute 'program_name'

I believe this is an issue with #841 where the change is not able to handle v1.2.2 and lower. This causes the if statement fall through the the elif where program_name is mandatory. This is at line 252 of plugins/module_utils/job.py at the time of this change.

I don't see anywhere in these [release notes](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/release_notes.html) that specify that ZOAU v1.2.2 is specifically not supported for ibm_zos_core v1.9 though maybe that is the case.

This can be recreated by submitting any JCL with ibm.ibm_zos_core.zos_job_submit while ZOAU v1.2.2 is installed on the target Mainframe.

Example playbook:
```
---
- hosts: tst1
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - name: Submit JCL in a PDSE member
      ibm.ibm_zos_core.zos_job_submit:
        src: MP68.SAMPLE(TEST)
        location: DATA_SET
      register: result
```

### IBM z/OS Ansible core Version

v1.9.0 (default)

### IBM Z Open Automation Utilities

v1.2.2

### IBM Enterprise Python

v3.11.x (default)

### ansible-version

v2.14.x

### z/OS version

v2.5 (default)

### Ansible module

zos_job_submit

### Playbook verbosity output.

I produced this but I don't think it is needed at this time.

### Ansible configuration.

```YAML
[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o PreferredAuthentications=publickey

[galaxy]
server_list = published_repo, rh_certified_repo, community_repo
```

### Contents of the inventory

```YAML
tst1:
  hosts:
    mvstcpz.ca.sunlife:
```

### Contents of `group_vars` or `host_vars`

```YAML
#--------------------------------#
#   TST1 Connection Variables    #
#--------------------------------#

PYZ: "/usr/lpp/cyp/v3r11/pyz"
ZOAU: "/usr/lpp/IBM/zoautil"
JAVA: "current_31/"

environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  PYTHONPATH: "{{ PYZ }}/lib"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin:/usr/lpp/java/{{ JAVA }}/bin:/usr/sbin:"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
  PYTHONSTDINENCODING: "cp1047"

ansible_python_lib: /usr/lpp/hzc/lib
ansible_python_interpreter: "{{ PYZ }}/bin/python3"
ansible_pipelining: true
```
