### ISSUE TITLE
[Enabler] [zos_tso_command] Explore options towards a solution for the UTF-8 warning for module zos_tso_command (and ansible.builtin.command/shell)

### ISSUE THREAD

**Issue by ketankelkar** [ansible-collections/ibm_zos_core#1533]
This item is a sub-task for:
- #987

I have identified  several tso commands and set up playbooks to replicate those use cases via `zos_tso_command`, `ansible.builtin.command` and `ansible.builtin.shell`.

The `ibm_zos_core` team has control over the code in the `zos_tso_command` module, so identifying its behaviors with regards to non-utf8 characters being sent to the Ansible controller can potentially be corrected. However, those tso commands can also be invoked via the built-in shell and command modules, and although the approach is not advised for tso commands (since the module exists), there are other commands which may have to go through those built-in modules. As such, it will be helpful to have an approach or potential mitigations for remediating non-utf8 chars coming into the Ansible controller from z/OS.

Currently passing tso commands are:
- time
- listuser
- lu {{ ansible_user }}
- send 'hi'

Currently failing (expected) tso commands are:
- lu food

On the POK systems, `lu ibmuser` returns mixed encoding. This does not seem to be the case on the ECs. This case has been identified and will be addressed outside of this item. This will be part of the general approach we take for remediating the non-utf8 chars. 

### Recreate Playbooks:
```yml

tasks:
- name: Set facts
  tags: always
  ansible.builtin.set_fact:
    weird_encoding_tsocommands:
      - "LU IBMUSER" # doesn't seem to break on EC
    tsocommands:
      - "time"
      - "listuser"
      - "LU {{ ansible_user | upper }}" # current user
      - "send 'hi'"
    tsocommands_with_error:
      - "LU FOOD" # non-existent user


- name: simple tso commands
  tags: a
  block:
  - name: simple tso commands
    zos_tso_command:
      commands: "{{ item }}"
    loop: "{{ tsocommands }}"

- name: simple tso commands which throw error (on purpose)
  tags: b
  block:
  - name: simple tso commands which throw error (on purpose)
    zos_tso_command:
      commands: "{{ item }}"
    loop: "{{ tsocommands_with_error }}"
    ignore_errors: yes

- name: tso command which brings back mostly utf8 with some non-utf8
  tags: c
  block:
  - name: tso command which brings back mostly utf8 with some non-utf8
    zos_tso_command:
      commands: "{{ item }}"
    loop: "{{ weird_encoding_tsocommands }}"
```
The above runs as expected even with builtin.command.

The below is the unexpected, mixed encoding case, replicated with `zos_tso_command`, `builtin.shell`, and `builtin.command`:
```yml
tasks:
- name: "list user profile (lu) for a different user than {{ ansible_user }}"
  tags: a, tsocmd, zos_tso_command
  block:
  - name: run lu with zos_tso_command
    ibm.ibm_zos_core.zos_tso_command:
      commands: "LU IBMUSER"

- name: "list user profile (lu) for a different user than {{ ansible_user }}"
  tags: b, tsocmd, command
  block:
  - name: run lu with builtin.command
    ansible.builtin.command: "tsocmd 'LU IBMUSER'"

- name: "list user profile (lu) for a different user than {{ ansible_user }}"
  tags: c, tsocmd, command
  block:
  - name: run lu with builtin.shell
    ansible.builtin.shell: "tsocmd 'LU IBMUSER'"

```
