### ISSUE TITLE
Wrong module name in the README

### ISSUE THREAD

**Issue by mtcohoon** [ansible-collections/ibm_zos_core#16]
##### SUMMARY

The README (https://github.com/ansible-collections/ibm_zos_core/blob/dev/README.md) has an error in the following code block:
```
- hosts: all
  collections:
   - ibm.ibm_zos_core
  tasks:
  - name: Query submitted job 'HELLO'
    zos_dataset:
       job_name: HELLO
```

Instead of `zos_dataset` the module should be `zos_job_query`.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

README.md

##### ANSIBLE VERSION

```
ansible 2.9.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/test/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]

```
