### ISSUE TITLE
zos_copy does not break records at right position

### ISSUE THREAD

**Issue by bmjunior** [ansible-collections/ibm_zos_core#161]
##### SUMMARY

zos_copy does not break records at end of line when trasmiting to sequential dataset on MF
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

zos_copy
##### ANSIBLE VERSION

```paste below
ansible 2.9.11
  config file = /home/bmjr/ansible/cirats/ansible.cfg
  configured module search path = ['/home/bmjr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/bmjr/ansible/cirats/ansible.cfg) = True
DEFAULT_FACT_PATH(/home/bmjr/ansible/cirats/ansible.cfg) = /home/bmjr/ansible/cirats/facts.d
DEFAULT_FORKS(/home/bmjr/ansible/cirats/ansible.cfg) = 25
DEFAULT_MANAGED_STR(/home/bmjr/ansible/cirats/ansible.cfg) = Ansible managed
DEFAULT_REMOTE_USER(/home/bmjr/ansible/cirats/ansible.cfg) = br11920
DEFAULT_TIMEOUT(/home/bmjr/ansible/cirats/ansible.cfg) = 60

```

##### OS / ENVIRONMENT

target system id zOS v 2.3

##### STEPS TO REPRODUCE

copy any file from redhat linux to a sequential dataset onMF

```yaml
    - name: Allocate remote sequential dataset
      zos_data_set:
        name: '{{ds_holdcard }}'
        type: SEQ
        space_primary: 2
        space_type: TRK
        record_format: FB
        record_length: 80
        block_size: 6080
        replace: yes

    - name: Send local holdcard file to remote sequential dataset
      zos_copy:
        src: "{{ playbook_dir }}/files/holdcard_#{{ hld }}.txt"
        dest: '{{ds_holdcard }}'
        encoding:
          from: ISO8859-1
          to: IBM-1047
```

##### EXPECTED RESULTS

records loaded like that:
++HOLD(HDBCC10) FMID(HDBCC10) FIXCAT CATEGORY (SIA-MVS-2019.12-30 ) 
 REASON(PH01725) RESOLVER(UI66853) CLASS(MDB2C10)                   
 .                                                                  
++HOLD(HQX77B0) FMID(HQX77B0) FIXCAT CATEGORY (SIA-MVS-2019.12-31 ) 
 REASON(PH14870) RESOLVER(UI66837) CLASS(MZOS230)                   
 .                                                                  
++HOLD(HQX77C0) FMID(HQX77C0) FIXCAT CATEGORY (SIA-MVS-2019.12-31 ) 
 REASON(PH14870) RESOLVER(UI66838) CLASS(MZOS240)                   
 .                                                                  
++HOLD(HQX77A0) FMID(HQX77A0) FIXCAT CATEGORY (SIA-MVS-2019.12-31 ) 
 REASON(PH14870) RESOLVER(UI66839) CLASS(MZOS220)                   
 .                                                                  

##### ACTUAL RESULTS

++HOLD(HDBCC10) FMID(HDBCC10) FIXCAT CATEGORY (SIA-MVS-2019.12-30 ). REASON(PH01
725) RESOLVER(UI66853) CLASS(MDB2C10). ..++HOLD(HQX77B0) FMID(HQX77B0) FIXCAT CA
TEGORY (SIA-MVS-2019.12-31 ). REASON(PH14870) RESOLVER(UI66837) CLASS(MZOS230). 
..++HOLD(HQX77C0) FMID(HQX77C0) FIXCAT CATEGORY (SIA-MVS-2019.12-31 ). REASON(PH
14870) RESOLVER(UI66838) CLASS(MZOS240). ..++HOLD(HQX77A0) FMID(HQX77A0) FIXCAT 
CATEGORY (SIA-MVS-2019.12-31 ). REASON(PH14870) RESOLVER(UI66839) CLASS(MZOS220)
. ..++HOLD(HMK1500) FMID(HMK1500) FIXCAT CATEGORY (SIA-MVS-2019.12-32 ). REASON(

```paste below
bmjr:cirats$ ansible-playbook -i hosts_cirats_inventory.yml -l sysprogs send_holdcard.yaml 

PLAY [send_holdcard] ***************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************
ok: [meue4.vipa.uk.ibm.com]

TASK [Allocate remote sequential dataset] ******************************************************************************************
changed: [meue4.vipa.uk.ibm.com]

TASK [Send local holdcard file to remote sequential dataset] ***********************************************************************
ok: [meue4.vipa.uk.ibm.com]

PLAY RECAP *************************************************************************************************************************
meue4.vipa.uk.ibm.com      : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
![Screenshot from 2020-08-13 16-42-40](https://user-images.githubusercontent.com/62013108/90179643-25557300-dd84-11ea-9616-366ca11a16ca.png)
![Screenshot from 2020-08-13 16-42-28](https://user-images.githubusercontent.com/62013108/90179648-2686a000-dd84-11ea-8ded-e209ae3e7066.png)
