### ISSUE TITLE
[Documentation] [modules] They document the use of TMPHLQ yet have the tmp_hlq option. 

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1675]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Documentation issue description

There are several modules that offer the `tmp_hlq` option which uses a HLQ for temporary data sets while Ansible and ZOAU perform operations and then clean up the temporary data sets. 

The doc will vary as some of the modules like `zos_backup_restore` during a PR had been updated to:
```
      - The default is the original HLQ of the data sets.
        If that is not available, then the value of C(TMPHLQ) is used.
```
while other [modules](https://github.com/search?q=repo%3Aansible-collections%2Fibm_zos_core+C%28TMPHLQ%29&type=code) have similar doc:
```
- The default HLQ is the Ansible user used to execute the module and if
 that is not available, then the value C(TMPHLQ) is used.
```

I believe why we see the mention of C(TMPHLQ) was before we updated the code to allow each module to set the `tmp_hlq` this was our only solution but to use TMPHLQ, you have to add it to the exported environment vars like (`TMPHLQ: "MYHLQ"`):
```
 environment:
    _BPXK_AUTOCVT: "ON"
    ZOAU_HOME: "{{ ZOAU }}"
    PYTHONPATH: "{{ ZOAU }}/lib"
    LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
    PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin"
    _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
    _TAG_REDIR_ERR: "txt"
    _TAG_REDIR_IN: "txt"
    _TAG_REDIR_OUT: "txt"
    LANG: "C"
    TMPHLQ: "MYHLQ"
```
The problem with this is that it ends up being per playbook, once the environment vars are passed over, all tasks is bound to it, unless you set environment vars per task. 

So the first issue is that we don't document how to use it in Ansible, (not implying we should)

The modules in question are:
```
- zos_volume_init.py
- zos_mount.py
- zos_fetch.py
- zos_unarchive.py
- zos_encode.py
- zos_archive.py
- zos_apf.py
- zos_mvs_raw.py
- zos_copy.py
- zos_lineinfile.py
- zos_data_set.py
- zos_blockinfile.py
- zos_backup_restore.py
```

### IBM z/OS Ansible core Version

v1.9.0 (default)
