### ISSUE TITLE
[Bug]Zos_blockinfile_not use marker_begin and end

### ISSUE THREAD

**Issue by AndreMarcel99** [ansible-collections/ibm_zos_core#1678]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Bug description

When using a new marker_begin and marker_end in insert when removing the new markers are no passing to the absent case.
So these case will fail.
```
    - name: Remove text from Scripts
      zos_blockinfile:
        marker_begin: "NEW BEGIN"
        marker_end: "NEW END"
        marker: "* {mark} ANSIBLE MANAGED BLOCK"
        src: "{{ tmp_ds }}"
        state: absent
      ignore_errors: True

```

### IBM z/OS Ansible core Version

v1.11.0

### IBM Z Open Automation Utilities

v1.2.5 (default)

### IBM Enterprise Python

v3.11.x (default)

### ansible-version

v2.16.x (default)

### z/OS version

v2.5 (default)
