### ISSUE TITLE
[Enabler] Enable replace all in zos lineinfile

### ISSUE THREAD

**Issue by AndreMarcel99** [ansible-collections/ibm_zos_core#1685]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

```
- name: Ensure value of a variable in the sequential data set
  zos_lineinfile:
    src: SOME.DATA.SET
    state: present 
    regexp: '^VAR='
    line: VAR="some value"
```
Will only replace the last found not all cases, users ask for that option

### Ansible module

zos_lineinfile
