### ISSUE TITLE
[Documentation] [zos_archive] Example is focused on GDG and terse yet really does not align to a terse example.

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#1731]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Documentation issue description

Compare this terse example to others, it does not seem to really have meant to be a terse example.
```
- name: Archive multiple data sets into a new GDS
  zos_archive:
    src: "USER.ARCHIVE.*"
    dest: "USER.GDG(+1)"
    format:
      name: terse
      format_options:
        use_adrdssu: True
```

Others that align to terse.
```
- name: Archive multiple GDSs into a terse
  zos_archive:
    src:
      - "USER.GDG(0)"
      - "USER.GDG(-1)"
      - "USER.GDG(-2)"
    dest: "USER.ARCHIVE.RESULT.TRS"
    format:
      name: terse
      format_options:
        use_adrdssu: True
```

### IBM z/OS Ansible core Version

v1.9.0 (default)
