### ISSUE TITLE
[Enhancement] Enhance error message when failing to import ZOAU

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1765]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enhancement or feature description

Recently I tried importing 1.2.5 using the development branch and running the following playbook.  Error message will be thrown :

```
fatal: [zvm]: FAILED! => {"changed": false, "message": "", "msg": "TypeError('catching classes that do not inherit from BaseException is not allowed')", "names": ["USER.WHAT.EVER"]}
```

I would expect to have error message : 
```python
"ZOAU is not properly configured for Ansible. Unable to import zoautil_py. "
"Ensure environment variables are properly configured in Ansible for use with ZOAU. "
"Complete traceback: {0}".format(self.traceback)
```

```yaml
- hosts : zvm
  collections :
    - ibm.ibm_zos_core
  gather_facts: False
  vars:
    ZOAU: "/zoau/v1.2.5"
    # ZOAU: "/zoau/v1.3.3"
    PYZ: "/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz"
    RC_0_DATA_SET_NAME: "USER.WHAT.EVER.ONE"
    DATA_SET_TO_LISTCAT: "USER.WHAT.EVER"
    IDCAMS_STDIN: " LISTCAT NTRIES('{{ DATA_SET_TO_LISTCAT | upper }}')"
    # " LISTCAT ENTRIES('OMVSADM.TEST')"

  environment: "{{ environment_vars }}"
  tasks:

    - name: create some data set
      block:
        - name: create data set to LISTCAT
          zos_data_set:
            name: "{{ DATA_SET_TO_LISTCAT }}"
            type: seq
            state: present
            replace: yes

        - name: mvs raw with verbose with rc=0
          zos_mvs_raw:
            verbose: True
            program_name: idcams
            auth: True
            dds:
              - dd_data_set:
                  dd_name: SYSPRINT
                  data_set_name: "{{ RC_0_DATA_SET_NAME }}"
                  disposition: new
                  type: seq
                  return_content:
                    type: text
              - dd_input:
                  dd_name: SYSIN
                  content: "{{ IDCAMS_STDIN }}"
          register: output_rc_0
          ignore_errors: True

        - name: print output
          debug:
            msg:
              - "{{ output_rc_0 }}"

        - name: mvs raw with verbose with rc=0
          zos_mvs_raw:
            verbose: False
            program_name: idcams
            auth: True
            dds:
              - dd_data_set:
                  dd_name: SYSPRINT
                  data_set_name: "{{ RC_0_DATA_SET_NAME }}"
                  disposition: old
                  type: seq
              - dd_input:
                  dd_name: SYSIN
                  content: "{{ IDCAMS_STDIN }}"
          register: output_rc_0

        - name: print output
          debug:
            msg:
              - "{{ output_rc_0 }}"

      always:
        - name: delete data sets
          zos_data_set:
            name: "{{ item }}"
            state: absent
          loop:
            - "{{ DATA_SET_TO_LISTCAT }}"
            - "{{ RC_0_DATA_SET_NAME }}"
```

This is the playbook I was running, to reproduce this error simply use the latest collection version from dev and execute this.

### Ansible module

zos_mvs_raw
