### ISSUE TITLE
[Bug] [zos_mvs_raw] Not returning correct return code (RC) when the module fails

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1779]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Bug description

When running a task with `zos_mvs_raw` and having it fail, it will return a wrong return code, usually 8.

```yaml

- hosts : zvm
  collections :
    - ibm.ibm_zos_core
  gather_facts: False
  vars:
    ZOAU: "/zoau/v1.3.3"
    PYZ: "/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz"
    RC_0_DATA_SET_NAME: "USER.WHAT.EVER.ONE"
    DATA_SET_TO_LISTCAT: "USER.WHAT.EVER"
    IDCAMS_STDIN: " LISTCAT NTRIES('{{ DATA_SET_TO_LISTCAT | upper }}')"

  environment: "{{ environment_vars }}"
  tasks:

    - name: create some data set
      block:
        - name: create data set to LISTCAT
          zos_data_set:
            name: "{{ DATA_SET_TO_LISTCAT }}"
            type: seq
            state: present
            replace: yes

        - name: mvs raw with verbose with rc=0
          zos_mvs_raw:
            verbose: True
            program_name: idcams
            auth: False
            dds:
              - dd_data_set:
                  dd_name: SYSPRINT
                  data_set_name: "{{ RC_0_DATA_SET_NAME }}"
                  disposition: new
                  type: seq
                  return_content:
                    type: text
              - dd_input:
                  dd_name: SYSIN
                  content: "{{ IDCAMS_STDIN }}"
          register: output_rc_0

        - name: print output
          debug:
            msg:
              - "{{ output_rc_0 }}"
      always:
        - name: delete data sets
          zos_data_set:
            name: "{{ item }}"
            state: absent
          loop:
            - "{{ DATA_SET_TO_LISTCAT }}"
            - "{{ RC_0_DATA_SET_NAME }}"

```

When running this playbook you would get error code 8 instead of 36.  This needs to be fixed in 1.12.0-beta.1 and dev branch.

### IBM z/OS Ansible core Version

v1.12.0-beta.1

### IBM Z Open Automation Utilities

v1.3.3

### IBM Enterprise Python

v3.11.x (default)

### ansible-version

v2.16.x (default)

### z/OS version

v2.5 (default)

### Ansible module

zos_mvs_raw
