### ISSUE TITLE
[Bug][zos_operator] Running a command in list fails with command invalid

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1817]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Bug description

Running the following sample in a list fails 

```yaml
    - name: Check VSAM allocation
      ibm.ibm_zos_core.zos_operator:
        cmd:
          - "D GRS,RES=(SYSDSN,''CICSUSER.LP01CIC1.EXMPCAT'')" 
      ignore_errors: true
      register: eqResult
```

With the following error :

```yaml
fatal: [zceeZosLpar]: FAILED! => {"changed": false, "msg": "An unexpected error occurred: [ZOAUResponse]\n\trc: 1\n\treponse_format: UTF-8\n\tstdout_response: \n\tstderr_response: \n\tcommand: opercmd -T 100 -w -- \"[\"D GRS,RES=(SYSDSN,'CICSUSER.LP01CIC1.EXMPCAT'')\"] \""}
```

But executing it as a string works ok
```yaml
    - name: Check VSAM allocation
      ibm.ibm_zos_core.zos_operator:
        cmd: "D GRS,RES=(SYSDSN,CICSUSER.LP01CIC1.EXMPCAT)"
      ignore_errors: true
      register: eqResult
```

Can check more in thread : /archives/CSLEJ8VGV/p1732740813664929

### IBM z/OS Ansible core Version

v1.11.0

### IBM Z Open Automation Utilities

v1.3.1

### IBM Enterprise Python

v3.11.x

### ansible-version

v2.14.x

### z/OS version

v2.5
