### ISSUE TITLE
Inconsistent case requirements for different modules when addressing z/OS datasets

### ISSUE THREAD

**Issue by bl0x** [ansible-collections/ibm_zos_core#195]
##### SUMMARY

Some modules require upper case input for z/OS datasets, others don't.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Examples:
zos_copy: requires uppercase input
zos_job_submit: accepts also mixed case

##### ANSIBLE VERSION

```paste below
ansible 2.9.11
  config file = /root/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/root/ansible.cfg) = True
DEFAULT_FORKS(/root/ansible.cfg) = 25
DEFAULT_HOST_LIST(/root/ansible.cfg) = ['/root/inventory']
HOST_KEY_CHECKING(/root/ansible.cfg) = False
RETRY_FILES_ENABLED(/root/ansible.cfg) = False
```

##### OS / ENVIRONMENT

z/OS, OS/390

##### STEPS TO REPRODUCE

```yaml
- name: Does not work
  zos_copy:
    remote_src: true
    src: MTM2020.PUBLIC.INPUT(MERGECMD)
    dest: "z00000.input(mergecmd)"          # Lowercase is *not* translated here

- name: Works
  zos_copy:
    remote_src: true
    src: MTM2020.PUBLIC.INPUT(MERGECMD)
    dest: "Z00000.INPUT(MERGECMD)"

- name: Also works
  zos_job_submit:
    src: "z00000.JcL(sOmEjOb)"     # Lowercase is translated here
    location: DATA_SET

```

##### EXPECTED RESULTS

Either the src/dest values for z/OS datasets should be upper-cased for all modules, or for none.

##### ACTUAL RESULTS

The modules, that don't translate the input paths to uppercase fail, if the user supplies lowercase or mixed-case values.

```paste below
failed: [192.86.32.153] (item=NAMES2) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "dest": "z00454.input(NAMES2)",
            "remote_src": true,
            "src": "MTM2020.PUBLIC.INPUT(NAMES2)"
        }
    },
    "item": "NAMES2",
    "msg": "Failure during execution of mvscmd; Return code: 12; stdout: 1IDCAMS  SYSTEM SERVICES                                           TIME: 16:18:44        09/22/20     PAGE      1\n0        \n   LISTCAT ENT(.00454......) ALL\n0IDC3203I ITEM '.00454......' DOES NOT ADHERE TO RESTRICTIONS\n0IDC3202I ABOVE TEXT BYPASSED UNTIL NEXT COMMAND. CONDITION CODE IS 12\n0        \n0IDC0002I IDCAMS PROCESSING COMPLETE. MAXIMUM CONDITION CODE WAS 12\n; stderr: ",
    "rc": null,
    "stderr": null,
    "stderr_lines": null,
    "stdout": null,
    "stdout_lines": null
}
```
