### ISSUE TITLE
[Bug] [zos_copy] Faulty behavior when copying members with aliases.

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#1951]
### Is there an existing issue for this?

- [x] There are no existing issues.

### Bug description

It was reported in slack channel /archives/CSLEJ8VGV/p1740076490147359 that copying from a load lib that contains members with both aliases and without aliases into a destination load lib has both members with aliases and without aliases resulted in `zos_copy` only copying the members that do not have aliases unless `aliases=true` is specified.

Which should not happen, because we are using `executable=true` and from the documentation: 

```
If the src executable has an alias, the alias information is also copied.
```

So that statement is not true, but user reported that when using `aliases` all members are copied.

```yaml

    - name: Copying system link listed libraries - {{ inventory_hostname }}
      zos_copy:
        src: "PM001.TEST940.SCSQSNLE(*)"
        dest: "PM001.TEST94X.SCSQSNLE"
        remote_src: true
        force: true
        executable: true
        aliases: true
        tmp_hlq:  PM001
      register: result_zos_copy
```

### IBM z/OS Ansible core Version

v1.12.0

### IBM Z Open Automation Utilities

v1.3.2

### IBM Enterprise Python

v3.11.x

### ansible-version

v2.15.x

### z/OS version

v2.5

### Ansible configuration.

```YAML

```

### Contents of the inventory

```YAML

```

### Contents of `group_vars` or `host_vars`

```YAML

```
