### ISSUE TITLE
[Bug] [zos_mvs_raw] Module fails for z/OS programs that need access to columns 1 and 2.

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#2071]
### Is there an existing issue for this?

- [x] There are no existing issues.

### Bug description

In pull request [1470](https://github.com/ansible-collections/ibm_zos_core/pull/1470) , it was decided that the module would validate that line lengths were less than 80 chars long with the inclusion of columns 1 and 2 being empty to ensure that line length is the same LRECL as temporary data sets used by the module. 

While the line length check with padding is fine, its that the module forces lines that start in column 1 and occupy columns 2 to be empty and shifts the line by 2, this is evident in the code [here](https://github.com/ansible-collections/ibm_zos_core/blob/2e70099b059fcdfbd3104ba316e8edca18ae7a09/plugins/modules/zos_mvs_raw.py#L2339).

In our use case, IEBUPDTE requires access to columns 1 and 2 and fail, running in an older version of the module where this change did not appear ran successfully. [Here is the doc and its example](https://www.ibm.com/docs/en/zos/2.4.0?topic=examples-example-11-create-new-partitioned-data-set).

Maybe a different approach is to not automatically handle this or maybe if we continue to automatically handle columns 1 and 2 being empty, we consider an option to control that like there is in[ zos_blockinfile](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/modules/zos_blockinfile.html) , option `indentation`. 

The IMS team had this in their source that surfaced the issue.
```
- name: UPDATE
      zos_mvs_raw:
        program_name: IEBUPDTE
        parm: "NEW"
        dds:
          - dd_output:
              dd_name: SYSPRINT
              return_content:
                type: text
          - dd_data_set:
              dd_name: SYSUT1
              data_set_name: "{{ADDTL_SAMP_PROC_LIB}}"
              disposition: shr
          - dd_data_set:
              dd_name: SYSUT2
              data_set_name: "{{ADDTL_SAMP_PROC_LIB}}"
              disposition: shr
          - dd_input:
              dd_name: SYSIN
              content:
                - "./        ADD  NAME=CBLTDLI"
                - "  LIBRARY SDFSRESL(CBLTDLI)     DL/I LANG INTF"
                - "  LIBRARY SDFSRESL(DFHEI01)     HLPI LANG INTF"
                - "  LIBRARY SDFSRESL(DFHEI1)      HLPI LANG INTF"
                - "  ENTRY DLITCBL"
                - "./        ADD  NAME=PLITDLI"
                - "  LIBRARY SDFSRESL(PLITDLI)     PL/I LANG INTF"
                - "  LIBRARY SDFSRESL(DFHEI01)     HLPI LANG INTF"
                - "  LIBRARY SDFSRESL(DFHEI1)      HLPI LANG INTF"
                - "  ENTRY PLICALLA"
                - "./        ADD  NAME=DFSMREC"
                - "0,MODBLKSA,IMSACBA,FORMATA"
                - "./        ADD  NAME=REFCPY"
                - "          COPY INDD=REFOUT,OUTDD=REFOUT"
                - "./        ADD  NAME=DFSACBCP"
                - "          COPY INDD=IMSACB,OUTDD=IMSACB"
                - "./        ADD  NAME=FMTCPY"
                - "          COPY INDD=FORMAT,OUTDD=FORMAT"
      when: create_sample
```

### IBM z/OS Ansible core Version

v1.12.0-beta.1

### IBM Z Open Automation Utilities

v1.3.1

### IBM Enterprise Python

v3.11.x

### ansible-version

v2.14.x

### z/OS version

v2.5

### Ansible configuration.

```YAML

```

### Contents of the inventory

```YAML

```

### Contents of `group_vars` or `host_vars`

```YAML

```
