### ISSUE TITLE
Ansible zos_job_submit fails when trying to submit jcl from USS file

### ISSUE THREAD

**Issue by EdwardMcCarthy** [ansible-collections/ibm_zos_core#2078]
### Is there an existing issue for this?

- [x] There are no existing issues.

### Bug description

Trying to submit JCL job from file in Unix System Services ( USS ) fails with

BGYSC4006E Line exceeds maximum length of 80

Note zoau level is 1.3.5

./zoaversionhelper
2025/03/13 21:08:08 CUT v1.3.5.0 bcb459b6 7509 PH64192 1385 36baca08

### IBM z/OS Ansible core Version

v1.13.0

### IBM Z Open Automation Utilities

v1.3.4

### IBM Enterprise Python

v3.13.x

### ansible-version

v2.15.x

### z/OS version

v3.1

### Ansible module

zos_job_submit

### Playbook verbosity output.

[may-9-ansible-job-sub.txt](https://github.com/user-attachments/files/20113386/may-9-ansible-job-sub.txt)

This is JCL in the USS file

//IBMUSER JOB (999,ABC),'CDPz             ',CLASS=A,MSGCLASS=T,
// NOTIFY=&SYSUID,TIME=1440,REGION=0M
/*JOBPARM S=ZZZZ
//ALCINST  EXEC PGM=IEFBR14

my playbook

- hosts: zceeZosLpar

  collections:
    - ibm.ibm_zos_core
  collections:
    - ibm.ibm_zosmf
  environment: "{{ environment_vars }}"
  
  gather_facts: no

  tasks:

    - name: " submit JCL 1"
      ibm.ibm_zos_core.zos_job_submit:
        src: "/global/zDevOps/prodCode/ansibleTests/e-iefbr14.txt"
        location: uss
        wait_time_s: 300
      ignore_errors: true
      register: br14jResult

    - name: " submit JCL result"
      debug:
        msg: "{{br14jResult }}"

### Ansible configuration.

```YAML
[defaults]
forks = 25
callbacks_enabled = timer, profile_tasks, profile_roles
stdout_callback = community.general.diy
private_key_file = /etc/ansible/edmcar_id_rsa

[callback_profile_tasks]
sort_order = none
task_output_limit=400

[ssh_connection]
pipelining = True
```

### Contents of the inventory

```YAML
zsystem:
  hosts:
    zceeZosLpar:
      ansible_host: myz.ibm.com
      ansible_user: ibmuser
      ansible_python_interpreter: /usr/lpp/IBM/cyp/v3r13/pyz/bin/python3
      api_polling_retry_count: "12"
      api_polling_interval_seconds: "10"
```

### Contents of `group_vars` or `host_vars`

```YAML
ZOAU: "/usr/lpp/IBM/zoau/v1r3"
PYZ: "/usr/lpp/IBM/cyp/v3r13/pyz"
GIT: "/u/ibmuser/zDevOps/rocket"
JAVA: "/usr/lpp/java/J8.0_64"

environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  PYTHONPATH: "{{ PYZ }}:{{ ZOAU }}/lib/3.13"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:{{ GIT }}/bin:{{JAVA}}/bin:/var/bin:/usr/sbin:/bin"
  JAVA_HOME: "{{ JAVA }}"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
  PYTHONSTDINENCODING: "cp1047"
```

**Comment by rexemin** [comment]
@EdwardMcCarthy could you provide us with the encoding/tag information for the USS file you're trying to submit as a job?

**Comment by fernandofloresg** [comment]
Adding the playbook shared by edward: 

```yaml
    - name: idz zOSExplorer submit unpack JCL
      ibm.ibm_zos_core.zos_job_submit:
        src: /global/zDevOps/prodCode/idz17/src/IDz_Host_SMPE-17.0.0/HALG340/JADRH0J.readme.txt
        location: uss
        wait_time_s: 300
        encoding:
          from: ISO8859-1
          to: IBM-037
      register: zesResult
```
