### ISSUE TITLE
[Enhancement] [zos_unarchive] Add encoding support for the module

### ISSUE THREAD

**Issue by Rohitcodes28** [ansible-collections/ibm_zos_core#2082]
### Is there an existing issue for this?

- [x] There are no existing issues.

### Enhancement or feature description

The zos_unarchive module currently extracts archived data sets or USS files on z/OS but lacks support for character encoding conversion. This enhancement proposes adding optional encoding support, similar to what exists in the zos_copy and zos_archive modules.
The objective will be to support the encoding using the zos_encode module utility and be able to encode  the files in the  encoding user wants post unarchiving to the desired destination.  The expectation is that the files will be changed to new encoding and will be kept, we are not considering the backup of files and keeping initial un-archived files in this case. 

### 

User should be able to provide the encoding dictionary with `from` and `to` values.
```yaml
encoding:
    from: IBM-1047
    to: IBM-037
```

User should be able to provide a list of files/data sets/paths ( Analyze feasibility of providing patterns) to be able to skip encoding as those might be binary files:

```yaml
- name: Copy local tar file and unpack it on the managed z/OS node, then encode to IBM-037 only files that are not under binary_files folder.
  zos_unarchive:
    src: "./files/archive_folder_test.tar"
    format:
      name: tar
    encoding:
        from: IBM-1047
        to: IBM-037
    skip_encoding:
        - "binary_files/"
```

Here user should be able to specify a folder without providing the absolute path that it will be unpacked to, but rather its relative path as it is in the archive.

After a successful unarchive process, the module will go through all the unarchived items and start encoding them into the `to` values. If there is a failure when encoding, the module should not fail but continue with the next encoding file, however it will report which files were encoded after unarchiving:

```json
{
"encoded": [
    "/tmp/a.txt",
    "/tmp/b.txt"
],
"failed_on_encoding": [
    "/tmp/abc.txt"
],
"skipped_encoding": [
    "/tmp/binary_files/"
]
}
```

Here, return values should be the absolute path where the files resides on.

The behavior should be added to the docs explaining:
- What happens when a file encoding fails.
- Saying that this module won't create backup of any files.
- Stating that if we are unarchiving some files, and there is a conflict with a name of a file that already exists, that file won't be encoded.

### Ansible module

zos_unarchive
