### ISSUE TITLE
[Enhancement][zos_archive] Support adding a list of files to skip encoding

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#2090]
### Is there an existing issue for this?

- [x] There are no existing issues.

### Enhancement or feature description

Related to enhancement #1870, the goal is to add new option and new return values to `zos_archive`:

User should be able to provide a list of files/data sets/paths ( Analyze feasibility of providing patterns) to be able to skip encoding as those might be binary files:

```yaml
- name: Copy local tar file and unpack it on the managed z/OS node, then encode to IBM-037 only files that are not under binary_files folder.
  zos_archive:
    src: "./files/archive_folder_test.tar"
    format:
      name: tar
    encoding:
        from: IBM-1047
        to: IBM-037
    skip_encoding:
        - "u/usr001/binary_files/"
```

The module will go through all the archived items and start encoding them into the `to` values. If there is a failure when encoding, the module should not fail but continue with the next encoding file, however it will report which files were encoded before archiving:

```json
{
"encoded": [
    "a.txt",
    "b.txt"
],
"failed_on_encoding": [
    "abc.txt"
],
"skipped_encoding": [
    "binary_files/"
]
}
```

Here, return values should be the relative path where the files resides on the archive.

The behavior should be added to the docs explaining:
- What happens when a file encoding fails.
- Saying that this module won't create backup of any files.

### Ansible module

zos_archive
