### ISSUE TITLE
[Enabler] Regression test the removal of

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#2095]
### Is there an existing issue for this?

- [x] There are no existing issues.

### Enabler description

Typically we default to these environment vars, this issue is particularly speaking to the environment var `PYZ` below.

I believe our code is to a point we don't need `PYZ` defined any longer. I have done some minimal smoke testing and found it not necessary, the goal here is that we run full regression to validate my findings. This issue should compound over issue #2093 such that it includes regression testing without `_TAG_REDIR_*` env vars as well. 

Today we use this:
```
ZOAU: "/zoau/v1.3.4"
PYZ: "/allpython/3.11/usr/lpp/IBM/cyp/v3r11/pyz"

environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  PYTHONPATH: "{{ ZOAU }}/lib/3.11"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
  PYTHONSTDINENCODING: "cp1047"
```

Test with this:
```
ZOAU: "/zoau/v1.3.4"

environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  PYTHONPATH: "{{ ZOAU }}/lib/3.11"
  LIBPATH: "{{ ZOAU }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:/bin:/var/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  LANG: "C"
  PYTHONSTDINENCODING: "cp1047"
```
