### ISSUE TITLE
[Enhancement] Add function exists() to zos_stat

### ISSUE THREAD

**Issue by storfibm** [ansible-collections/ibm_zos_core#2112]
### Is there an existing issue for this?

- [x] There are no existing issues.

### Enhancement or feature description

Zos_stat was recently introduced but unlike the builtin Ansible module does not contain an exists() function. This should be added such that users can drive the following functionality.

```
tasks:
  - name: Check if a data set exists
    zos_stat:
      name: "MY.DATA.SET"
    register: dataset_status
  - name: Report if a data set exists
    ansible.builtin.debug:
      msg: "The data set exists"
    when: dataset_status.exists
```

**Requirements:**
-This should work for data sets, files, aggregates or GDGs
-Investigate if "defined" can also leverage this function, eg. "when: dataset_status is defined" operations
-Provide test cases
-Update documentation

### Ansible module

zos_stat
