### ISSUE TITLE
[Enhancement] Skip Encoding in Zos_unarchive

### ISSUE THREAD

**Issue by Rohitcodes28** [ansible-collections/ibm_zos_core#2121]
### Is there an existing issue for this?

- [x] There are no existing issues.

### Enhancement or feature description

To add  options to skip encoding in zos_unarchive.

User should be able to provide a list of files/data sets/paths ( Analyze feasibility of providing patterns) to be able to skip encoding as those might be binary files:

```
- name: Copy local tar file and unpack it on the managed z/OS node, then encode to IBM-037 only files that are not under binary_files folder.
  zos_unarchive:
    src: "./files/archive_folder_test.tar"
    format:
      name: tar
    encoding:
        from: IBM-1047
        to: IBM-037
    skip_encoding:
        - "binary_files/"
```

Here user should be able to specify a folder without providing the absolute path that it will be unpacked to, but rather its relative path as it is in the archive.

### Ansible module

zos_unarchive
