### ISSUE TITLE
Docs: Module template shows empty 'returned:' output item

### ISSUE THREAD

**Issue by andy-maier** [ansible-collections/ibm_zos_core#218]
##### SUMMARY

The "returned" field of return value properties is optional. However, if not specified in the return value docstring, the template still generates an empty "returned:" output text, which is confusing.

We would like to have the "returned:" output text omitted if no "returned" field is specified for a return value property.

I can bring a PR for this forward.

Note: We open this issue here because this repo has the master version of the module.rst.j2 file, across the IBM collections.

##### ISSUE TYPE
- Documentation Bug Report

##### COMPONENT NAME

* docs/templates/module.rst.j2

##### ANSIBLE VERSION

```paste below
N/A
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

We already fixed this in the [zhmc collection](https://github.com/zhmcclient/zhmc-ansible-modules) repo, so I'm describing the input:

```
RETURN = """
changed:
  description: bla
  returned: always
  type: bool
adapter:
  description: bla
  returned: success
  type: dict
  contains:
    name:
      description: bla
      type: str
      # no returned
```

##### EXPECTED RESULTS

We would like to have the "returned:" output text omitted if no "returned" field is specified for a return value property.

##### ACTUAL RESULTS

See above
