### ISSUE TITLE
Docs: Support for multiple samples in return values of module template

### ISSUE THREAD

**Issue by andy-maier** [ansible-collections/ibm_zos_core#224]
##### SUMMARY

The module.rst.j2 template from the zosmf collection has support for a list of samples in the return values. The zos_core version only supports a single sample.

It would be nice to add support for sample being a list of samples.

The approach chosen by zosmf is to have "sample" being a dict with keys "sample1", "sample2" etc., and the module template recognizes this by the presence of the "sample1" item.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

* docs/templates/module.rst.j2

##### ADDITIONAL INFORMATION

It would allow specifying multiple samples for a return property.

Example with a string typed property:

RETURN docstring:
```yaml
xyz:
    description: bla
    type: str
    sample:
        sample1: "text1"
        sample2: "text2"
```

Possible RST:
```yaml
xyz
  bla

  | **type**: str
  | **sample**:

      "text1"

      "text2"
```

Example with a complex typed property:

RETURN docstring:
```yaml
xyz:
    description: bla
    type: list
    elements: str
    sample:
        sample1:
          [ "text1", "text2" ]
        sample2:
          []
```

Possible RST:
```yaml
xyz
  bla

  | **type**: str
  | **sample**:

    .. code-block::

        [ "text1", "text2" ]

    .. code-block::

        []
```

Note that the zosmf template does not support complex types nicely because it puts them into the same code block. The RST output shown above distinguishes the cases of str/int and complex types consistent with how it is currently done with single samples.
