### ISSUE TITLE
[Bug] ansible.builtin.replace fails with file created with zos_encode

### ISSUE THREAD

**Issue by petelouis** [ansible-collections/ibm_zos_core#309]
##### SUMMARY

I have 2 identical ASCII files residing in USS on my z/OS system, containing the following text:

ababab

Or, in hex:

x'6162616261620A'

The first file, zostest3.linux, was created by doing a binary upload of a file from my Linux workstation to USS on my z/OS system.
The second file, zostest3.ascii, was created by running zos_encode against an EBCDIC text file I created on the z/OS system.
If I go into ISHELL and run file compare against these files, it tells me they're identical.

When I run ansible.builtin.replace against these 2 files, it works as expected with the first file, but not the second; with the second file, it appears that regexp never matches, so no replace is done.  See sample playbook below.

##### COMPONENT NAME

zos_encode

##### ANSIBLE VERSION

```
Ansible version output:
ansible 2.9.27
  config file = /home/plouis/ansible/ansible.cfg
  configured module search path = ['/home/plouis/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Aug 12 2021, 07:06:15) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]

```

##### SPECIFY ANSIBLE COLLECTION VERSION

ibm_zos_core version is 1.3.1

##### SPECIFY THE Z OPEN AUTOMATION UTILITIES VERSION

ZOAU version is 2021/03/26 15:44:32 CUT V1.1.1 

##### ENVIRONMENT

host system is z/OS 2.4, Ansible is running on my IBM-maintained RHEL 8 workstation

##### STEPS TO REPRODUCE

```yaml
  tasks:

    - name: convert format
      zos_encode:
        src: /tmp/cics/zostest3.ebcdic
        dest: /tmp/cics/zostest3.ascii
        from_encoding: IBM-1047
        to_encoding: ISO8859-1

    - name: Replace a
      ansible.builtin.replace:
        path: /tmp/cics/zostest3.linux            # works with this file
#        path: /tmp/cics/zostest3.ascii           # but not this one
        regexp: 'a'
        replace: "b"
        encoding: ISO8859-1
        backup: no
```

##### ACTUAL RESULTS

```
Playbook output:
```

#### Ansible.cfg

```
'ansible-config dump --only-changed' output:
```

#### Inventory

```
Inventory content:
```

#### Vars

```
'group_vars' or 'host_vars' content:
```
