### ISSUE TITLE
[Feature] [zos_job_query]More asterisk support for z/OS ansible modules 

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#323]
I have a playbook using zos_job_query to query jobname "CPY*RS*"

      zos_job_query:
        job_name: "CPY*RS*"

but it failed and report the following error:
Value of unknown type: <class 'RuntimeError'>, Failed to validate the job name: CPY*RS*\n

      zos_job_query:
        job_name: "CPY*"

Describe the solution you'd like:
It looks like only support asterisk * as the suffix of the jobname now.
It would be better to have more than 1 asterisk support and even other wildcard support.

**Comment by ddimatos** [comment]
This issue was transferred from [issue](https://github.com/IBM/z_ansible_collections_samples/issues/147) and opened by user https://github.com/cdlwhui.

**Comment by focabr** [comment]
Hi, 

i have the same problem here.

```yml
    - name: Lista todos as tasks do DB2
      zos_job_query:
        job_name: "D*MSTR"
      register: db2_query

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: Value of unknown type: <class 'RuntimeError'>, Failed to validate the job name: D*MSTR
```
