### ISSUE TITLE
[Bug][zos_encode] Encoding a VSAM into a USS file fails if record length is equal to max rec length

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#361]
##### SUMMARY

When using zos_encode where a src is a VSAM dataset with its records having the same length as the max record, into a USS file the encoding fails with error message : 

fatal: [zvm]: FAILED! => {"changed": false, "dest": "/tmp/encode_test_file", "gid": 1, "group": "OMVSGRP", "mode": "0644", "msg": "USSCmdExecError(\"Failed during execution of usscmd: mvscmdauth --pgm=idcams --sysprint=stdout --sysin=stdin, Return code: 8; stdout: 1IDCAMS  SYSTEM SERVICES                                           TIME: 10:51:18        07/29/22     PAGE      1\\n0        \\n   REPRO INDATASET(OMVSADM.FETCH.TEST.VS) -\\n     OUTDATASET(OMVSADM.P3886590.T0561922.C0000000) REPLACE\\n0IDC3302I  ACTION ERROR ON OMVSADM.P3886590.T0561922.C0000000\\n IDC3309I ** RECORD X'F0F0F0F140' NOT WRITTEN.  LENGTH INVALID\\n0IDC3302I  ACTION ERROR ON OMVSADM.P3886590.T0561922.C0000000\\n IDC3309I ** RECORD X'F0F0F0F2F1' NOT WRITTEN.  LENGTH INVALID\\n0IDC0005I NUMBER OF RECORDS PROCESSED WAS 0\\n0IDC0001I FUNCTION COMPLETED, HIGHEST CONDITION CODE WAS 8\\n0        \\n0IDC0002I IDCAMS PROCESSING COMPLETE. MAXIMUM CONDITION CODE WAS 8\\n; stderr: \")", "owner": "BPXROOT", "size": 458, "src": "OMVSADM.FETCH.TEST.VS", "state": "file", "uid": 0}

##### COMPONENT NAME
zos_encode

##### ANSIBLE VERSION
```
Ansible version output:

ansible [core 2.13.1]
  config file = None
  configured module search path = ['/Users/fernandoflores/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/fernandoflores/Library/Python/3.8/lib/python/site-packages/ansible
  ansible collection location = /Users/fernandoflores/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/fernandoflores/Library/Python/3.8/bin/ansible
  python version = 3.8.9 (default, Apr 13 2022, 08:48:07) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True
```

##### SPECIFY ANSIBLE COLLECTION VERSION
```
"version": "1.4.0-beta.1"
```

##### SPECIFY THE Z OPEN AUTOMATION UTILITIES VERSION
```
# zoaversion -b
2021/07/07 22:36:30 CUT V1.2.0
```

##### STEPS TO REPRODUCE

1. Create a VSAM with any record length (tested with 50). 
2. Using DITTO fill the dataset content.
3. Run zos_encode with below parameters.4. 
```yaml
- hosts : zvm
  collections : 
    - ibm.ibm_zos_core
  vars:
    ZOAU: "/zoau/v1.2.0"
    PYZ: "/python3/usr/lpp/IBM/cyp/v3r8/pyz"
    VSAM_DATA_SET: "OMVSADM.FETCH.TEST.VS"
  environment: "{{ environment_vars }}"
  tasks :   
    - name: Encode USS file to VSAM
      zos_encode:
        src: "{{ VSAM_DATA_SET }}"
        dest: '/tmp/encode_test_file'
        from_encoding: IBM-1047
        to_encoding: ISO8859-1
      register : result
    
    - name: "Response for encoding the USS to VSAM"
      debug:
        msg: "{{ result }}"
```

##### EXPECTED RESULTS
Should encode the VSAM into a USS file successfully.

##### ACTUAL RESULTS

```
Playbook output:

fernandoflores@Oscars-MacBook-Pro fetch-VSAM % ansible-playbook -i inventory.yml 9_test_encode.yml 
[WARNING]: Collection ibm.ibm_zos_core does not support Ansible version 2.13.1

PLAY [zvm] ***********************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [zvm]

TASK [Encode USS file to VSAM] ***************************************************************************************************************************************************
fatal: [zvm]: FAILED! => {"changed": false, "dest": "/tmp/encode_test_file", "gid": 1, "group": "OMVSGRP", "mode": "0644", "msg": "USSCmdExecError(\"Failed during execution of usscmd: mvscmdauth --pgm=idcams --sysprint=stdout --sysin=stdin, Return code: 8; stdout: 1IDCAMS  SYSTEM SERVICES                                           TIME: 10:51:18        07/29/22     PAGE      1\\n0        \\n   REPRO INDATASET(OMVSADM.FETCH.TEST.VS) -\\n     OUTDATASET(OMVSADM.P3886590.T0561922.C0000000) REPLACE\\n0IDC3302I  ACTION ERROR ON OMVSADM.P3886590.T0561922.C0000000\\n IDC3309I ** RECORD X'F0F0F0F140' NOT WRITTEN.  LENGTH INVALID\\n0IDC3302I  ACTION ERROR ON OMVSADM.P3886590.T0561922.C0000000\\n IDC3309I ** RECORD X'F0F0F0F2F1' NOT WRITTEN.  LENGTH INVALID\\n0IDC0005I NUMBER OF RECORDS PROCESSED WAS 0\\n0IDC0001I FUNCTION COMPLETED, HIGHEST CONDITION CODE WAS 8\\n0        \\n0IDC0002I IDCAMS PROCESSING COMPLETE. MAXIMUM CONDITION CODE WAS 8\\n; stderr: \")", "owner": "BPXROOT", "size": 458, "src": "OMVSADM.FETCH.TEST.VS", "state": "file", "uid": 0}

PLAY RECAP ***********************************************************************************************************************************************************************
zvm                        : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

#### Ansible.cfg

```
'ansible-config dump --only-changed' output:
```

#### Inventory

```
Inventory content:
```

#### Vars

```
'group_vars' or 'host_vars' content:
```
