### ISSUE TITLE
[Bug][zos_mvs_raw] Module zos_mvs_raw errors with content string

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#373]
##### SUMMARY

When using module `zos_mvs_raw` with program IDCAMS and inserting a large sting as `content` I get a ZOAU error. I don't know if the error is in the Ansible space or ZOAU space for now, we will assume Ansible and work our way down to ZOAU. 

Error:
```
fatal: [zvm]: FAILED! => {"backups": [], "changed": false, "dd_names": [], "msg": "DatasetWriteError('An error occurred during write of data set \"OMVSADM.P0332025.T0129321.C0000000\". RC=1. ')", "ret_code": {"code": 8}}
```

##### COMPONENT NAME

`zos_mvs_raw`

##### ANSIBLE VERSION

```
Ansible version output:
ansible [core 2.11.12]
  config file = /Users/ddimatos/git/github/playbooks/ansible.cfg
  configured module search path = ['/Users/ddimatos/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/modules']
  ansible python module location = /Users/ddimatos/ansible_versions/3_8_13/ansible-doc/lib/python3.8/site-packages/ansible
  ansible collection location = /Users/ddimatos/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/ddimatos/ansible_versions/3_8_13/ansible-doc/bin/ansible
  python version = 3.8.13 (default, Jun 14 2022, 23:29:22) [Clang 13.0.0 (clang-1300.0.27.3)]
  jinja version = 3.1.2
  libyaml = True
```

##### SPECIFY ANSIBLE COLLECTION VERSION

```
(ansible-doc) ddimatos:[ ~/git/github/playbooks ]cat ~/.ansible/collections/ansible_collections/ibm/ibm_zos_core/MANIFEST.json |grep -i version
  "version": "1.4.0-beta.1",
```

##### SPECIFY THE Z OPEN AUTOMATION UTILITIES VERSION

zoau version 1.1.1

##### ENVIRONMENT

z/OS 2.4
IBM Enterprise Python 3.8.2

##### STEPS TO REPRODUCE

This will work because the content is passed as an array of strings:
```yaml

---
- hosts: zvm
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  vars:
    DS_NAME: "IMSTESTL.IMS1.RECON2"
    DFS_DS_VOLUME1: "222222"
  environment: "{{ environment_vars }}"


  tasks:
    - name: show  response
      debug:
        msg: "{{ result }}"

    - name: Delete cluster 1
      zos_mvs_raw:
        program_name: idcams
        auth: yes
        dds:
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
          - dd_input:
              dd_name: sysin
              content:
                - "  DELETE IMSTESTL.IMS1.RECON3 CLUSTER -"
                - "            PURGE"
      register: result

    - name: show  response
      debug:
        msg: "{{ result }}"

    - name: Delete cluster 2
      zos_mvs_raw:
        program_name: idcams
        auth: yes
        dds:
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
          - dd_input:
              dd_name: sysin
              content:
                - "  DELETE IMSTESTL.IMS1.RECON2 CLUSTER -"
                - "            PURGE"
      register: result

    - name: show  response
      debug:
        msg: "{{ result }}"

    - name: Define cluster 1
      zos_mvs_raw:
        program_name: idcams
        auth: yes
        dds:
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
          - dd_input:
              dd_name: sysin
              content:
                - "  DEFINE CLUSTER -"
                - "            (NAME(IMSTESTL.IMS1.RECON3) -"
                - "            CYL(10 10)  -"
                - "            FREESPACE(20 20) -"
                - "            INDEXED -"
                - "            KEYS(32 0) -"
                - "            NOERASE -"
                - "            NONSPANNED -"
                - "            NOREUSE -"
                - "            SHAREOPTIONS(3 3) -"
                - "            SPEED -"
                - "            UNORDERED -"
                - "            RECORDSIZE(4086 32600) -"
                - "            VOLUMES(222222) -"
                - "            UNIQUE -"
                - "            )"
      register: result

    - name: show  response
      debug: 
        msg: "{{ result }}"

    - name: Define cluster 2
      zos_mvs_raw:
        program_name: idcams
        auth: yes
        dds:
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
          - dd_input:
              dd_name: sysin
              content:
                - "  DEFINE CLUSTER -"
                - "            (NAME({{DS_NAME}}) -"
                - "            CYL(10 10)  -"
                - "            FREESPACE(20 20) -"
                - "            INDEXED -"
                - "            KEYS(32 0) -"
                - "            NOERASE -"
                - "            NONSPANNED -"
                - "            NOREUSE -"
                - "            SHAREOPTIONS(3 3) -"
                - "            SPEED -"
                - "            UNORDERED -"
                - "            RECORDSIZE(4086 32600) -"
                - " {% if DFS_DS_VOLUME1 %} VOLUMES({{ DFS_DS_VOLUME1 }}) {% endif %} -"
                - "            UNIQUE -"
                - "            )"
      register: result

    - name: show  response
      debug: 
        msg: "{{ result }}"
```

When trying the same as above but instead of an array of strings a long string either will break:
```
    - name: Define cluster 3
      zos_mvs_raw:
        program_name: idcams
        auth: yes
        dds:
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
          - dd_input:
              dd_name: sysin
              content:
                "  DEFINE CLUSTER -
                            (NAME(IMSTESTL.IMS1.RECON4) -
                            CYL(10 10)  -
                            FREESPACE(20 20) -
                            INDEXED -
                            KEYS(32 0) -
                            NOERASE -
                            NONSPANNED -
                            NOREUSE -
                            SHAREOPTIONS(3 3) -
                            SPEED -
                            UNORDERED -
                            RECORDSIZE(4086 32600) -
                            VOLUMES(222222) -
                            UNIQUE)"
      register: result

    - name: show  response
      debug: 
        msg: "{{ result }}"

    - name: Define cluster 3
      zos_mvs_raw:
        program_name: idcams
        auth: yes
        dds:
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
          - dd_input:
              dd_name: sysin
              content:
                "  DEFINE CLUSTER
                            (NAME(IMSTESTL.IMS1.RECON4)
                            CYL(10 10)
                            FREESPACE(20 20)
                            INDEXED
                            KEYS(32 0)
                            NOERASE
                            NONSPANNED
                            NOREUSE
                            SHAREOPTIONS(3 3)
                            SPEED
                            UNORDERED
                            RECORDSIZE(4086 32600)
                            VOLUMES(222222)
                            UNIQUE)"
      register: result

    - name: show  response
      debug: 
        msg: "{{ result }}"
```

Allow me to bring your attention to the fact that a smaller DELETE command that does NOT use an array of strings works fine:
```
    - name: Delete cluster 1
      zos_mvs_raw:
        program_name: idcams
        auth: yes
        dds:
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
          - dd_input:
              dd_name: sysin
              content:
                "  DELETE IMSTESTL.IMS1.RECON3 CLUSTER
                            PURGE"
      register: result

    - name: show  response
      debug:
        msg: "{{ result }}"
```

##### EXPECTED RESULTS

I expect a VSAM to be created with a string input or array of strings, the later works fine.

##### ACTUAL RESULTS

```
(ansible-doc) ddimatos:[ ~/git/github/playbooks ]ansible-playbook -i inventory zos_raw_idcams.yml -vvv
ansible-playbook [core 2.11.12]
  config file = /Users/ddimatos/git/github/playbooks/ansible.cfg
  configured module search path = ['/Users/ddimatos/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/modules']
  ansible python module location = /Users/ddimatos/ansible_versions/3_8_13/ansible-doc/lib/python3.8/site-packages/ansible
  ansible collection location = /Users/ddimatos/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/ddimatos/ansible_versions/3_8_13/ansible-doc/bin/ansible-playbook
  python version = 3.8.13 (default, Jun 14 2022, 23:29:22) [Clang 13.0.0 (clang-1300.0.27.3)]
  jinja version = 3.1.2
  libyaml = True
Using /Users/ddimatos/git/github/playbooks/ansible.cfg as config file
host_list declined parsing /Users/ddimatos/git/github/playbooks/inventory as it did not pass its verify_file() method
script declined parsing /Users/ddimatos/git/github/playbooks/inventory as it did not pass its verify_file() method
auto declined parsing /Users/ddimatos/git/github/playbooks/inventory as it did not pass its verify_file() method
Parsed /Users/ddimatos/git/github/playbooks/inventory inventory source with yaml plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: zos_raw_idcams.yml **********************************************************************************************************
1 plays in zos_raw_idcams.yml

PLAY [zvm] ****************************************************************************************************************************
META: ran handlers

TASK [Define cluster 3] ***************************************************************************************************************
task path: /Users/ddimatos/git/github/playbooks/zos_raw_idcams.yml:142
<ec33017a.vmec.svl.ibm.com> ESTABLISH SSH CONNECTION FOR USER: omvsadm
<ec33017a.vmec.svl.ibm.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="omvsadm"' -o ConnectTimeout=10 -o 'ControlPath="/Users/ddimatos/.ansible/cp/3311113a13"' ec33017a.vmec.svl.ibm.com '/bin/sh -c '"'"'echo ~omvsadm && sleep 0'"'"''
<ec33017a.vmec.svl.ibm.com> (0, b'/\n', b'')
<ec33017a.vmec.svl.ibm.com> ESTABLISH SSH CONNECTION FOR USER: omvsadm
<ec33017a.vmec.svl.ibm.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="omvsadm"' -o ConnectTimeout=10 -o 'ControlPath="/Users/ddimatos/.ansible/cp/3311113a13"' ec33017a.vmec.svl.ibm.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /.ansible/tmp `"&& mkdir "` echo /.ansible/tmp/ansible-tmp-1660756114.179898-64644-220706583319289 `" && echo ansible-tmp-1660756114.179898-64644-220706583319289="` echo /.ansible/tmp/ansible-tmp-1660756114.179898-64644-220706583319289 `" ) && sleep 0'"'"''
<ec33017a.vmec.svl.ibm.com> (0, b'ansible-tmp-1660756114.179898-64644-220706583319289=/.ansible/tmp/ansible-tmp-1660756114.179898-64644-220706583319289\n', b'')
Using module file /Users/ddimatos/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_mvs_raw.py
<ec33017a.vmec.svl.ibm.com> PUT /Users/ddimatos/.ansible/tmp/ansible-local-646402z3oj5si/tmpf9c901oj TO /.ansible/tmp/ansible-tmp-1660756114.179898-64644-220706583319289/AnsiballZ_zos_mvs_raw.py
<ec33017a.vmec.svl.ibm.com> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="omvsadm"' -o ConnectTimeout=10 -o 'ControlPath="/Users/ddimatos/.ansible/cp/3311113a13"' '[ec33017a.vmec.svl.ibm.com]'
<ec33017a.vmec.svl.ibm.com> (0, b'sftp> put /Users/ddimatos/.ansible/tmp/ansible-local-646402z3oj5si/tmpf9c901oj /.ansible/tmp/ansible-tmp-1660756114.179898-64644-220706583319289/AnsiballZ_zos_mvs_raw.py\n', b'')
<ec33017a.vmec.svl.ibm.com> ESTABLISH SSH CONNECTION FOR USER: omvsadm
<ec33017a.vmec.svl.ibm.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="omvsadm"' -o ConnectTimeout=10 -o 'ControlPath="/Users/ddimatos/.ansible/cp/3311113a13"' ec33017a.vmec.svl.ibm.com '/bin/sh -c '"'"'chmod u+x /.ansible/tmp/ansible-tmp-1660756114.179898-64644-220706583319289/ /.ansible/tmp/ansible-tmp-1660756114.179898-64644-220706583319289/AnsiballZ_zos_mvs_raw.py && sleep 0'"'"''
<ec33017a.vmec.svl.ibm.com> (0, b'', b'')
<ec33017a.vmec.svl.ibm.com> ESTABLISH SSH CONNECTION FOR USER: omvsadm
<ec33017a.vmec.svl.ibm.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="omvsadm"' -o ConnectTimeout=10 -o 'ControlPath="/Users/ddimatos/.ansible/cp/3311113a13"' -tt ec33017a.vmec.svl.ibm.com '/bin/sh -c '"'"'_BPXK_AUTOCVT=ON ZOAU_HOME=/u/oeusr01/zoau/1.1.1 JAVA_HOME=/usr/lpp/java/J8.0 PYTHONPATH=/u/oeusr01/zoau/1.1.1/lib LIBPATH=/u/oeusr01/zoau/1.1.1/lib:/u/oeusr01/python/pyz_3_8_2/usr/lpp/IBM/cyp/v3r8/pyz/lib:/lib:/usr/lib:. PATH=/u/oeusr01/zoau/1.1.1/bin:/u/oeusr01/python/pyz_3_8_2/usr/lpp/IBM/cyp/v3r8/pyz/bin:/bin:/var/bin:/usr/lpp/java/J8.0/bin _CEE_RUNOPTS='"'"'"'"'"'"'"'"'FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)'"'"'"'"'"'"'"'"' _TAG_REDIR_ERR=txt _TAG_REDIR_IN=txt _TAG_REDIR_OUT=txt LANG=C /u/oeusr01/python/pyz_3_8_2/usr/lpp/IBM/cyp/v3r8/pyz/bin/python3.8 /.ansible/tmp/ansible-tmp-1660756114.179898-64644-220706583319289/AnsiballZ_zos_mvs_raw.py && sleep 0'"'"''
<ec33017a.vmec.svl.ibm.com> (1, b'\r\n{"changed": false, "dd_names": [], "ret_code": {"code": 8}, "backups": [], "failed": true, "msg": "DatasetWriteError(\'An error occurred during write of data set \\"OMVSADM.P7109382.T0149080.C0000000\\". RC=1. \')", "exception": "  File \\"/tmp/ansible_zos_mvs_raw_payload_r98idsk_/ansible_zos_mvs_raw_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_mvs_raw.py\\", line 1739, in run_module\\n  File \\"/tmp/ansible_zos_mvs_raw_payload_r98idsk_/ansible_zos_mvs_raw_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_mvs_raw.py\\", line 2299, in build_dd_statements\\n  File \\"/tmp/ansible_zos_mvs_raw_payload_r98idsk_/ansible_zos_mvs_raw_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_mvs_raw.py\\", line 2352, in build_data_definition\\n  File \\"/tmp/ansible_zos_mvs_raw_payload_r98idsk_/ansible_zos_mvs_raw_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_mvs_raw.py\\", line 2581, in __init__\\n  File \\"/tmp/ansible_zos_mvs_raw_payload_r98idsk_/ansible_zos_mvs_raw_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/dd_statement.py\\", line 551, in __init__\\n    DataSet.write(name, content)\\n  File \\"/tmp/ansible_zos_mvs_raw_payload_r98idsk_/ansible_zos_mvs_raw_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/data_set.py\\", line 929, in write\\n    raise DatasetWriteError(name, rc)\\n", "invocation": {"module_args": {"program_name": "idcams", "auth": true, "dds": [{"dd_output": {"dd_name": "sysprint", "return_content": {"type": "text", "src_encoding": "ibm-1047", "response_encoding": "iso8859-1"}}, "dd_data_set": null, "dd_unix": null, "dd_input": null, "dd_vio": null, "dd_concat": null, "dd_dummy": null}, {"dd_input": {"dd_name": "sysin", "content": "  DEFINE CLUSTER (NAME(IMSTESTL.IMS1.RECON4) CYL(10 10) FREESPACE(20 20) INDEXED KEYS(32 0) NOERASE NONSPANNED NOREUSE SHAREOPTIONS(3 3) SPEED UNORDERED RECORDSIZE(4086 32600) VOLUMES(222222) UNIQUE)", "return_content": null}, "dd_data_set": null, "dd_unix": null, "dd_output": null, "dd_vio": null, "dd_concat": null, "dd_dummy": null}], "verbose": false, "parm": null}}}\r\n', b'Shared connection to ec33017a.vmec.svl.ibm.com closed.\r\n')
<ec33017a.vmec.svl.ibm.com> Failed to connect to the host via ssh: Shared connection to ec33017a.vmec.svl.ibm.com closed.
<ec33017a.vmec.svl.ibm.com> ESTABLISH SSH CONNECTION FOR USER: omvsadm
<ec33017a.vmec.svl.ibm.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="omvsadm"' -o ConnectTimeout=10 -o 'ControlPath="/Users/ddimatos/.ansible/cp/3311113a13"' ec33017a.vmec.svl.ibm.com '/bin/sh -c '"'"'rm -f -r /.ansible/tmp/ansible-tmp-1660756114.179898-64644-220706583319289/ > /dev/null 2>&1 && sleep 0'"'"''
<ec33017a.vmec.svl.ibm.com> (0, b'', b'')
The full traceback is:
  File "/tmp/ansible_zos_mvs_raw_payload_r98idsk_/ansible_zos_mvs_raw_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_mvs_raw.py", line 1739, in run_module
  File "/tmp/ansible_zos_mvs_raw_payload_r98idsk_/ansible_zos_mvs_raw_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_mvs_raw.py", line 2299, in build_dd_statements
  File "/tmp/ansible_zos_mvs_raw_payload_r98idsk_/ansible_zos_mvs_raw_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_mvs_raw.py", line 2352, in build_data_definition
  File "/tmp/ansible_zos_mvs_raw_payload_r98idsk_/ansible_zos_mvs_raw_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/modules/zos_mvs_raw.py", line 2581, in __init__
  File "/tmp/ansible_zos_mvs_raw_payload_r98idsk_/ansible_zos_mvs_raw_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/dd_statement.py", line 551, in __init__
    DataSet.write(name, content)
  File "/tmp/ansible_zos_mvs_raw_payload_r98idsk_/ansible_zos_mvs_raw_payload.zip/ansible_collections/ibm/ibm_zos_core/plugins/module_utils/data_set.py", line 929, in write
    raise DatasetWriteError(name, rc)
fatal: [zvm]: FAILED! => {
    "backups": [],
    "changed": false,
    "dd_names": [],
    "invocation": {
        "module_args": {
            "auth": true,
            "dds": [
                {
                    "dd_concat": null,
                    "dd_data_set": null,
                    "dd_dummy": null,
                    "dd_input": null,
                    "dd_output": {
                        "dd_name": "sysprint",
                        "return_content": {
                            "response_encoding": "iso8859-1",
                            "src_encoding": "ibm-1047",
                            "type": "text"
                        }
                    },
                    "dd_unix": null,
                    "dd_vio": null
                },
                {
                    "dd_concat": null,
                    "dd_data_set": null,
                    "dd_dummy": null,
                    "dd_input": {
                        "content": "  DEFINE CLUSTER (NAME(IMSTESTL.IMS1.RECON4) CYL(10 10) FREESPACE(20 20) INDEXED KEYS(32 0) NOERASE NONSPANNED NOREUSE SHAREOPTIONS(3 3) SPEED UNORDERED RECORDSIZE(4086 32600) VOLUMES(222222) UNIQUE)",
                        "dd_name": "sysin",
                        "return_content": null
                    },
                    "dd_output": null,
                    "dd_unix": null,
                    "dd_vio": null
                }
            ],
            "parm": null,
            "program_name": "idcams",
            "verbose": false
        }
    },
    "msg": "DatasetWriteError('An error occurred during write of data set \"OMVSADM.P7109382.T0149080.C0000000\". RC=1. ')",
    "ret_code": {
        "code": 8
    }
}

PLAY RECAP ****************************************************************************************************************************
zvm                        : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

#### Ansible.cfg

```
'ansible-config dump --only-changed' output:
(ansible-doc) ddimatos:[ ~/git/github/playbooks ]ansible-config dump --only-changed
DEFAULT_FORKS(/Users/ddimatos/git/github/playbooks/ansible.cfg) = 25
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = ['/Users/ddimatos/.ansible/collections/ansible_collections/ibm/ibm_zos_core/plugins/module>
```

#### Inventory

```
Inventory content:
zsystem:
  hosts:
    zvm:
      ansible_host: ec33017a.vmec.svl.ibm.com
      ansible_user: omvsadm
      ansible_python_interpreter: /u/oeusr01/python/pyz_3_8_2/usr/lpp/IBM/cyp/v3r8/pyz/bin/python3.8
```

#### Vars

```
'group_vars' or 'host_vars' content:
PYZ: "/u/oeusr01/python/pyz_3_8_2/usr/lpp/IBM/cyp/v3r8/pyz"
ZOAU: "/u/oeusr01/zoau/1.1.1"

environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  JAVA_HOME: "{{ JAVA }}"
  PYTHONPATH: "{{ ZOAU }}/lib"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin:{{ JAVA }}/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
```
