### ISSUE TITLE
[Bug] zos_operator throws TypeError when wait_time_s is specified using ZOAU 1.2.1h

### ISSUE THREAD

**Issue by fernandofloresg** [ansible-collections/ibm_zos_core#389]
##### SUMMARY
When specifying wait_time_s in zos_operator using ZOAU 1.2.1h early version it throws TypeError.

##### COMPONENT NAME

zos_operator

##### ANSIBLE VERSION

```
Ansible version output:
ansible [core 2.11.12] 
  config file = None
  configured module search path = ['/Users/fernandoflores/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/fernandoflores/Library/Python/3.8/lib/python/site-packages/ansible
  ansible collection location = /Users/fernandoflores/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/fernandoflores/Library/Python/3.8/bin/ansible
  python version = 3.8.9 (default, Apr 13 2022, 08:48:07) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  jinja version = 3.1.2
  libyaml = True

```

##### SPECIFY ANSIBLE COLLECTION VERSION

1.4.0-beta.1

##### SPECIFY THE Z OPEN AUTOMATION UTILITIES VERSION

2022/08/25 21:44:21 CUT V1.2.1 31163ab 1856

##### STEPS TO REPRODUCE

```yaml
Reproduction playbook/yaml
- hosts: zvm
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  vars:
    ZOAU: "/zoau/v1.2.1h"
    PYZ: "/python2/usr/lpp/IBM/cyp/v3r9/pyz"
  tasks:
    - name: Call opercmd with 5 seconds delay
      zos_operator:
        cmd: "d u,all"
        verbose: True
        wait_time_s: 5
        wait: True
      register: result

    - name: show  response
      debug: 
        msg: "{{ result }}"
```

##### EXPECTED RESULTS

Executes and returns the result with a wait of maximum 5 seconds for the job.

##### ACTUAL RESULTS

```
Playbook output:

fatal: [zvm]: FAILED! => {"changed": false, "msg": "An unexpected error occurred: ZOAUException(\"'timeout' must be an integer.\")"}
```

#### Ansible.cfg

```
'ansible-config dump --only-changed' output:
```

#### Inventory

```
Inventory content:
```

#### Vars

```
'group_vars' or 'host_vars' content:
```
