### ISSUE TITLE
[Bug] zos_operator commmand content appends two empty rows

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#397]
In the dev branch code I noticed when running the zos_operator the content would return 2 empty rows, tracing the code does not seem to depict its in the module and possibly in the API call. 

Example:
```
        "content": [
            "EC33017A   2022244  16:00:49.00             ISF031I CONSOLE OMVS0000 ACTIVATED",
            "EC33017A   2022244  16:00:49.00            -D U,ALL ",
            "EC33017A   2022244  16:00:49.00             IEE457I 16.00.49 UNIT STATUS 645",
            "                                           UNIT TYPE STATUS        VOLSER     VOLSTATE      SS",
            "                                           0000 3390 F-NRD                        /RSDNT     0",
            "                                           0001 3211 OFFLINE                                 0",
            "                                           0002 3211 OFFLINE                                 0",
            "                                           0003 3211 OFFLINE                                 0",
            "                                           0004 3211 OFFLINE                                 0",
            "                                           0005 3211 OFFLINE                                 0",
            "                                           0006 3211 OFFLINE                                 0",
            "                                           0007 3211 OFFLINE                                 0",
            "                                           0008 3211 OFFLINE                                 0",
            "                                           0009 3277 OFFLINE                                 0",
            "                                           000C 2540 A                                       0",
            "                                           000D 2540 A                                       0",
            "                                           000E 1403 A                                       0",
            "                                           000F 1403 A                                       0",
            "                                           0010 3211 A                                       0",
            "                                           0011 3211 A                                       0",
            "",
            ""
        ],
```

##### COMPONENT NAME

  `ibm_zos_operator`

##### ANSIBLE VERSION

```
ansible [core 2.11.12]
```

##### SPECIFY THE Z OPEN AUTOMATION UTILITIES VERSION
2022/08/17 21:25:13 CUT V1.2.1

##### STEPS TO REPRODUCE

```yaml

- hosts: zvm
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - name: Execute operator command
      zos_operator:
        cmd: 'd u,all'
        wait_time_s: 5
        wait: true
        verbose: false
      register: result

    - name: Response 
      debug:
        var: result

```

##### EXPECTED RESULTS
Content that corresponds to the actual response (no trailing lines)
