### ISSUE TITLE
[Bug] [zos_mvs_raw] Add special DDname cases

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#426]
### Bug description

This issue was raised by @adn1107; When using zos_mvs_raw, with something like:
```
//HZSPRINT EXEC PGM=HZSPRNT,REGION=0M,
//  PARM=('CHECK(IBMRACF,RACF_CERTIFICATE_EXPIRATION)','EXCEPTIONS')
//SYSOUT   DD SYSOUT=A,DCB=(LRECL=256)
//
//HZSPRINT EXEC PGM=HZSPRNT,TIME=1440,REGION=0M,PARMDD=SYSIN
//SYSIN DD *,DLM='@@'
CHECK(IBMRACF,RACF_CERTIFICATE_EXPIRATION)
,EXCEPTIONS
@@
//SYSOUT   DD SYSOUT=A,DCB=(LRECL=256)
```

the following DDname specifications are not supported
```
//SYSIN DD *,DLM='@@'
//SYSOUT   DD SYSOUT=A,DCB=(LRECL=256)
```
 
Although this appears to be a valid point and bug, since I don't have much experience with delimiters (DLM) I raised the question if they are really needed? I am wondering if deliminator's are necessary with zos_mvs_raw when you can pass content and not have to concern yourself with a DLM?

For example:

```
- dd_input:
dd_name: sysin
content:
- " DUMP OUTDD(ARCHIVE) -"
- " DS(INCL({{ data_set | upper }}))"
``` 

Here is my full example:
```
- name: Take a set of data sets and write them to an archive.
zos_mvs_raw:
program_name: adrdssu
auth: yes
dds:
- dd_data_set:
dd_name: archive
data_set_name: "{{ archive_data_set }}"
disposition: old
- dd_input:
dd_name: sysin
content:
- " DUMP OUTDD(ARCHIVE) -"
- " DS(INCL({{ data_set | upper }}))"
- dd_output:
dd_name: sysprint
return_content:
type: text
- dd_output:
dd_name: sysabend
return_content:
type: text
register: dump_response
failed_when: dump_response.ret_code.code > 0
```

We don't have a confirmation on this yet, so part of this bug is to investigate whether or not its valid that DLM's be supported, and from @adn1107 

> i need to test this again. I remember trying a lot of different combos but couldn't get it to work. 

### Ansible version

```shell
2.9.27
```

### IBM z/OS Ansible core Version

v1.4.0-beta.1

### IBM ZOAU version

v1.1.1

### Ansible module

zos_mvs_raw

**Comment by richp405** [comment]
This may relate to symbol work that is in an active ticket... on-hold until we can duplicate.

**Comment by richp405** [comment]
Need to go back to Andy and ask for expansion of this.

**Comment by ddimatos** [comment]
Ill share my point and feel free to share it;
DLM (d eliminators) in JCL eg `DLM='@@` mark the start end end points for a DD such as SYSIN such the JCL knows where the SYSIN content starts and end, since more can follow a SYSIN like other DDs.

We don't have this problem in YAML because the `content` block starts after `content:` and YAML requires indentation so the indented bock is essentially what you are trying to put DLM's around in JCL. 

For example this short snippet is grouped by the parent `-dd_input` with sub option `content` , YAML clearly forces you into a start and stop without any need for a DLM. Unless a use case can be provided, it appears this ask is simply for easier porting of JCL without taking into account the Ansible constructs. 
```
    - name: Delete cluster 1
      zos_mvs_raw:
        program_name: idcams
        auth: yes
        dds:
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
          - dd_input:
              dd_name: sysin
              content:
                "  DELETE IMSTESTL.IMS1.RECON3 CLUSTER
                            PURGE"
      register: result
```
