### ISSUE TITLE
[Enhancement][1] Support Jinja templates in modules

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#428]
### Enhancement description

Jinja2 templates can provide a powerful way to reuse `src` content, imagine you have some JCL or other `src` that reusable if  there was a way to replace the variables yet the src remains consistent. 

Today our modules do not accept Jinja as part of the `src` e.g. `src: my.jcl.j2` where JCL might look like:

my.jcl.j2:
```
//HELLO    JOB (T043JM,JM00,1,0,0,0),'HELLO WORLD - JRM',CLASS=R,
//             MSGCLASS=X,MSGLEVEL=1,NOTIFY=S0JM
//STEP0001 EXEC PGM=IEBGENER
//SYSIN    DD DUMMY
//SYSPRINT DD SYSOUT=*
//SYSUT1   DD *
{{ message }}
/*
//SYSUT2   DD SYSOUT=*
//
```

and your playbook you have:
```
---
- hosts: zvm
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"
  vars:
      message: "Hello World"

  tasks:
     - name: submit a job
        zos_job_submit:
        src: my.jcl.j2
        location: LOCAL
       register: result
```

Now the JCL would have the vars substituted.

The community has a `template` module dedicated to taking *.j2 and `copy` for files, I don't know if it makes sense for us model after that given several of our modules could benefit from templating, those being `zos_copy`, `zos_job_submit` and  maybe `zos_fetch` to name a few. I think this issue needs to also perform a bit of research before developing. 

There is a decent introductory blog on this topic [here](https://www.linuxtechi.com/configure-use-ansible-jinja2-templates/)
and maybe also review to better understand the [difference between the community copy and template modules](https://dev.to/koh_sh/difference-between-ansible-s-copy-and-template-module-41e6).

### Ansible module

zos_copy, zos_fetch, zos_job_submit
