### ISSUE TITLE
[Enhancement] [zos_blockinfile] Add a  examples docs to use a var in block argument

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#430]
### Enhancement description

Currently there is one example but using variable substitution in the [zos_blockinfile](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/modules/zos_blockinfile.html) but it would be helpful if we created a more z/OS specific one for JCL, something many users use this module to edit. 

This issue relied on that #422 was fixed/validated and it was, so now this is simply a doc issue that remains. 

## User Story
As a user,  I want to be aware of the capability of using variables as input for `zos_blockinfile` module so that I can refer to the examples for guidance in doing so.

Something like (this example needs work):
```
- name: Add systsin data
     zos_blockinfile:
       src: "{{ uss_dir }}/{{ temp_systsin }}"
       marker: "/* {mark} ANSIBLE MANAGED BLOCK ADD SYSTSIN */"
       block: |
         DSN SYSTEM({{ DB2SSID }})
         RUN  PROGRAM(DSNTEP2) PLAN(DSNTEP12) -
              LIB('{{ DB2RUN }}.RUNLIB.LOAD')
```

Maybe one more example where block text will reside in some file and you want redirection of that files content into the block section. Not sure this example work with `zos_blockinfile` , i believe it does work with the community `blockinfile`.
```
- name: Example of file contents as a block
              zos_blockinfile:
                    path: "/tmp/jcl.txt"
                    insertbefore: BOF
                    create: yes
                    marker: "//* {mark} *//"
                    marker_begin: "1st Ansible Insert start"
                    marker_end: "1st Ansible Insert end"
                    block: "{{ jcl_file }}"
jcl_file is set in vars:
     vars:
        jcl_file: "{{ lookup('file', '/tmp/jcl.txt') }}" (edited) 
```

### Notes:
Where this conversation occurred `archives/CSLEJ8VGV/p1643668213540119`

### Ansible module

zos_blockinfile

**Comment by ddimatos** [comment]
Task:
```
    - name: Set facts for demonstration purposes.
      set_fact:
        HLQ: 'ANSIBLE'
        MLQ: 'MEMBER'
        LLQ: 'TEST'
        MEM: '(JCL)'
        MSG: 'your first JCL program'

    - name: Update JCL in a PDS member with Jinja2 variable syntax.
      zos_blockinfile:
        src: "{{ HLQ }}.{{MLQ}}.{{LLQ}}{{MEM}}"
        insertafter: "HELLO, WORLD"
        marker: "//* {mark} *//"
        marker_begin: " Begin Ansible Block Insert "
        marker_end: " End Ansible Block Insert "
        state: present
        block: |
          This is {{ MSG }}, and its now
          managed by Ansible.
      register: result

    - name: Response
      debug:
        msg: "{{ result }}"
```

Result:
```
TASK [Update JCL in a PDS member with Jinja2 variable syntax.] ***************************************************************************************************************************
changed: [zvm]

TASK [Response] **************************************************************************************************************************************************************************
ok: [zvm] => {
    "msg": {
        "changed": 1,
        "cmd": "dmodhelper -b -d -c IBM-1047 -m  Begin Ansible Block Insert \n End Ansible Block Insert \n//* {mark} *// -s -e /HELLO, WORLD/a\\This is your first JCL program, and its now\nmanaged by Ansible./$ -e $ a\\This is your first JCL program, and its now\nmanaged by Ansible. ANSIBLE.MEMBER.TEST(JCL) ",
        "failed": false,
        "found": 1
    }
}
```

JCL edited:
```
//HELLO    JOB (T043JM,JM00,1,0,0,0),'HELLO WORLD - JRM',   
//             MSGCLASS=X,MSGLEVEL=1,NOTIFY=&SYSUID         
//STEP0001 EXEC PGM=IEBGENER                                
//SYSIN    DD DUMMY                                         
//SYSPRINT DD SYSOUT=*                                      
//SYSUT1   DD *                                             
HELLO, WORLD                                                
//*  Begin Ansible Block Insert  *//                        
This is your first JCL program, and its now                 
managed by Ansible.                                         
//*  End Ansible Block Insert  *//                          
/*                                                          
//SYSUT2   DD SYSOUT=*                                      
//                                                          
```

**Comment by ddimatos** [comment]
Task:
```
    - name: Updated JCL in PDS member with content from a file
      zos_blockinfile:
        src: "{{ HLQ }}.{{MLQ}}.{{LLQ}}{{MEM}}"
        insertafter: "//*  End Ansible Block Insert  *//"
        marker: "//* {mark} *//"
        marker_begin: " Begin Ansible Block Insert "
        marker_end: " End Ansible Block Insert "
        block: "{{ CONTENT }}"
```

files/content.txt:
```
This is another edit managed by Ansible.
This is content is coming from a file
located in USS.
```

JCL Edited:
```
 BROWSE    ANSIBLE.MEMBER.TEST(JCL)                 Line 0
 Command ===>                                             
********************************* Top of Data ************
//HELLO    JOB (T043JM,JM00,1,0,0,0),'HELLO WORLD - JRM', 
//             MSGCLASS=X,MSGLEVEL=1,NOTIFY=&SYSUID       
//STEP0001 EXEC PGM=IEBGENER                              
//SYSIN    DD DUMMY                                       
//SYSPRINT DD SYSOUT=*                                    
//SYSUT1   DD *                                           
HELLO, WORLD                                              
/*                                                        
//SYSUT2   DD SYSOUT=*                                    
//                                                        
//*  Begin Ansible Block Insert  *//                      
This is another edit managed by Ansible.                  
This is content is coming from a file                     
located in USS.                                           
//*  End Ansible Block Insert  *//                        
```
