### ISSUE TITLE
[Enhancement] add symbols support in zos_job_submit

### ISSUE THREAD

**Issue by azarrafa** [ansible-collections/ibm_zos_core#532]
### Enhancement or featture description

Hello,
Is possible to add symbol support in zos_job_submit module. 
For exemple : 
   
```
 - name: Submit the JCL
  zos_job_submit:
    src: TEST.UTILs(SAMPLE)
    location: DATA_SET
    symbols: 
     - var1: value1
     - var2: value2
  register: response
```

### Ansible module

zos_job_submit

**Comment by ddimatos** [comment]
Hello @azarrafa , thank you for taking the time to request an enhancement. 

If i understand correctly you are requesting that as we submit the JCL that has a symbol that we insert the values for that JCL.
For example JCL TEST.SYMBOL.PDS
```
//S1 EXEC PGM=WTO,PARM='&SYM1'
//DD1 DD DSN=&SYMBOL2,UNIT=SYSDA,SPACE=(TRK,(1,1))
//DD2 DD DSN=&SYMBOL3,UNIT=SYSDA,SPACE=(TRK,(1,1))
//DD3 DD DSN=&SYMBOL4,UNIT=SYSDA,SPACE=(TRK,(1,1))
//DD4 DD DSN=&SYMBOL5,UNIT=SYSDA,SPACE=(TRK,(1,1))
// PEND
```

Corresponding playbook:
```
 - name: Submit the JCL
  zos_job_submit:
    src: TEST.UTILs(SAMPLE)
    location: DATA_SET
    symbols: 
     - SYMBOL1: This is a WTO
     - SYMBOL2: TMP2
     - SYMBOL3: TMP3
     - SYMBOL4: TMP4
     - SYMBOL5: TMP5
  register: response
```

would yield:
```
1 EXEC PGM=WTO,PARM='What's up, Doc?',ACCT=(DEF)
//DD1 DD DSN=TMP2,UNIT=SYSDA,SPACE=(TRK,(1,1))
//DD2 DD DSN=TMP3,UNIT=SYSDA,SPACE=(TRK,(1,1))
//DD3 DD DSN=TMP4,UNIT=SYSDA,SPACE=(TRK,(1,1))
//DD4 DD DSN=TMP5,UNIT=SYSDA,SPACE=(TRK,(1,1))
```

If so, this is very much like Jinja2 where JCL could be templated and you insert what you wish there, [have a look at this work item](https://github.com/ansible-collections/ibm_zos_core/issues/428) and let us know if its going to resolve this issue.
