### ISSUE TITLE
[Bug][zos_job_submit] Exception thrown when submitting a job in LOCAL mode as particular CI user

### ISSUE THREAD

**Issue by Mark-J-Lawrence** [ansible-collections/ibm_zos_core#540]
### Bug description

Playbook contains the following task:

```
- name: Submit job to regenerate RACF commands
      ibm.ibm_zos_core.zos_job_submit:
        src: ../racf.jcl
        location: LOCAL
        wait: true
        wait_time_s: 300
        return_output: true
```

When I run locally, it logs in as my own user (using a password) on the z/OS machine, and it works perfectly.

However, when I then run this as part of a jenkins job (using an SSH key to a user called `JENKINS`) it fails with an exception. I have tried changing the `location` to `USS`, but it fails with the same error.

The exception thrown is not particularly helpful because it appears another exception is thrown which doesn't inherit from `BaseException`, which causes a distraction.

To diagnose the problem myself a bit further, I manually changed `/python/v3r10/pyz/lib/python3.10/site-packages/zoautil_py/jobs.py` to stream `response.stdout_response` to a local text file (`response.stderr_response` was empty, the line that raises a ZOAUException does not handle this). The file contained:

```
submit 'JENKINS.P3622224.T0720544.C0000000'
RECORD LENGTH OF DATA SET JENKINS.P3622224.T0720544.C0000000 NOT 80
```

A quick google of that response sent me here: https://www.ibm.com/docs/en/zos/2.1.0?topic=ikj-ikj56261i

So it appears the temporary data set that is being created to store the JCL isn't being created with the correct record size....but only for the JENKINS user, for some reason?

If I change `location` to `DATA_SET` and point it to the JCL stored on the system, the task hangs.

### Playbook verbosity output

[ansible_log.docx](https://github.com/ansible-collections/ibm_zos_core/files/9829128/ansible_log.docx)

### Contents of `ansible.cfg`

```
[defaults]
inventory = ./inventory
library = ./library
action_plugins=./plugins/action
host_key_checking = False
pipelining = False
```

### Contents of the inventory

```
all:
  hosts:
    winmvsb0:
      ansible_host: winmvsb0.hursley.ibm.com
      ansible_user: jenkins
      ansible_connection: ssh 
      host_key_checking: false
```

### Contents of `group_vars` or `host_vars`

`host_vars`:

```
PYZ: "/python/v3r10/pyz"
ZOAU: "/usr/lpp/IBM/zoautil"
ansible_python_interpreter: "{{ PYZ }}/bin/python"

# The location of ROCKET z Open Source TOOLS
TOOLS_ROOT: "/rocket"
TOOLS_PATH: "{{ TOOLS_ROOT }}/bin"

GIT_SHELL: "{{ TOOLS_ROOT }}/bin/bash"
GIT_EXEC_PATH: "{{ TOOLS_ROOT }}/libexec/git-core"
GIT_TEMPLATE_DIR: "{{ TOOLS_ROOT }}/share/git-core/templates"
```

`group_vars`:

```
PYZ: "/python/v3r10/pyz"
ZOAU: "/usr/lpp/IBM/zoautil"

environment_vars:
  _BPXK_AUTOCVT: "ON"
  PYTHON: "{{ PYZ }}/bin"
  ZOAU_ROOT: "{{ ZOAU }}"
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin:/usr/sbin"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  MANPATH: "{{ ZOAU }}/docs/%L"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
```

### Ansible version

```
ansible-core==2.11.11
```

### IBM z/OS Ansible core Version

v1.4.0-beta.1

### IBM ZOAU version

v1.1.1

### z/OS version

z/OS 02.04.00

### Ansible module

zos_job_submit
