### ISSUE TITLE
[Bug][zos_copy][TS]Recreate an error when copying zip files from controller to managed node

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#544]
### Bug description

Error occurs when performing this task
```
Ansible Task:
===========
    zos_copy:
      src: "/tmp/tax-code-adaptor-cics-1.0.0.zip"
      dest: "/usr/lpp/cicsts/liberty/tax-code-adaptor-cics-1.0.0.zip"
      is_binary: true
      force: true
      mode: '0775'
      sftp_port: 22
      validate: true
```

Error (sanitized):
```
fatal: [[foo.com](http://foo.com/)]: FAILED! => {"changed": false, "msg": "Error transfering source '/tmp/tax-code-adaptor-cics-1.0.0.zip' to remote z/OS system", "rc": 0, "stderr": "Connected to [user@foo.com](mailto:user@foo..com).", "stderr_lines": ["Connected to [user@foo.com](mailto:user@foo.com)."]}
```

Also note there appears to be a type in the error msg "transfering".

Note: this is using zoau 1.1 (yet the selection box has 1.1.1) so assuming that 1.1 has not had the latest PTF applied

Note: there is no selection or option to enter the managed node python, that is version 3.9 

### Ansible version

```shell
ansible --version
ansible 2.10.17
config file = /etc/ansible/ansible.cfg
........
ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
executable location = /usr/local/bin/ansible
python version = 3.6.8 (default, Jan 14 2022, 11:04:20) [GCC 8.5.0 20210514 (Red Hat 8.5.0-7)]
```

### IBM z/OS Ansible core Version

v1.3.1

### IBM ZOAU version

v1.1.1

### Ansible module

zos_copy
