### ISSUE TITLE
[Bug][zos_linefile] Does not behave like community version, you end up with a duplicate entry

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#583]
### Bug description

When you run the module twice you end up with two entries of the same line using zos_blockinfile where with the community version you do not. zos_linefile should align to the community version. 

Using zos_blockinfile you end up with two entries:
```

---
- hosts: zvm
  gather_facts: false
  environment: "{{ environment_vars }}"
  collections:
    - ibm.ibm_zos_core

  tasks:
    # - name: Touch a file
    #   ansible.builtin.file:
    #     path: /tmp/ansible_file1
    #     state: touch

    - name: Linefile
      zos_lineinfile:
        src: /tmp/ansible_file1
        state: present
        line: "ABCD"

    - name: Linefile
      zos_lineinfile:
        src: /tmp/ansible_file1
        state: present
        line: "ABCD"
```

```
# cat ansible_file1
ABCD
ABCD
```

This community usage results in only one entry in the file  `/tmp/ansible_file1`, note that using the community version.
```
---
- hosts: zvm
  gather_facts: false
  environment: "{{ environment_vars }}"
  collections:
    - ibm.ibm_zos_core

  tasks:
    - name: Linefile
      lineinfile:
        path: /tmp/ansible_file1
        state: present
        line: "ABCD"

    - name: Linefile
      lineinfile:
        path: /tmp/ansible_file1
        state: present
        line: "ABCD"
```

```
# cat ansible_file1
ABCD
```

### Ansible version

```shell
2.9
```

### IBM z/OS Ansible core Version

v1.4.0-beta.2

### IBM ZOAU version

v1.1.1

### z/OS version

2.4

### Ansible module

zos_lineinfile
