### ISSUE TITLE
[Bug][zos_linefile] When the destination does not exist it assumes a data set is missing

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#584]
### Bug description

I noticed this error `fatal: [zvm]: FAILED! => {"changed": false, "msg": "None data set type is NOT supported"}` when I accidentally pointed to a non-existent USS file.

On quick glance it looks like the bug may be in the module_utils call [here](https://github.com/ansible-collections/ibm_zos_core/blob/2b14281e1bb6db9fe03992af8a89c96a222a70bd/plugins/modules/zos_lineinfile.py#L423), for some reason it thinks my USS file is a data set.

```
    ds_utils = data_set.DataSetUtils(src)
    file_type = ds_utils.ds_type()
```

```
---
- hosts: zvm
  gather_facts: false
  environment: "{{ environment_vars }}"
  collections:
    - ibm.ibm_zos_core

  tasks:
    - name: Linefile
      lineinfile:
        src: /tmp/ansible_file1
        state: present
        line: "ABCD"
```

### Ansible version

```shell
2.9
```

### IBM z/OS Ansible core Version

v1.4.0-beta.2

### IBM ZOAU version

v1.1.1

### z/OS version

2.4

### Ansible module

zos_lineinfile
