### ISSUE TITLE
[Bug][zos_linefile] Each time I run the module a dump looking file is left behind in tmp 

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#585]
### Bug description

I ran the module a few times and noticed this left behind:
```
33554539.PO120722.SI085027.X0003735.Y0000000  67108972.PO120722.SI085119.X0004426.Y0000000
33554540.PO120722.SI085116.X0004502.Y0000000  ansible_file1
```

Playbook was:
```
---
- hosts: zvm
  gather_facts: false
  environment: "{{ environment_vars }}"
  collections:
    - ibm.ibm_zos_core

  tasks:
     - name: Linefile
       lineinfile:
         src: /tmp/ansible_file1
         state: present
         line: "ABCD"
```

### Ansible version

```shell
2.9
```

### IBM z/OS Ansible core Version

v1.4.0-beta.2

### IBM ZOAU version

v1.1.1

### z/OS version

2.4

### Ansible module

zos_lineinfile
