### ISSUE TITLE
[Bug] [zos_copy] Issue with module zos_copy z/OS in z/OS core 1.4.0 with attributes force=True and backup=False

### ISSUE THREAD

**Issue by jbyibm** [ansible-collections/ibm_zos_core#587]
### Bug description

We just give a try with IBM Ansible Core 1.4.0, and we have an issue we don't understand with zos_copy. (A blocker for our customer)

We have set force=True and backup=False. This should force the copy even if the destination member is already present in the target  PDS and do not create a backup.  In our use case the member is already present in the target PDS.

But we have this message. With all results values sets to null.
We see in the message that zos_copy is trying to create a backup. Why backup=False?

How to invest ? We have nothing  in the response (null value).

```
fatal: [zos_host_01]: FAILED! => {
    "changed": false,
    "failed_when_result": true,
    "invocation": {
        "module_args": {
            "backup": false,
            "dest": "NAZARE.GENAPP.BUG140.LOADLIB(LGACDB02)",
            "force": true,
            "is_binary": true,
            "remote_src": true,
            "src": "/tmp/wd_deploy/jenkins/zos_host_01/ansible.izgdvvv2/CICSLOAD/LGACDB02.CICSLOAD"
        }
    },
    "msg": "BackupError('An error occurred during backup: \"Unable to backup NAZARE.GENAPP.BUG140.LOADLIB(LGACDB02) to NAZARE.GENAPP.BUG140.LOADLIB(T14IN0H9)\"')",
    "rc": null,
    "stderr": null,
    "stderr_lines": null,
    "stdout": null,
    "stdout_lines": null
}
```

### Playbook verbosity output

```
fatal: [zos_host_01]: FAILED! => {
    "changed": false,
    "failed_when_result": true,
    "invocation": {
        "module_args": {
            "backup": false,
            "dest": "NAZARE.GENAPP.BUG140.LOADLIB(LGACDB02)",
            "force": true,
            "is_binary": true,
            "remote_src": true,
            "src": "/tmp/wd_deploy/jenkins/zos_host_01/ansible.izgdvvv2/CICSLOAD/LGACDB02.CICSLOAD"
        }
    },
    "msg": "BackupError('An error occurred during backup: \"Unable to backup NAZARE.GENAPP.BUG140.LOADLIB(LGACDB02) to NAZARE.GENAPP.BUG140.LOADLIB(T14IN0H9)\"')",
    "rc": null,
    "stderr": null,
    "stderr_lines": null,
    "stdout": null,
    "stdout_lines": null
}
```

### Contents of `ansible.cfg`

```YAML
#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2022. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
[defaults]
forks = 25
host_key_checking = False
#callbacks_enabled = timer, profile_tasks, profile_roles

[ssh_connection]
pipelining = True
#ssh_args = -o ControlMaster=auto -o ControlPersist=3600s -o PreferredAuthentications=publickey
```

### Contents of the inventory

```YAML
all:
  hosts:
    zos_host_01:
      ansible_host: X.X.X.X
      ansible_user: USER
      ansible_ssh_port: 2
```

### Contents of `group_vars` or `host_vars`

```YAML
################################################################################
# Enviroment variables for all z/OS managed nodes (target) that do not need
# further configuration.
################################################################################
environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  #PYTHONPATH: "{{ ZOAU }}/lib"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
```

### Ansible version

```shell
ansible [core 2.11.12]
  config file = /home/jby/ansible.cfg
  configured module search path = ['/home/jby/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /home/jby/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

### IBM z/OS Ansible core Version

v1.4.0

### IBM ZOAU version

v1.2.1

### z/OS version

2.4

### Ansible module

zos_copy
