### ISSUE TITLE
[Bug]  zos_copy 1.4 - carriage return is taken into account when allocating destination file

### ISSUE THREAD

**Issue by vlodeibm** [ansible-collections/ibm_zos_core#599]
### Bug description

When I want to copy a text file from the uss partition to a zos sequential data set without specifying the dest_data_set parameter, the output file is created with a record length taking into account the carriage return. For example, if my input file contains more than one line, each line which length is 3 characters, the output file is created with a length of 4 (3 + carriage return)  whereas if my input file contains only one line of 5 characters, without a carriage return, my file output is created with a length of 4. 

The playbook succeeded but the data set created has a wrong length. 

### Playbook verbosity output

![image](https://user-images.githubusercontent.com/122458609/211860223-a10f74c1-6f22-4629-8f1a-f209b8e8ba1f.png)

### Contents of `ansible.cfg`

```YAML
#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2022. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
[defaults]
forks = 25
host_key_checking = False
#callbacks_enabled = timer, profile_tasks, profile_roles
stdout_callback = ibm.ibm_zos_plum_deploy.cb_evidences

[ssh_connection]
pipelining = True
#ssh_args = -o ControlMaster=auto -o ControlPersist=3600s -o PreferredAuthentications=publickey

[callback_evidences]
evidences_folder = ../evidences
```

### Contents of the inventory

```YAML
all:
  hosts:
    cvb1:
      ansible_host: X.X.X.X
      ansible_user: MYUSER
      ansible_ssh_port: 222
```

### Contents of `group_vars` or `host_vars`

```YAML
environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  #PYTHONPATH: "{{ ZOAU }}/lib"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
```

### Ansible version

```shell
ansible [core 2.11.12]
  config file = None
  configured module search path = ['/home/vlode/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /home/vlode/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

### IBM z/OS Ansible core Version

v1.4.0

### IBM ZOAU version

v1.2.1

### z/OS version

2.4

### Ansible module
zos_copy
