### ISSUE TITLE
[Bug] [zos_copy] Mode set for files is applied to destination directory

### ISSUE THREAD

**Issue by rexemin** [ansible-collections/ibm_zos_core#619]
### Bug description

When setting `mode` and copying the contents of a directory, the new permissions are applied to the destination directory too. This is a deviation from the behavior of the community module, where the permissions are only applied to the files that are getting copied.

Example task:
```yaml
tasks:
    - name: Copy remote text files.
      zos_copy:
        src: ./tests/
        dest: /test/
        mode: '0644'
        force: true
        remote_src: false
```

And where `/test/` has permissions `755` initially. Output from `ls -la` after using zos_copy:
```
drw-r--r--   2 BPXROOT  SYS1        8192 Jan 20 16:08 test
```

Output from `ls -la` after using the community copy module:
```
drwxr-xr-x   2 BPXROOT  SYS1        8192 Jan 20 16:06 test
```

### Contents of `ansible.cfg`

```YAML
[defaults]
forks = 25
# remote_tmp = /u/ansible/tmp
# remote_port = 22
# debug = True
# verbosity = 1

[ssh_connection]
pipelining = True

[colors]
verbose = green
```

### Contents of the inventory

```YAML
source_system:
  hosts:
    zvm:
      ansible_host: ***
      ansible_user: "omvsadm"
      ansible_python_interpreter: "/python3/usr/lpp/IBM/cyp/v3r8/pyz/bin/python3.8"
```

### Ansible version

```shell
ansible [core 2.11.12] 
  config file = /Users/iamorenosoto/Documents/IBM/Development/GitHub/553_554/playbooks/ansible.cfg
  configured module search path = ['/Users/iamorenosoto/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/iamorenosoto/.pyenv/versions/3.8.12/envs/gh-553-554/lib/python3.8/site-packages/ansible
  ansible collection location = /Users/iamorenosoto/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/iamorenosoto/.pyenv/versions/gh-553-554/bin/ansible
  python version = 3.8.12 (default, Jan 17 2022, 16:02:56) [Clang 13.0.0 (clang-1300.0.27.3)]
  jinja version = 3.1.2
  libyaml = True
```

### IBM z/OS Ansible core Version

v1.4.0

### IBM ZOAU version

v1.1.1

### z/OS version

2.3

### Ansible module

zos_copy
