### ISSUE TITLE
[Epic] [Collaboration] Review ansible-core and IBM Enterprise Python's usage of file tagging with binary files

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#676]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Support and service?

- [ ] Yes support and service is involved.
- [X] No support and service is involved.

### Are the dependencies a supported?

- [ ] Yes, the dependencies are supported.
- [X] Not applicable to this collaboration.

### IBM Z Open Automation Utilities

None

### IBM Enterprise Python

v3.11.x, v3.10.x

### IBM z/OS Ansible core Version

None

### ansible-version

None

### z/OS version

None

### Collaboration description

The community modules such as `lineinfile`,`file` and `script` when interacting with a z/OS managed node will end up leaving files unreadable. When a file is opened by python as binary `rb` on the z/OS managed node, Python expects that to be in UTF-8 and most of the time its in the managed nodes default locale as EBCDIC which then leaves the file unreadable. 

Many times the modules will not be able to execute correctly because they don't know how to handle EBCDIC. 

This work item has various scope but narrowing it down is the idea and possibly including other issues under this collaboration will help clarify what is being attempted.

Tasks:
- [x] #705 - Convert the notes/playbook to serve as a reproducible test that can be replayed and used to evaluate the problem
   - [x] #708
           Test setting `ansible_ssh_transfer_method: sftp`, by default Ansible uses scp where on z/OS this becomes a transfer that is auto converted to the z/OS locale, by switching to SFTP as the transport protocol it will ensure a binary transfer and encodings don't change. This will break zos_ibm_core modules but that is ok for now, point is try to understand if there is a community work around 
   - [x] #709
          Investigate using `transfer_method = piped`, I believe `piped` is using `dd` to do what what SFTP or SCP was doing. This may break zos_ibm_core modules but that is ok for now, point is to understand the community work around. 
- [x] #706
        Investigate if their is a common point all traffic to the managed node goes through such that we can override and potentially change the files tag when it lands on z/OS. I believe this would be difficult, complex and difficult to maintain because the ideal place would be the ssh connection ([ssh.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/ssh.py)) yet all modules float over that and we would have to decide what is a file and what changes need to be made to be readable on z/OS. 
- [x] #707
       Investigate porting a simple module to demonstrate the community the impact to other modules, consider something like the file module. 
- [x] Work with the IBM Enterprise Python team using issue #979 to figure out what the root cause is , what be done in the short term vs the long term, where short term might be to introduce an environment variable and long term would be to work with the USS team to alter how binary files might change when processes such as Python read them.
- [ ] Work with IBM Enterprise Python, Red Hat Ansible partners and the community to understand the purpose of why files are opened with Read Binary mode over Text, issue #1159  ([Enabler] Collaborate with IBM Python, Ansible partners and the community on the read binary and encoding issue to find a solution)

- [x] #825 
- [x] #956 

Note: Issue #775 could be related to this epic or even #983, it will be moved accordingly when its reviewed. 
- [x] Review issue for relevance:  [BUG community shell module returns garbage in a call to dls if pipeling is disabled for ibm pyz3.10+ #775](https://github.com/ansible-collections/ibm_zos_core/issues/775)

```
################################################################################
# Run this playbook like so:
# ansible-playbook -i inventory community_lineinfile.yml
#
# This recreate is not completely automated so you will need some manual steps
# first
################################################################################

################################################################################
# PYTHON 3.10 scenario, pipelining = false
################################################################################
# 00) - Ensure ansible.cfg option pipeline is `pipelining = False`, if using
#       ansible 2.11 or later, be sure to put it under [connection] else [ssh_connection]
#     - Ensure you are using Python 3.10 (update inventory and all.yml)
# 0) ssh <user>@<host>
# 1) cd /tmp
# 2) rm -rf afile
# 3) echo "ABCD=NUM">afile
# 4) cat afile
# 5) ls -laTE afile
#        Note: Tagging does not seem to pose any difference, I have tried both:
#        t IBM-1047    T=on  -rw-r--r--  --s-  1 BPXROOT  OMVSGRP        9 Jan 26 11:24 afile
#        - untagged    T=off -rw-r--r--  --s-  1 BPXROOT  OMVSGRP        9 Jan 27 10:51 afile
# 6) On the controller/laptop run the playbook: `ansible-playbook -i inventory community_lineinfile.yml`
# 7) Step (6) should be successful: .... zvm                        : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
# 8) ssh <user>@<host>
# 9) cd /tmp
# 8) iconv -f UTF-8 -t IBM-1047 afile>file
# 9) cat file
#       B�~
#       ABCD=ALPHA
# 9.1) cat afile
#        ABCD=NUM
#        ^0A^41^42^43^44^U^41<&^48^41^0A
# 10) You can see from this that ansible understood how to use the REGEX when in
#     python 3.10 but it did not do a replace as it should have, it appended the
#     the updated line.

################################################################################
# PYTHON 3.10 scenario, pipelining = True
################################################################################
# Repeat the above scenario, you really don't have to do anything but just run
# with Python 3.10, pipelining-True and you will see this error:
#
# @@@@@@@@@@@@������m������M������m���k@����m����k@���������m������]\u0015@@@@�������z
# \u0015@@@@@@@@���z\u0015@@@@@@@@@@@@������K������M����m����]\u0015@@@@@@@@������@MՁ��ř���k@��ř���]z
# \u0015@@@@@@@@@@@@����\u0015@@@@���K����M��������]\u0015��@mm����mm@~~@}mm����mm}z\u0015@@@@m���������m����M]
# \n                                                             ^\nSyntaxError: (unicode error)
# 'utf-8' codec can't decode byte 0x81 in position 2: invalid start byte\n", "module_stdout": "", "msg":
# "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

################################################################################
# Python 3.9 scenario pipelining = True
################################################################################
# 00) - Ensure ansible.cfg option pipeline is `pipelining = True`, if using
#       ansible 2.11 or later, be sure to put it under [connection] else [ssh_connection]
#     - Ensure you are using Python 3.9 (update inventory and all.yml)
# 0) ssh <user>@<host>
# 1) cd /tmp
# 2) rm -rf afile
# 3) echo "ABCD=NUM">afile
# 4) cat afile
# 5) ls -laTE afile
#        Note: Tagging does not seem to pose any difference, I have tried both:
#        - untagged    T=off -rw-r--r--  --s-  1 BPXROOT  OMVSGRP       11 Jan 27 11:27 afile
# 6) On the controller/laptop run the playbook: `ansible-playbook -i inventory community_lineinfile.yml`
# 7) Step (6) should be successful: .... zvm                        : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
# 8) ssh <user>@<host>
# 9) cd /tmp
# 8) iconv -f UTF-8 -t IBM-1047 afile>file
# 9) cat file
#     ABCD=ALPHA
# 9.1) cat afile
#        �����<&砎
# 10) You can see from this that with PYZ 3.9 the line ABCD was correctly replace
#     and not appended to as python 3.10 with pipeling=false incorrectly does.

################################################################################
# Python 3.9 scenario pipelining = False
################################################################################
# 00) - Ensure ansible.cfg option pipeline is `pipelining = False`, if using
#       ansible 2.11 or later, be sure to put it under [connection] else [ssh_connection]
#     - Ensure you are using Python 3.9 (update inventory and all.yml)
# Repeat the above steps, its successful just like "Python 3.9 scenario pipelining = True"
# Here are the cat's:
# [ OMVSADM:/SYSTEM/tmp: ]cat file
# ABCD=ALPHA
#[ OMVSADM:/SYSTEM/tmp: ]cat afile
#�����<&砎[ OMVSADM:/SYSTEM/tmp: ]


################################################################################
# Summary
################################################################################
# It DOES  matter in this scenario if `pipelining` is 'True' or 'False'
################################################################################
---
- hosts: zvm
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - name: Add ABCD to ansible_file1
      ansible.builtin.lineinfile:
        path: /tmp/file
        state: present
        regex: '^ABCD='
        line: "ABCD=ALPHA"

```
