### ISSUE TITLE
[Bug] [zos_mvs_raw] When invoking a program with a steplib the expected output is never returned

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#679]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.2

### IBM Enterprise Python

v3.9.x

### IBM z/OS Ansible core Version

v1.5.0

### ansible-version

v2.14.x

### z/OS version

v2.5

### Ansible module

zos_mvs_raw

### Bug description

I am not sure this is only when a steplib is involved but I have been investigating another issue and noticed some odd behavior. 

I have cobol application , all it does is a DISPLAY "SIMPLE HELLO WORLD" and noticed that the response was never coming back. I asked for the response to be return as text and instead I was given a temp data set which no longer existed. 

My assumptions are the content is in the data set that is returned (temp data set) but we did not extract it correctly for sysprint. 

This playbook:
```
    - name: Execute program
      zos_mvs_raw:
        program_name: HELLOPGM
        auth: false
        verbose: true
        dds:
          - dd_data_set:
              dd_name: steplib
              data_set_name: ANSIBLE.COBOL.LOADLIB
          - dd_output:
              dd_name: sysprint
              return_content:
                type: text
          - dd_output:
              dd_name: stderr
              return_content:
                type: text
          - dd_output:
              dd_name: stdout
              return_content:
                type: text
      register: result
      tags: case_load_lib

    - name: Result
      debug:
         msg: "{{result}}"
      tags: case_load_lib
```
Returns:
```
ok: [zvm] => {
    "msg": {
        "backups": [],
        "changed": true,
        "dd_names": [
            {
                "byte_count": 0,
                "content": [
                    ""
                ],
                "dd_name": "sysprint",
                "name": "OMVSADM.P0331954.T0211743.C0000000",
                "record_count": 1
            },
            {
                "byte_count": 0,
                "content": [
                    ""
                ],
                "dd_name": "stderr",
                "name": "OMVSADM.P6777525.T0085483.C0000000",
                "record_count": 1
            },
            {
                "byte_count": 0,
                "content": [
                    ""
                ],
                "dd_name": "stdout",
                "name": "OMVSADM.P6777527.T0842977.C0000000",
                "record_count": 1
            }
        ],
        "failed": false,
        "ret_code": {
            "code": 0
        }
    }
}
```

While this one returns the output as stderr (could be the cobol application needs to output to a DD to be stdout, so lets look past that point for now). Even the commented out command works in the below:
```
    - name: Execute with mvscmd
      #ansible.builtin.shell: mvscmd --pgm=HELLOPGM  --steplib=ANSIBLE.COBOL.LOADLIB --sysprint=*
      ansible.builtin.shell: mvscmd --pgm=HELLOPGM  --steplib=ANSIBLE.COBOL.LOADLIB --sysprint=* --stderr=* --stdout=*
      register: result
      tags: case_mvscmd

    - name: Result
      debug:
         msg: "{{result}}"
      tags: case_mvscmd
``` 
and returns:
```
ok: [zvm] => {
    "msg": {
        "changed": true,
        "cmd": "mvscmd --pgm=HELLOPGM  --steplib=ANSIBLE.COBOL.LOADLIB --sysprint=*",
        "delta": "0:00:01.225416",
        "end": "2023-03-20 19:55:03.213754",
        "failed": false,
        "msg": "",
        "rc": 0,
        "start": "2023-03-20 19:55:01.988338",
        "stderr": "SIMPLE HELLO WORLD",
        "stderr_lines": [
            "SIMPLE HELLO WORLD"
        ],
        "stdout": "",
        "stdout_lines": []
    }
}
```

I did dig down a bit to this point in the mdule_utils/zos_mvs_raw (which by the way is not an ideal name, looks too much like a module) , here I forced in some code of my own:

This did not return anything different, I was hoping zoau could manage the data set if we passed in a sysprint with `*`:
```
        rc, out, err = module.run_command("mvscmd --pgm=HELLOPGM --steplib=ANSIBLE.COBOL.LOADLIB --sysprint=*")
        return MVSCmdResponse(rc, out, err)
```

Going a bit further, I tweaked the code and added the err and out streams:
```
        rc, out, err = module.run_command("mvscmd --pgm=HELLOPGM --steplib=ANSIBLE.COBOL.LOADLIB --sysprint=*")
        raise Exception("Command is:" + command + " out: " + out + " err: " + err)
        return MVSCmdResponse(rc, out, err)
``` 
and got (notice the err stream now has SIMPLE HELLO WORLD):
```
 "Exception('Command is:mvscmd  -v --pgm=HELLOPGM   --steplib=ANSIBLE.COBOL.LOADLIB --sysprint=OMVSADM.P3554828.T0300376.C0000000  out:  err: SIMPLE HELLO WORLD\\n')", "ret_code": {"code": 8}}
```

This tells me the issue is someplace in the `return MVSCmdResponse(rc, out, err)` code. 

For this you will need to[ run the playbook here](https://github.com/ansible-collections/ibm_zos_core/issues/633) to have a program else one of your choosing.

I forgot to mention that the command that we generate for mvscmd looks like:
```
mvscmd   --pgm=HELLOPGM   --steplib=ANSIBLE.COBOL.LOADLIB --sysprint=OMVSADM.P6777460.T0547658.C0000000 '
```
You can see Ansible creates the temporary data set vs ZOAU doing so, it might be better we keep that control but alternately could be passed to zoau to manage with a `*`. 

Depending on what is discovered in `MVSCmdResponse` we should document what we do with sysprint, eg will the streams br merged  into one (STDOUT , STDERR and I suppose sysprint)  but we don't really explain the behavior. I would recommend for now the easiest and less disruptive approach is to merge all the streams into the content (output) (so stdout/stderr/sysprint) all go to content, and then if there is an error a users watches the RC. In the future we could consider separating them out as different streams and maybe a boolean to merge. 

The other option is to evaluate using the zoautil_py.execute(....) instead and see if this corrects the behavior over using MVSCmdResponse.

**Comment by fernandofloresg** [comment]
Here is a playbook on how to create a LOADLIB 

```yaml
- hosts : zvm
  collections : 
    - ibm.ibm_zos_core
  gather_facts: no
  vars:
    ZOAU: "/zoau/v1.3.4"
    PYZ: "/allpython/3.11/usr/lpp/IBM/cyp/v3r11/pyz"
    DATASET_SRC_NAME: "OMVSADM.NAZARE.WDEPLOY.CORE140.LOADLIB"
    DATASET_DEST_NAME: "SYS1.PROCLIB"
  environment: "{{ environment_vars }}"
  tasks:
    - name: Delete a data set if it exists
      zos_data_set:
        name: ANSIBLE.COBOL.LOADLIB
        state: absent

    - name: Delete a data set if it exists
      zos_data_set:
        name: APM001.TEST94X.SCSQSNLE
        state: absent

    - name: Delete a data set if it exists
      zos_data_set:
        name: ANSIBLE.COBOL.LOADLIB2
        state: absent

    - name: Delete a data set if it exists
      zos_data_set:
        name: ANSIBLE.COBOL.LOADLIB3
        state: absent
      
    - name: Create/replace the PDS for the COBOL program
      zos_data_set:
        name: ANSIBLE.COBOL.SRC
        type: pdse
        space_primary: 2
        space_type: m
        record_format: fb
        record_length: 80
        block_size: 3120
        replace: true
      register: result

    - name: Create member ANSIBLE.COBOL.SRC(HELLOSRC)
      zos_data_set:
        name: ANSIBLE.COBOL.SRC(HELLOSRC)
        state: present
        replace: true
        type: member
      register: result

    - name: Create member ANSIBLE.COBOL.SRC(HELLOSRC2)
      zos_data_set:
        name: ANSIBLE.COBOL.SRC(HELLOSR2)
        state: present
        replace: true
        type: member
      register: result
  
    - name: Inline COBOL to the PDS member HELLOSRC
      zos_copy:
        content: |4
                   IDENTIFICATION DIVISION.
                   PROGRAM-ID. HELLOWRD.

                   PROCEDURE DIVISION.
                       DISPLAY 'SIMPLE HELLO WORLD'.
                       STOP RUN.
        dest: ANSIBLE.COBOL.SRC(HELLOSRC)
        force: yes
      register: result

    - name: Inline COBOL to the PDS member HELLOSRC
      zos_copy:
        content: |4
                   IDENTIFICATION DIVISION.
                   PROGRAM-ID. HELLOWRD.

                   PROCEDURE DIVISION.
                       DISPLAY 'SIMPLE HELLO WORLD'.
                       STOP RUN.
        dest: ANSIBLE.COBOL.SRC(HELLOSR2)
        force: yes
      register: result

    - name: Create PDSE for module linking the cobol copiled source
      zos_data_set:
        name: ANSIBLE.COBOL.LOADLIB
        type: pdse
        space_primary: 2
        space_type: m
        record_format: u
        record_length: 0
        block_size: 32760
        replace: true
      register: result

    - name: Compile and link edit the code into a load module
      zos_job_submit:
        src: "{{playbook_dir}}/files/COMPLINK.jcl"
        location: local
        wait_time_s: 60
        encoding:
          from: ISO8859-1
          to: IBM-1047
      register: result 

    - name: Compile and link edit the code into a load module
      zos_job_submit:
        src: "{{playbook_dir}}/files/COMPLINK2.jcl"
        location: local
        wait_time_s: 60
        encoding:
          from: ISO8859-1
          to: IBM-1047
      register: result

    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:

    - name: Copying system link listed libraries - {{ inventory_hostname }}
      zos_copy:
        src: "ANSIBLE.COBOL.LOADLIB(*)"
        dest: "PM001.TEST94X.SCSQSNLE"
        remote_src: true
        force: true
        executable: true
        # aliases: true
        tmp_hlq:  PM001
      register: result_zos_copy
```

Which requires COMPLINK.JCL

```jcl
// *****************************************************************************
//* Copyright (c) IBM Corporation 2021
//* ****************************************************************************
//*
//* ****************************************************************************
//* Configure the job card as needed, most common keyword parameters often
//* needing editing are:
//* CLASS:      Used to achieve a balance between different types of jobs and
//*             avoid contention between jobs that use the same resources.
//* MSGLEVEL:   Controls how the allocation and termination messages are
//*             printed in the job's output listing (SYSOUT).
//* MSGCLASS:   Assign an output class for your output listing (SYSOUT)
//*
//* COBOL pattern for this compile and link
//* COBOL SRC
//*         '-> COMPILE
//*                   '-> OBJ CODE
//*                              '-> LINK EDIT
//*                                          '->LOAD MODULE
//*                                                        '->GO
//*                                                            '-> HELLOPGM.jcl
//*
//* SYSIN:      The COBOL source in DSN ANSIBLE.COBOL.SRC(HELLOSRC)
//* SYSPRINT:   The output
//* SYSLIN:     Where the COBOL binary is written, using &&LOADSET and parms to
//*             manage this but you could create a PDS such as
//*             DSN=ANSIBLE.COBOL.OBJ,UNIT=SYSDA,
//*             DISP=(MOD,KEEP),SPACE=(TRK,(3,3))
//* SYSUT:      Statements define the utility data sets that the compiler
//*             will use to process the source program
//*
//* SYSMDECK:   Required for all compilations, it will contain a copy
//*             of the updated input source after library processing
//* ****************************************************************************
//*
//* ****************************************************************************
//* COMPILE A COBOL PROGRAM
//* ****************************************************************************
//*
//COMPLINK  JOB MSGCLASS=H,MSGLEVEL=(1,1),NOTIFY=&SYSUID,REGION=0M
//STEP1     EXEC PGM=IGYCRCTL
//STEPLIB   DD DSN=IGYV5R10.SIGYCOMP,DISP=SHR
//          DD DSN=IGYV5R10.SIGYMAC,DISP=SHR
//SYSIN     DD DISP=SHR,DSN=ANSIBLE.COBOL.SRC(HELLOSRC)
//SYSPRINT  DD SYSOUT=*
//SYSLIN   DD  UNIT=SYSDA,DISP=(MOD,PASS),
//             SPACE=(CYL,(1,1)),
//             DCB=(RECFM=FB,LRECL=80,BLKSIZE=27920),
//             DSN=&&LOADSET
//SYSUT1    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT2    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT3    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT4    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT5    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT6    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT7    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT8    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT9    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT10   DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT11   DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT12   DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT13   DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT14   DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT15   DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSMDECK  DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//*
//* ****************************************************************************
//* LINKEDIT A COBOL PROGRAM
//* SYSLMOD: The PDSE where the link editor will create a module, don't create
//*          the member, let the link editor do this else you will get an OF4
//* SYSLIN: The binder reads the object deck in this DD which is created in the
//*         compile step. If you had not used &&LOADSET you would need to pass
//*         your DSN such as DSN=ANSIBLE.COBOL.OBJ,DISP=(OLD,KEEP)
//* ****************************************************************************
//*
//LKED     EXEC PGM=IEWL,REGION=0M
//SYSPRINT DD  SYSOUT=*
//SYSLIB   DD  DSN=CEE.SCEELKED,DISP=SHR
//         DD  DSN=CEE.SCEELKEX,DISP=SHR
//SYSLMOD  DD  DSN=ANSIBLE.COBOL.LOADLIB(HELLOSRC),
//             DISP=SHR
//SYSUT1   DD  UNIT=SYSDA,DCB=BLKSIZE=1024,
//             SPACE=(TRK,(3,3))
//SYSTERM  DD  SYSOUT=*
//SYSPRINT DD  SYSOUT=*
//SYSLIN   DD  DSN=&&LOADSET,DISP=(OLD,KEEP)
//         DD  *
  ALIAS    HELLO
  NAME     HELLOSRC
//*
//SYSIN    DD  DUMMY

```

COMPLINK2.JCL

```jcl
// *****************************************************************************
//* Copyright (c) IBM Corporation 2021
//* ****************************************************************************
//*
//* ****************************************************************************
//* Configure the job card as needed, most common keyword parameters often
//* needing editing are:
//* CLASS:      Used to achieve a balance between different types of jobs and
//*             avoid contention between jobs that use the same resources.
//* MSGLEVEL:   Controls how the allocation and termination messages are
//*             printed in the job's output listing (SYSOUT).
//* MSGCLASS:   Assign an output class for your output listing (SYSOUT)
//*
//* COBOL pattern for this compile and link
//* COBOL SRC
//*         '-> COMPILE
//*                   '-> OBJ CODE
//*                              '-> LINK EDIT
//*                                          '->LOAD MODULE
//*                                                        '->GO
//*                                                            '-> HELLOPGM.jcl
//*
//* SYSIN:      The COBOL source in DSN ANSIBLE.COBOL.SRC(HELLOSRC)
//* SYSPRINT:   The output
//* SYSLIN:     Where the COBOL binary is written, using &&LOADSET and parms to
//*             manage this but you could create a PDS such as
//*             DSN=ANSIBLE.COBOL.OBJ,UNIT=SYSDA,
//*             DISP=(MOD,KEEP),SPACE=(TRK,(3,3))
//* SYSUT:      Statements define the utility data sets that the compiler
//*             will use to process the source program
//*
//* SYSMDECK:   Required for all compilations, it will contain a copy
//*             of the updated input source after library processing
//* ****************************************************************************
//*
//* ****************************************************************************
//* COMPILE A COBOL PROGRAM
//* ****************************************************************************
//*
//COMPLINK  JOB MSGCLASS=H,MSGLEVEL=(1,1),NOTIFY=&SYSUID,REGION=0M
//STEP1     EXEC PGM=IGYCRCTL
//STEPLIB   DD DSN=IGYV5R10.SIGYCOMP,DISP=SHR
//          DD DSN=IGYV5R10.SIGYMAC,DISP=SHR
//SYSIN     DD DISP=SHR,DSN=ANSIBLE.COBOL.SRC(HELLOSR2)
//SYSPRINT  DD SYSOUT=*
//SYSLIN   DD  UNIT=SYSDA,DISP=(MOD,PASS),
//             SPACE=(CYL,(1,1)),
//             DCB=(RECFM=FB,LRECL=80,BLKSIZE=27920),
//             DSN=&&LOADSET
//SYSUT1    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT2    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT3    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT4    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT5    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT6    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT7    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT8    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT9    DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT10   DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT11   DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT12   DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT13   DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT14   DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSUT15   DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//SYSMDECK  DD SPACE=(80,(10,10),,,ROUND),UNIT=SYSDA
//*
//* ****************************************************************************
//* LINKEDIT A COBOL PROGRAM
//* SYSLMOD: The PDSE where the link editor will create a module, don't create
//*          the member, let the link editor do this else you will get an OF4
//* SYSLIN: The binder reads the object deck in this DD which is created in the
//*         compile step. If you had not used &&LOADSET you would need to pass
//*         your DSN such as DSN=ANSIBLE.COBOL.OBJ,DISP=(OLD,KEEP)
//* ****************************************************************************
//*
//LKED     EXEC PGM=IEWL,REGION=0M
//SYSPRINT DD  SYSOUT=*
//SYSLIB   DD  DSN=CEE.SCEELKED,DISP=SHR
//         DD  DSN=CEE.SCEELKEX,DISP=SHR
//SYSLMOD  DD  DSN=ANSIBLE.COBOL.LOADLIB(HELLOSRW),
//             DISP=SHR
//SYSUT1   DD  UNIT=SYSDA,DCB=BLKSIZE=1024,
//             SPACE=(TRK,(3,3))
//SYSTERM  DD  SYSOUT=*
//SYSPRINT DD  SYSOUT=*
//SYSLIN   DD  DSN=&&LOADSET,DISP=(OLD,KEEP)
//SYSIN    DD  DUMMY
//*

```


You can use just 1 to create the LOADLIB
