### ISSUE TITLE
[Enabler] Investigate using `transfer_method = piped` to see if it helps binary reads

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#709]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

- [ ] Investigate using `transfer_method = piped`, I believe `piped` is using `dd` to do what what SFTP or SCP was doing. This may break zos_ibm_core modules but that is ok for now, point is to understand the community work around.

**Comment by ketankelkar** [comment]
some docs - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/ssh_connection.html#parameter-ssh_transfer_method

**Comment by ketankelkar** [comment]
the transfer method doesn't seem to affect lineinfile (or blockinfile). However, i found interesting behavior with copy.

With `ansible 2.14` & `pyz3.10` & `ansible_ssh_transfer_method: piped`:
The copy module `fails` with a mismatched checksum error. However, the output reports the checksum, and when I inserted that checksum into the `checksum` param to force the copy through, the copied over file on the z/OS side showed that the file was copied over successfully, no need for iconv.

With `ansible 2.14` & `pyz3.19` & `ansible_ssh_transfer_method: piped`: The file copy works without any issue.

**Comment by ketankelkar** [comment]
Upon some additional investigation, I've discovered the following:

With the default ssh transfer method, both pyz 3.9 and 3.10+ transfer a file over in utf and leave it untagged. 
With the ssh transfer method set to 'piped' and pyz3.9, the file is converted to EBCDIIC when copied over to target. 

With ssh transfer method set to 'piped' and pyz3.10+, the copy module fails with a checksum error.
```
fatal: [ec33018]: FAILED! => {"changed": false, "checksum": "af949f951dd4827afb33110dd2da768492f5d820", "expected_checksum": "dfcfc5b6f9b2a181c1c4ad9ffa8b0adbf55a0b73", "msg": "Copied file does not match the expected checksum. Transfer failed."}
```

 It is possible to override the checksum error via the 'checksum' module param in which case the file is once again successfully transferred over to the z/OS target also in EBCDIIC. 

Turning off pipelining with transfer method 'piped' with pyz3.10+ fails even more spectacularly:
```fatal: [ec33018]: FAILED! => {"changed": false, "module_stderr": "Shared connection to ec33018a.vmec.svl.ibm.com closed.\r\n", "module_stdout": "?#?/>???Ȃ?\u0006\u0016\u0006\u0016?ʂ?Ă?_?:?/??>?@?/?,?\u001b#?>Ȁ?'\u001b?/?Ȃ?\u0016?\u0016?\u0005?\u0004\u0005?\u0016\u0016?\u0004?\u0016\u0016\u0006?\u0004?>?\u0016?\u0016?\u0005?\u0004\u0005?\u0016\u0016?\u0004?\u0016?\u0006\u0004?%?/?\u0006\u0016?\u0016?_?ł?>???/??>?#?_??%?^/?˂?#?^?/?^?/?/_˂?:?/??>?@?/?,?\u001b#?>Ȁ?'\u001b?^?^?%%?>^/?^>?%?>?^?_?`^?>?˂?/?΂?>?%%?ʂ?>?%%?/?%?>?%%?/?˂?>?%%?_??˂?>?%%?>?>?%%'''?", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 0}```


Playbook I ran:
```
---
- hosts: ec33018
  gather_facts: no
  environment: "{{ environment_vars }}"
  vars:

    # docs - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/ssh_connection.html#parameter-pipelining
    ansible_ssh_pipelining: yes

    # docs - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/ssh_connection.html#parameter-ssh_transfer_method
    ansible_ssh_transfer_method: piped


  tasks:

    - name: copy file over
      copy:
        src: files/AAA
        dest: /u/oeusr01
        # checksum: af949f951dd4827afb33110dd2da768492f5d820
```
contents of file copied over:
```
AAA
BBB
CCC
DDD
EEE

```
inventory file:
```
all:
  hosts:
    ec33018:
      ansible_host: ec33018a.ec.host.address
      ansible_user: omvsadm
```

3.9 config:
```
ZOAU: "/zoau/v1.2.2"
PYZ: "/allpython/3.9/usr/lpp/IBM/cyp/v3r9/pyz"

ansible_python_interpreter: "{{ PYZ }}/bin/python3"

environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  PYTHONPATH: "{{ ZOAU }}/lib"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
```
3.10 config:
```
ZOAU: "/zoau/v1.2.2"
PYZ: "/allpython/3.10/usr/lpp/IBM/cyp/v3r10/pyz"

ansible_python_interpreter: "{{ PYZ }}/bin/python3"

environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  PYTHONPATH: "{{ ZOAU }}/lib"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:/bin:/var/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
  PYTHONSTDINENCODING: "cp1047"
```

**Comment by ketankelkar** [comment]
Changing the transfer method to 'piped' seems to have a positive effect on the builtin script module. Whereas with transfer methods scp and sftp with both pyz3.9 and 3.10 both fail to run the script module, when transfer method is set to piped, for both pyz3.10 and pyz3.9, the specified script file runs as expected. 

module failure message for 3.9/3.10 with scp/sftp -- it's the same for all:
```
TASK [try script] *************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NoneType: None
fatal: [ec33018]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 1, "stderr": "Shared connection to ec33018a.vmec.svl.ibm.com closed.\r\n", "stderr_lines": ["Shared connection to ec33018a.vmec.svl.ibm.com closed."], "stdout": "/.ansible/tmp/ansible-tmp-1689379219.785449-43281-218934829983492/mk.sh 1: FSUM7729 missing closing \"'\"\r\n", "stdout_lines": ["/.ansible/tmp/ansible-tmp-1689379219.785449-43281-218934829983492/mk.sh 1: FSUM7729 missing closing \"'\""]}
```

playbook:
```
---
- hosts: ec33018
  gather_facts: no
  environment: "{{ environment_vars }}"
  vars:

    # docs - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/ssh_connection.html#parameter-pipelining
    ansible_ssh_pipelining: yes


    # docs - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/ssh_connection.html#parameter-ssh_transfer_method
    ansible_ssh_transfer_method: piped
    # ansible_ssh_transfer_method: scp
    # ansible_ssh_transfer_method: sftp

  tasks:
    - name: try script
      ansible.builtin.script: "{{ playbook_dir }}/files/mk.sh"
```

script file mk.sh:
```
touch $(date | awk '{print $4}' )
```
