### ISSUE TITLE
[Enhancement] [zos_copy] Improve performance when copying an entire PDS with thousands of members

### ISSUE THREAD

**Issue by adn1107** [ansible-collections/ibm_zos_core#764]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Ansible module

zos_copy

### Enhancement or feature description

looks like zos_copy is copying 1 member at a time

**Comment by ddimatos** [comment]
@adn1107, i suppose you did something like and saw sequential copies? 
```
- name: Copy all members inside a PDS to another PDS
  zos_copy:
    src: SOME.SRC.PDS(*)
    dest: SOME.DEST.PDS
    remote_src: true
```
