### ISSUE TITLE
[Bug] Regression copying a single file to a PDS 

### ISSUE THREAD

**Issue by phaumer** [ansible-collections/ibm_zos_core#774]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.2

### IBM Enterprise Python

v3.9.x

### IBM z/OS Ansible core Version

v1.5.0

### ansible-version

latest

### z/OS version

v2.5

### Ansible module

zos_copy

### Bug description

With v1.4 I could write the following 

```yaml
    - name: Copy Debug JCL to JCL data set
      ibm.ibm_zos_core.zos_copy:
        src: "{{ tempdir.path }}/DEBUG"
        dest: "IBMUSER.SAMPLE.JCL"
```

and it would upload the file `DEBUG` to `IBMUSER.SAMPLE.JCL(DEBUG)`

In 1.5 this operation finished without an error, but nothing gets copied. In verbose more the output shows

```
ok: [devtest1] => {"changed": null, "dest": null, "is_binary": false}
```

The only workaround that works in 1.5 is 

```yaml
    - name: Copy Debug JCL to JCL data set
      ibm.ibm_zos_core.zos_copy:
        src: "{{ tempdir.path }}/DEBUG"
        dest: "IBMUSER.SAMPLE.JCL(DEBUG)"
        force: true
```

requiring to provide the name twice, increasing maintenance of the code. :-) 

The following still works in 1.5, though

```yaml
    - name: Copy cobol copybooks
      ibm.ibm_zos_core.zos_copy:
        src: "{{ playbook_dir }}/../COPYBOOK/"
        dest: "IBMUSER.SAMPLE.COBOL"
```

If the directory contains the files `SAM1.cbl` and `SAM2.cbl` it creates `IBMUSER.SAMPLE.COBOL(SAM1)` and `IBMUSER.SAMPLE.COBOL(SAM2)`

### Ansible configuration.

```YAML
[defaults]
deprecation_warnings=False
```
