### ISSUE TITLE
[Documentation] WTOR filter is missing doc

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#831]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

When generating the changelog, it reports that there is missing doc for the WTOR filer that ships with the collection. See below.

```
`ddimatos:[ ~/git/github/ibm_zos_core ]./ac --venv-start
-----------------------------------------------------------------------
Starting managed python virtual environment: venv-2.15
-----------------------------------------------------------------------
(venv-2.15) antsibull-changelog lint
(venv-2.15) antsibull-changelog release
[WARNING]: filter ibm.ibm_zos_core.filter_wtor_messages missing documentation
(or could not parse documentation): No documentation available for
ibm.ibm_zos_core.filter_wtor_messages
(/private/var/folders/7f/12ckwlks01g7qdthvsby9rt00000gn/T/antsibull-changelogev
azekbv/collections/ansible_collections/ibm/ibm_zos_core/plugins/filter/wtor.py)
```

Some links to help:
[The filter in question](https://ibm.github.io/z_ansible_collections_doc/ibm_zos_core/docs/source/filters.html)
[Example we can use to model doc after](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/b64decode.yml)
[More on filters and doc](https://docs.ansible.com/ansible/latest/dev_guide/developing_plugins.html#filter-plugins)

Started a draft (will need work, its only a start):
```
DOCUMENTATION:
  name: filter_wtor_messages
  author: IBM ansible core team
  version_added: 'historical'
  short_description: .......
  description:
    - ......
    - ...
  positional: _input
  options:
    _input:
      description: 
      type: string
      required: true
​
EXAMPLES: |
  # Filter a string
  wtor: "{{ 'bG9sYQ==' | b64decode }}"
​
RETURN:
  _value:
    description: The contens.....
    type: string
```

Its not in the scope of this issue but if we continue to invest in filters it might be worth updating the doc tooling to support filters.
