### ISSUE TITLE
[Bug] [zos_copy] Missing 'library' for dest_data_set sub option type.

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#920]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Documentation issue description

Module zos_copy is missing the type library that enables and supports an executable. Although a PDS/E will suffice for an executable, this sets the DSNTYPE , thus its simply a doc issue, the code can already support it. 

Refer to zos_data_set module type to additional examples. 

The zos_copy documentation below that needs updating:
```
  dest_data_set:
    description:
      - Data set attributes to customize a C(dest) data set to be copied into.
    required: false
    type: dict
    suboptions:
      type:
        description:
          - Organization of the destination
        type: str
        required: true
        choices:
          - KSDS
          - ESDS
          - RRDS
          - LDS
          - SEQ
          - PDS
          - PDSE
          - MEMBER
          - BASIC
 ```

You will also need to update the choices module spec , eg
```
            dest_data_set=dict(
                type='dict',
                required=False,
                options=dict(
                    type=dict(
                        type='str',
                        choices=['BASIC', 'KSDS', 'ESDS', 'RRDS',
                                 'LDS', 'SEQ', 'PDS', 'PDSE', 'MEMBER'],
                        required=True,
                    ),
```
### IBM z/OS Ansible core Version

v1.7.0-beta.1

### Ansible module

zos_copy
