### ISSUE TITLE
stderr: "Invalid argument \"?`?\u0015\" for type \"encoding\"."

### ISSUE THREAD

**Issue by SubhasishSarkarIndia** [ansible-collections/ibm_zos_core#967]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Are the dependencies a supported version?

- [X] The dependencies are supported.

### IBM Z Open Automation Utilities

v1.2.5

### IBM Enterprise Python

v3.14.x

### IBM z/OS Ansible core Version

v1.9.0

### ansible-version

latest

### z/OS version

v2.4

### Ansible module

zos_job_output

### Bug description

My playbook jcl_job.yml looks like:

```
---
- hosts: imsa
  collections:
    - ibm.ibm_zos_core
  gather_facts: false

  tasks:
    - name: Submit a JCL Job from a PDS member
      zos_job_submit:
        src: HLQ.CZAGENT.JOBS.SS.PERSONAL(HELLOWLD)
        location: DATA_SET
        max_rc: 0

      register: response
```

When I execute the playbook using ansible-playbook -i inventory.yml jcl_job.yml, I receive the following error message:

TASK [Submit a JCL Job from a PDS member] ******************************************************************************************************************************
task path: /home/ssansible/.local/lib/python3.10/site-packages/ansibless/playbooks/jcl_job.yml:12
[DEPRECATION WARNING]: Module "ibm.ibm_zos_core.zos_job_submit" returned non UTF-8 data in the JSON response. This will become an error in the future. This feature
will be removed in version 2.18. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Non UTF-8 encoded data replaced with "?" while displaying text to stdout/stderr, this is temporary and will become an error. This feature will
be removed in version 2.18. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [imsa]: FAILED! => {"changed": false, "msg": "Parameter verification failed", "stderr": "Invalid argument \"?`?\u0015\" for type \"encoding\".", "stderr_lines": ["Invalid argument \"?`?\u0015\" for type \"encoding\"."]}

### Playbook verbosity output.

[Playbook verbosity output.txt](https://github.com/ansible-collections/ibm_zos_core/files/12611737/Playbook.verbosity.output.txt)

### Ansible configuration.

```YAML
ssansible@IN-subsarka-W4:~/.local/lib/python3.10/site-packages/ansibless$ ansible-config view
ansible-config [core 2.15.3]
  config file = /home/ssansible/.local/lib/python3.10/site-packages/ansibless/ansible.cfg
  configured module search path = ['/home/ssansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ssansible/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ssansible/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ssansible/.local/bin/ansible-config
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /home/ssansible/.local/lib/python3.10/site-packages/ansibless/ansible.cfg as config file
[defaults]
        interpreter_python = /shrd/cyp/usr/lpp/IBM/cyp/v3r10/pyz/bin/python3
        remote_user = MVSSAS
        connection_password_file = connection_password_file
        verbosity = 2

[colors]
        verbose = yellow
```

### Contents of the inventory

```YAML
contents of inventory.yml: -

mainframelpars:
  hosts:
    imsa:
  vars:
    _BPXK_AUTOCVT: "ON"
    ZOAU_HOME: "/shrd/zoautil2"
    PYTHONPATH: "/shrd/zoautil2/lib"
    LIBPATH: "/shrd/zoautil2/lib/:/shrd/cyp/usr/lpp/IBM/cyp/v3r10/pyz/lib:/usr/lib:/lib:."
    PATH: "/shrd/zoautil2/bin:/shrd/cyp/usr/lpp/IBM/cyp/v3r10/pyz/bin:/bin"
    _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
    _TAG_REDIR_ERR: "txt"
    _TAG_REDIR_IN: "txt"
    _TAG_REDIR_OUT: "txt"
    LANG: "C"
```

### Contents of `group_vars` or `host_vars`

```YAML
No group_vars or host_vars
```
