### ISSUE TITLE
[Enabler] Recreate UTF-8 warning in a playbook

### ISSUE THREAD

**Issue by ddimatos** [ansible-collections/ibm_zos_core#985]
### Is there an existing issue for this?

- [X] There are no existing issues.

### Enabler description

As part of collaboration #983 this issue is to recreate the UTF-8 warning in a playbook to determine if the warning (even though it can be disabled) will break a playbooks execution.

**Comment by ketankelkar** [comment]
the playbook creates 4 files with the same content:
- untagged ebcdic
- tagged ebcdic
- untagged utf
- tagged utf.

Only the tagged ebcdic and untagged utf-8 create the deprecation warnings.


playbook recreate:
```yml
---
- name: Recreate UTF-8 warning 
  hosts: ec33022
  gather_facts: false
  collections:
    - "ibm.ibm_zos_core"

  vars:

    # content. 
    # '|-' says keep new lines except at the end.
    file_content: |-
      AA
      BB
      CC

    # file paths:
    base_dir: "{{ '/home/ketan/utf8' if 'pok.stglabs' in ansible_host else '/u/oeusr01/setup-files' }}"

    untagged_ibm1047_file: "{{ base_dir }}/untagged-ibm1047.txt"
    tagged_ibm1047_file: "{{ base_dir }}/tagged-ibm1047.txt"
    untagged_utf8_file: "{{ base_dir }}/untagged-utf8.txt"
    tagged_utf8_file: "{{ base_dir }}/tagged-utf8.txt"


    files:
      # - "{{ untagged_ibm1047_file }}" # no
      - "{{ tagged_ibm1047_file }}" # yes
      - "{{ untagged_utf8_file }}" # yes
      # - "{{ tagged_utf8_file }}" # no



  environment: "{{ environment_vars }}"

  tasks:

    - name: Remove base directory {{ base_dir }} if exists.
      file:
        path: "{{ base_dir }}"
        state: absent

    - name: Create base directory {{ base_dir }}.
      file:
        path: "{{ base_dir }}"
        state: directory

    - name: Create untagged ebcdic file {{ untagged_ibm1047_file }}.
      raw: "echo '{{ file_content }}' > {{ untagged_ibm1047_file }}"

    - name: Create tagged ebcdic file {{ tagged_ibm1047_file }}.
      shell: "echo '{{ file_content }}' > {{ tagged_ibm1047_file }}"

    - name: Create untagged utf8 file {{ untagged_utf8_file }}.
      raw: "iconv -f IBM-1047 -t ISO8859-1 {{ untagged_ibm1047_file }} > {{ untagged_utf8_file }}"

    - name: Create tagged utf8 file {{ tagged_utf8_file }}.
      shell: "iconv -f IBM-1047 -t ISO8859-1 {{ tagged_ibm1047_file }} > {{ tagged_utf8_file }}"

      # Ensure correct file tags.
    - name: Remove tag from {{ untagged_ibm1047_file }}.
      shell: "chtag -r {{ untagged_ibm1047_file }}"

    - name: Re-tag ebcdic file to IBM-1047 {{ tagged_ibm1047_file }}.
      shell: "chtag -tc IBM-1047 {{ tagged_ibm1047_file }}"

    - name: Remove tag {{ untagged_utf8_file }}.
      shell: "chtag -r {{ untagged_utf8_file }}"

    - name: Re-tag utf8 file to ISO8859-1 {{ tagged_utf8_file }}.
      shell: "chtag -tc ISO8859-1 {{ tagged_utf8_file }}"

    - name: cat files
      command: "cat {{ item }}"
      loop: "{{ files }}"
      register: output
    
    - name: print output
      debug:
        msg: "{{item.stdout}}"
      loop: "{{ output.results }}"
```

playbook tasks w deprecation warning:
```bash
TASK [cat files] **************************************************************************************************************************************************************************
Tuesday 31 October 2023  15:08:40 -0700 (0:00:14.855)       0:02:56.553 ******* 
changed: [ec33022] => (item=/u/oeusr01/setup-files/tagged-ibm1047.txt)
[DEPRECATION WARNING]: Module "ansible.builtin.command" returned non UTF-8 data in the JSON response. This will become an error in the future. This feature will be removed in version 
2.18. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [ec33022] => (item=/u/oeusr01/setup-files/untagged-utf8.txt)

TASK [print output] ***********************************************************************************************************************************************************************
Tuesday 31 October 2023  15:09:05 -0700 (0:00:25.232)       0:03:21.786 ******* 
ok: [ec33022] => (item={'changed': True, 'stdout': 'AA\nBB\nCC', 'stderr': '', 'rc': 0, 'cmd': ['cat', '/u/oeusr01/setup-files/tagged-ibm1047.txt'], 'start': '2023-10-31 22:08:52.727075', 'end': '2023-10-31 22:08:55.722095', 'delta': '0:00:02.995020', 'msg': '', 'invocation': {'module_args': {'_raw_params': 'cat /u/oeusr01/setup-files/tagged-ibm1047.txt', '_uses_shell': False, 'stdin_add_newline': True, 'strip_empty_ends': True, 'argv': None, 'chdir': None, 'executable': None, 'creates': None, 'removes': None, 'stdin': None}}, 'stdout_lines': ['AA', 'BB', 'CC'], 'stderr_lines': [], 'failed': False, 'item': '/u/oeusr01/setup-files/tagged-ibm1047.txt', 'ansible_loop_var': 'item'}) => {
    "msg": "AA\nBB\nCC"
}
[DEPRECATION WARNING]: Non UTF-8 encoded data replaced with "?" while displaying text to stdout/stderr, this is temporary and will become an error. This feature will be removed in 
version 2.18. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [ec33022] => (item={'changed': True, 'stdout': '\udca0\udca0\udc8e\udce2\udce2\udc8e\udce4\udce4\udc8e', 'stderr': '', 'rc': 0, 'cmd': ['cat', '/u/oeusr01/setup-files/untagged-utf8.txt'], 'start': '2023-10-31 22:09:02.296603', 'end': '2023-10-31 22:09:05.493008', 'delta': '0:00:03.196405', 'msg': '', 'invocation': {'module_args': {'_raw_params': 'cat /u/oeusr01/setup-files/untagged-utf8.txt', '_uses_shell': False, 'stdin_add_newline': True, 'strip_empty_ends': True, 'argv': None, 'chdir': None, 'executable': None, 'creates': None, 'removes': None, 'stdin': None}}, 'stdout_lines': ['\udca0\udca0\udc8e\udce2\udce2\udc8e\udce4\udce4\udc8e'], 'stderr_lines': [], 'failed': False, 'item': '/u/oeusr01/setup-files/untagged-utf8.txt', 'ansible_loop_var': 'item'}) => {
    "msg": "?"
}
```
